### ISSUE TITLE
 Gen Tool 如何指定生成器模式？

### ISSUE THREAD

**Issue by DokiDoki1103** [go-gorm/gen#1013]
## Your Question

gen.WithoutContext

生成无需传入context参数的代码。如果无需传入context，则代码调用方式如：dal.User.First()，否则，调用方式要像这样：dal.User.WithContext(ctx).First()

**Comment by qqxhb** [comment]
@DokiDoki1103 gen的自定义配置比较多，推荐用代码的方式；
gentool适合简单的场景，当然你也可以提一个pr
