### ISSUE TITLE
根据配置文件生成代码里outPath 配置项没生效

### ISSUE THREAD

**Issue by striveQiao** [go-gorm/gen#1017]
outPath : "./gentool" 
这个配置选项没生效，不是在这个目录下生成的dao和query代码，实际是在哪个目录下执行的gentool -c ./gentool.tool命令就是在哪个目录下生成的dao和query代码

**Comment by qqxhb** [comment]
@striveQiao 符合预期的呀，本来这个写的就行相对路径（执行的路径）
