### ISSUE TITLE
生成表唯一索引多加了一个primaryKey属性

### ISSUE THREAD

**Issue by TophillZK** [go-gorm/gen#1036]
版本gorm.io/gen v0.3.23
如果表结构为
create table bs_dictdata_dict(
   type_code        varchar(5) not null,
   dict_code            varchar(60) not null,
   dict_name            varchar(100) not null,
   unique key AK_bs_dictdata_dict (type_code, dict_code)
);
生成的结构体为
type BsDictdataDict struct {
	TypeCode string `gorm:"column:type_code;primaryKey;uniqueIndex:AK_bs_dictdata_dict,priority:1" json:"type_code"`
	DictCode string `gorm:"column:dict_code;primaryKey;uniqueIndex:AK_bs_dictdata_dict,priority:2" json:"dict_code"`
	DictName string `gorm:"column:dict_name;not null" json:"dict_name"`
}

如果表结构为
create table bs_dictdata_dict(
   type_code        varchar(5) not null,
   dict_code            varchar(60) not null,
   dict_name            varchar(100) not null,
   primary key (dict_code),
   unique key AK_bs_dictdata_dict (type_code, dict_code)
);
生成的结构体为
type BsDictdataDict struct {
	TypeCode string `gorm:"column:type_code;not null;uniqueIndex:AK_bs_dictdata_dict,priority:1" json:"type_code"`
	DictCode string `gorm:"column:dict_code;primaryKey;uniqueIndex:AK_bs_dictdata_dict,priority:2" json:"dict_code"`
	DictName string `gorm:"column:dict_name;not null" json:"dict_name"`
}

我认为第一种情况，我没有定义主键primary的时候，不应该把唯一索引也生成出来一个主键的标签。

**Comment by qqxhb** [comment]
@TophillZK 这个是db的默认行为哈，innerdb存储依赖主键索引。如果没有主键的时候，会把第一个非空唯一索引设置为主键索引哈
[If a table contains no primary key, InnoDB automatically promotes the first UNIQUE NOT NULL index to the primary key. This is not supported for UNIQUE NOT NULL indexes that have functional key parts.](https://dev.mysql.com/doc/refman/8.0/en/create-index.html)


你如果确实不想要 可以用GormTag这个option去掉`primaryKey`

**Comment by TophillZK** [comment]
好的，感谢大佬的高效回复~~
