### ISSUE TITLE
根据关联字段的条件过滤 -> 是否有简单的写法

### ISSUE THREAD

**Issue by Asupa** [go-gorm/gen#1044]
## Your Question
举例来说，我使用gen 生成两个model User 和 Project, Project 定义了User 的BelongsTo 关联
`type User{`
`  ...`
`  Username    string    gorm:"column:username;type:varchar(255);not null;uniqueIndex:username,priority:1" json:"username"`
`}`

`type Project struct {`
`   ...`
`   OwnerID  int32  gorm:"column:owner_id;type:int(11);index:owner_id,priority:1" json:"owner_id"`
`   Owner     User   json:"owner"`
`}`

我现在想要查询所有 username="admin“ 的User 作为Owner的CodebaseType记录
我现在的做法是：
`users, err := dal.User.Where(dal.User.Username.Eq("admin")).Find()             // 获取所有username 为admin的user记录`
`userIds := make([]int32,0)`
`for _, userId := range userIds{`
`    userIds = append(userIds, userId)`
`}                                                                             // 获取所有符合条件的user ID`
`projects, err := dal.Project.Where(dal.Project.OwnerID.IN(userIds...)).Find() // 根据Owner ID 查询记录`

我想知道是否有更简单的关联字段过滤方法，比如我期望中的是这样的:)
`dal.Project.Where(dal.Project.Owner.Username.Eq("admin"))`

**Comment by qqxhb** [comment]
@Asupa `FieldType` https://gorm.io/gen/database_to_structs.html#Field-Options

**Comment by qqxhb** [comment]
用join 或者subquery
