### ISSUE TITLE
多where条件，包含主键条件，单记录查询失败

### ISSUE THREAD

**Issue by hww9035** [go-gorm/gen#1054]
使用多个where条件，其中包含主键条件，使用first/take/last单记录查询时，既没有执行查询也没有记录sql日志信息。

比如：
dao.WithContext(c).Where(dao.ID.Eq(1)).Where(dao.Status.Eq(1)).First() 
其中ID是主键，Status是附加状态条件

**Comment by qqxhb** [comment]
@hww9035 写个复现demo吧，如果这个都不能执行，功能基本上就是不可用的状体，不太可能

没有看到sql日志，是通过什么判断没有执行的呢？

sql日志可以加上.Debug()看看

多个条件也可以直接写到一个where里，当然你现在的用法也是没问题的

**Comment by hww9035** [comment]
感谢回复，我重新验证了下没有问题，应该是当时我自己处理不当导致。

**Comment by mimicode** [comment]
我也遇到这个奇怪的问题了，直接用gorm 查询 用take 和 gen的query take查询，生成的查询语句都是一样的 。但后者总是no record ，前者没问题。奇怪怪。用生成的查询语句去数据库查询也可以查到。  整个query 换其它表也是查询不到数据。。。。。
