### ISSUE TITLE
gorm gen生成代码后，一对多，怎么清除关联或者删除关联

### ISSUE THREAD

**Issue by Guwengo** [go-gorm/gen#1058]
gorm gen生成代码后，一对多，怎么清除关联或者删除关联
官网文档中https://gorm.io/zh_CN/gen/associations.html
的方法 u.Languages.Model(&user).Clear()  生成代码 没有找到 Languages方法
是有新的方法吗？还是我使用错误了

**Comment by Guwengo** [comment]
类似普通默认下gorm 的 Association 也没有，如果有办法帮忙写个简单示例的关键代码参考下

**Comment by qqxhb** [comment]
你需要生成的时候指定这个关联关系，这样在user的dao上就会生成Language
