### ISSUE TITLE
Package name of model to generate cannot be the same as the model

### ISSUE THREAD

**Issue by ghodss** [go-gorm/gen#1064]
## Description

When doing basic DAO generation, if the lowercase name of the model is the same as the name of the package that the model is in, e.g. `g.ApplyBasic(user.User{})`, the `users.gen.go` file is generated with compiler errors. Either this use case should be supported or there should be an explicit error message during generation.

**Comment by qqxhb** [comment]
https://gorm.io/gen/database_to_structs.html#Global-Generating-Options
```go
/ WithModelNameStrategy specify model struct name naming strategy, only work when syncing table from db
// If an empty string is returned, the table will be ignored
WithModelNameStrategy(ns func(tableName string) (modelName string))

// WithFileNameStrategy specify file name naming strategy, only work when syncing table from db
WithFileNameStrategy(ns func(tableName string) (fileName string))
```
