### ISSUE TITLE
Will an error be returned on call `UpdateSimple` method updated 0 line data?

### ISSUE THREAD

**Issue by daidai21** [go-gorm/gen#1067]
## Your Question

Will an error be returned on call `UpdateSimple` method updated 0 line data?

## The document you expected this should be explained

https://gorm.io/zh_CN/gen/update.html

![image](https://github.com/go-gorm/gen/assets/36124626/5e2c8fb1-9d00-4306-9e1c-e5f8e1758452)

**Comment by qqxhb** [comment]
No.
