### ISSUE TITLE
Simply update multi columns expr

### ISSUE THREAD

**Issue by to2false** [go-gorm/gen#107]
## Describe the feature

SQL: `update a set b = b + 1, c = c + 1 where d = 4`

Code:
```go
Updates(map[string]interface{}{
	q.B.ColumnName().String():     q.B.Add(1)).RawExpr(),
	q.C.ColumnName().String():     q.C.Add(1).RawExpr(),
})
```

## Motivation

Provide a way to simply this action to reduce code

**Comment by riverchu** [comment]
We have had provided api `UpdateSimple` may solve your problem, and usage is [here](https://github.com/go-gorm/gen#update-single-column).
However, `UpdateSimple` accept only 1 parameter for now, and i will optimize it in next version coming soon

**Comment by riverchu** [comment]
`UpdateSimple` now accept multi parameters in release `v0.0.20`
