### ISSUE TITLE
[error] check interface fail: sql [] build err:sql is null

### ISSUE THREAD

**Issue by lemon-360** [go-gorm/gen#1071]
package model

import "gorm.io/gorm"

type User struct {
	gorm.Model
	Name string
	Role string
}

type Company struct {
	gorm.Model
	CompanyName string
}

package main

import (
	"gorm.io/driver/mysql"
	"gorm.io/gen"
	"gorm.io/gorm"
	"orm/model"
)

type Querier interface {
	FilterWithNameAndRole(name, role string) ([]gen.T, error)
}

func main() {
	g := gen.NewGenerator(gen.Config{
		OutPath: "./query",
		Mode:    gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface,
	})

	gormdb, _ := gorm.Open(mysql.Open("lemon:abc123@tcp(rm-wz9g34jp31238k54fvo.mysql.rds.aliyuncs.com:3306)/mydb?charset=utf8mb4&parseTime=True&loc=Local"))
	g.UseDB(gormdb)

	g.ApplyInterface(func(Querier) {}, model.User{}, model.Company{})
	g.Execute()
}

运行报错
[error] check interface fail: sql [] build err:sql is null
panic: check interface fail

**Comment by qqxhb** [comment]
@lemon-360 Querier不要和main在一个路径下就好了
