### ISSUE TITLE
When the association operation is supported

### ISSUE THREAD

**Issue by wuqinqiang** [go-gorm/gen#109]
For example: Preloading..........

**Comment by riverchu** [comment]
Coming soon, we will inform you when we finish it🤘

**Comment by riverchu** [comment]
Now, we support Preloading at `v0.0.24-alpha`.And doc is [here](https://github.com/go-gorm/gen#preloading)

**Comment by riverchu** [comment]
New release `v0.0.24` is online

**Comment by to2false** [comment]
@riverchu How to gen associations model?

**Comment by riverchu** [comment]
> @riverchu How to gen associations model?

use exist model struct
```go
g.ApplyBasic(model.Customer{}, model.CreditCard{})
```

model's struct: 
```go
type Customer struct {
	gorm.Model
	CreditCards []CreditCard `gorm:"foreignKey:CustomerRefer"`
}

type CreditCard struct {
	gorm.Model
	Number        string
	CustomerRefer uint
}
```

**Comment by to2false** [comment]
If the model is generated directly and is not editable, what to do?

**Comment by riverchu** [comment]
> > use exist model struct
> 
> @riverchu If the model is generated directly and is not editable, what to do?

We will support generated model ASAP. U may start another issue about this

**Comment by to2false** [comment]
ok
