### ISSUE TITLE
 升级 gorm.io/gen v0.3.25 后，为什么使用 g.GenerateAllTable() 生成的字段有变化？

### ISSUE THREAD

**Issue by November-12** [go-gorm/gen#1090]
例如：
<img width="228" alt="image" src="https://github.com/go-gorm/gen/assets/10138778/bf2272ac-7bee-4abc-b061-852ecace4c76">

<img width="266" alt="image" src="https://github.com/go-gorm/gen/assets/10138778/4222c8b8-6baf-45a6-a704-7ad0ba22b800">

<img width="249" alt="image" src="https://github.com/go-gorm/gen/assets/10138778/c6606c7d-b5c2-4bc5-88d6-a106041460c1">

在数据库字段没变的情况下，以s结尾的字段，都被去掉了s，以Data结尾的字段，都变成了Datum，这个问题如何处理？

**Comment by November-12** [comment]
@jinzhu

**Comment by qqxhb** [comment]
@November-12 是不是改了这个配置，https://gorm.io/docs/gorm_config.html#NamingStrategy
`    SingularTable, // use singular table name, table for `User` would be `user` with this option enabled
`

**Comment by November-12** [comment]
> @November-12 是不是改了这个配置，https://gorm.io/docs/gorm_config.html#NamingStrategy ` SingularTable, // use singular table name, table for`User`would be`user`with this option enabled`

 您好～确实没有改动过任何配置，仅仅升级了版本。

**Comment by qqxhb** [comment]
@November-12 那辛苦配置下 上面那个配置，看看能解决问题不

**Comment by November-12** [comment]
> @November-12 那辛苦配置下 上面那个配置，看看能解决问题不

尝试了之后无法解决，这个SingularTable他影响的是“表名”的单复数，我遇到的问题是“字段名”的单复数被修改了，这个好像没有没发现可以配置的地方。

**Comment by November-12** [comment]
> @November-12 如果是默认的话，字段名也会用这个策略，`SchemaName` 方便发下你的配置吗？gorm和gen的配置

gen的配置：
`package main

import (
	initialize "project/initialize"

	"gorm.io/gen"
)

func main() {
	g := gen.NewGenerator(gen.Config{
		OutPath:       "../../query",
		Mode:          gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface, // generate mode
		FieldNullable: true,
	})
	initialize.ViperInit("../../configs/conf.yml")
	initialize.LogInIt()
	gormdb := initialize.PgInit()
	if gormdb == nil {
		panic("gormdb is nil")
	}
	g.UseDB(gormdb)
	g.ApplyBasic(
		g.GenerateAllTable()...,
	)
	g.Execute()
}
`


gorm的配置：
`func PgConnect(config *DbConfig) (*gorm.DB, error) {
	dataSource := fmt.Sprintf("host=%s port=%d dbname=%s user=%s password=%s sslmode=disable TimeZone=%s",
		config.Host, config.Port, config.DbName, config.Username, config.Password, config.TimeZone)

	newLogger := logger.New(Writer{}, logger.Config{
		SlowThreshold:             time.Duration(config.SlowThreshold) * time.Millisecond,
		LogLevel:                  logger.LogLevel(config.LogLevel),
		IgnoreRecordNotFoundError: true,
		Colorful:                  true,
	})

	var err error
	db, err := gorm.Open(postgres.Open(dataSource), &gorm.Config{Logger: newLogger})
	if err != nil {
		return nil, fmt.Errorf("连接数据库失败: %v", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("获取原生数据库连接失败: %v", err)
	}

	sqlDB.SetMaxIdleConns(config.IdleConns)
	sqlDB.SetMaxOpenConns(config.OpenConns)
	sqlDB.SetConnMaxLifetime(time.Hour)

	log.Println("连接数据库完成...")
	// 检查版本
	err = CheckVersion(db)
	if err != nil {
		fmt.Println(err)
	}
	return db, nil
}`

**Comment by November-12** [comment]
> @November-12 如果是默认的话，字段名也会用这个策略，`SchemaName` 方便发下你的配置吗？gorm和gen的配置

我这边测试了几遍‘SingularTable’这个参数，确实是表名会应用这个策略，字段名则不会，都会被转换为单数。

**Comment by qqxhb** [comment]
@November-12 配置没看出问题，但是逻辑我也确认了 第一个版本到现在都是没变化的
`if ns, ok := db.NamingStrategy.(schema.NamingStrategy); ok {
			ns.SingularTable = true
			m.Name = ns.SchemaName(ns.TablePrefix + m.Name)
		}`
