### ISSUE TITLE
能否数据库不加外键也能使用FieldRelateConfig

### ISSUE THREAD

**Issue by dfang** [go-gorm/gen#1098]
目前表不加外键去生成BelongsTo关系的字段，会报错 define a valid foreign key for relations or implement the Valuer/Scanner interface

eg. 能否ordres表不加user_id外键也能支持 Order里加User字段呢

**Comment by paradox-lab2** [comment]
可以不加物理外键，用代码实现逻辑外键的，但orders还是要有一个user_id字段才好实现逻辑外键
