### ISSUE TITLE
请问使用表达式更新时是否可以增加判断条件呢？

### ISSUE THREAD

**Issue by whit15** [go-gorm/gen#1103]
我们项目有些字段是设计为可Null的，遇到问题是在Update/UpdateSimple时gen的.Value()和Null()方法是分开的，请问如何在一个表达式中使用类似Scopes来判断条件动态添加不同的赋值方法呢？

预期如下述伪代码
`u.WithContext(ctx).Where(u.ID.Eq(111)).UpdateSimple(
    u.Age.Add(1), 
    (x != nil) ? u.Number.Value(*x) : u.Number.Null(),
)`
Number字段我们是可Null的，想要根据x变量来判断入库时更新为值还是null

感谢大佬们辛苦开源，期待您的回复，谢谢。

**Comment by qqxhb** [comment]
@whit15 比如你把 UpdateSimple后面的内容都先放到一个slice里，是不是就可以了？

**Comment by whit15** [comment]
> @whit15 比如你把 UpdateSimple后面的内容都先放到一个slice里，是不是就可以了？

果然，是我大意了，万分感谢！

**Comment by kuangshp** [comment]
大佬贴代码出来看看

**Comment by whit15** [comment]
> 大佬贴代码出来看看

非大佬，可作参考
`
updateList := []field.AssignExpr{
    dao.TblUser.Version.Add(1),
    dao.TblUser.UpdateTime.Value(time.Now())
}

if newYear {
    updateList = append(updateList, dao.TblUser.Age.Add(1))
}

updateResult, err := dao.TblUser.
	Where(
		dao.TblUser.ID.Eq(user.ID),
		dao.TblUser.Version.Eq(user.Version),
	).
	UpdateSimple(
		updateList...,
	)
if err != nil {
	return err
}

if updateResult.RowsAffected <= 0 {
	return errors.New(errcode.UpdateError(s.ServiceName).Msg)
}
`
