### ISSUE TITLE
使用gen生成Sqlite引擎的model时字段丢失了index tag

### ISSUE THREAD

**Issue by Michael-Min** [go-gorm/gen#1105]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

1.数据库引擎：sqlite
2.gorm-gen读取sqlite数据源生成代码
3.生成的model中，字段缺失index tag，对比了mysql（ok）。

**Comment by qqxhb** [comment]
sqlite升级到最新的看看吧，老版本driver可能没有实现
