### ISSUE TITLE
The return value Count of the FindByPage function is always 0.

### ISSUE THREAD

**Issue by short-sighted** [go-gorm/gen#1116]
## Your Question

My English is not good, so please forgive me if there are any mistakes in my expression.

### Environment:
- GORM version: v1.25.9
- Gen version: v0.3.25
- go-mssqldb version: v1.6.0

The `findbypage` function generated by GORM returns a count of 0.
I suspect the issue lies in the SQL generated by Gen when calling `*.Offset(-1).Limit(-1).Count()`.
The generated SQL orders by the primary key column, causing an error due to the primary key column not being included in any aggregation function or Group clause.
The generated SQL looks like this: `select count(*) from "user" order by "id"`.
Also I noticed that the generated similar function ScanByPage uses *.Count() directly to return the quantity.

## Expected answer

Since my current environment only supports SQL Server, I found that temporarily replacing `*.Offset(-1).Limit(-1).Count()` with `*.Count()` resolves the issue. 
However, I am still interested in understanding why the original SQL is generated and how to address it properly.

**Comment by qqxhb** [comment]
@\https://gorm.io/docs/query.html#Limit-amp-Offset

**Comment by short-sighted** [comment]
In gorm-gen FindByPage template function, the generated SQL for the Count operation includes an ORDER BY clause. This results in a database error when used with SELECT COUNT(*) because the primary key is not aggregated with GROUP BY. I have a solution that I hope will be helpful.

``` go
func (dialecter SQLServerDialector) Initialize(db *gorm.DB) error {
	err := dialecter.Dialector.Initialize(db)
	if err != nil {
		return err
	}

	db.ClauseBuilders["LIMIT"] = func(c clause.Clause, builder clause.Builder) {
		if limit, ok := c.Expression.(clause.Limit); ok {
			if stmt, ok := builder.(*gorm.Statement); ok {
				countClause := false
				if selectClause, ok := stmt.Clauses["SELECT"]; ok {
					if expr, ok := selectClause.Expression.(clause.Expr); ok {
						countClause = strings.Contains(strings.ToLower(expr.SQL), "count")
					}
				}
				if _, ok := stmt.Clauses["ORDER BY"]; !ok {
					if !countClause {
						if stmt.Schema != nil && stmt.Schema.PrioritizedPrimaryField != nil {
							builder.WriteString("ORDER BY ")
							builder.WriteQuoted(stmt.Schema.PrioritizedPrimaryField.DBName)
							builder.WriteByte(' ')
						} else {
							builder.WriteString("ORDER BY (SELECT NULL) ")
						}
					} else {
						limit.Offset = 0
						limit.Limit = nil
					}
				}
			}

			if limit.Offset > 0 {
				builder.WriteString("OFFSET ")
				builder.WriteString(strconv.Itoa(limit.Offset))
				builder.WriteString(" ROWS")
			}

			if limit.Limit != nil && *limit.Limit >= 0 {
				if limit.Offset == 0 {
					builder.WriteString("OFFSET 0 ROW")
				}
				builder.WriteString(" FETCH NEXT ")
				builder.WriteString(strconv.Itoa(*limit.Limit))
				builder.WriteString(" ROWS ONLY")
			}
		}
	}

	return nil
}


db, err := gorm.Open(SQLServerDialector{Dialector: sqlserver.Dialector{
		Config: &sqlserver.Config{
			DSN: dsn,
		},
	}}, &gorm.Config{
		Logger: newLogger,
	})
	if err != nil {
		panic(fmt.Errorf("connect db fail: %w", err))
	}
```
