### ISSUE TITLE
gentools install broke yesterday  - go install gorm.io/gen/tools/gentool@latest fails

### ISSUE THREAD

**Issue by rabarar** [go-gorm/gen#1125]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

**Comment by tr1v3r** [comment]
Describe the error?

**Comment by tr1v3r** [comment]
Okay, thanks for the report. I will fix it ASAP

**Comment by rabarar** [comment]
Thank you!While I have you, any chance we can fix the mapping of Postgres primary key SERIAL columns in the generation? I use a post-processing sed script to clean up the erroneous golang code generation when that keyword is affixed to a table column.On Apr 11, 2024, at 11:52 AM, True R1v3r ***@***.***> wrote:﻿
Okay, thanks for the report. I will fix it ASAP

**Comment by tr1v3r** [comment]
Of course, but that's another request, you can raise another issue.

**Comment by rabarar** [comment]
Indeed… I’ll add it knowing you t open to looking at it!On Apr 11, 2024, at 12:11 PM, True R1v3r ***@***.***> wrote:﻿
Of course, but that's another request, you can raise another issue.

**Comment by tr1v3r** [comment]
> https://github.com/go-gorm/gen/releases/tag/tools%2Fgentool%2Fv0.0.1

I've added independent tag for the gentool. According to the information provided at [https://golang.org/ref/mod#vcs-version](https://golang.org/ref/mod#vcs-version), build tag in this way should allow for the direct retrieval of the corresponding version of the code using `go install gorm.io/gen/tools/gentool@v0.0.1`. However, it seems not to have taken effect. I will continue to follow up on this issue.

**Comment by tr1v3r** [comment]
I've pinpointed the cause, it's the domain not updating its routing information causing a 404 when requesting the URL https://gorm.io/gen/tools/gentool?go-get=1

**Comment by tr1v3r** [comment]
It's working now.

**Comment by rabarar** [comment]
Thanks was it a GitHub tag issue?On Apr 13, 2024, at 12:36 PM, True R1v3r ***@***.***> wrote:﻿
It's working now.

**Comment by tr1v3r** [comment]
> Thanks was it a GitHub tag issue?On Apr 13, 2024, at 12:36 PM, True R1v3r ***@***.***> wrote:﻿ It's working now. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

not exactly the tag, it's the https://gorm.io/gen/tools/gentool?go-get=1 meta tags value does not conform to the sub-module markup specification.
