### ISSUE TITLE
在使用 GenerateModel 时，总是将字段中的 ssh 转换为 SSH，想要转换为 Ssh

### ISSUE THREAD

**Issue by rea1shane** [go-gorm/gen#1126]
使用 `gen.FieldRename` 也不能将 ssh 变为 Ssh：

```go
g.GenerateModel(
	"test",
	gen.FieldRename("ssh", "Ssh"),
)
```

**Comment by rea1shane** [comment]
How to disable `commonInitialisms`?

**Comment by qqxhb** [comment]
这个只是命名规范问题，ssh应该就是SSH才对？
@rea1shane

**Comment by rea1shane** [comment]
> 这个只是命名规范问题，ssh应该就是SSH才对？ @rea1shane

这导致了我代码的一些问题，我觉得不应该强制转换这些特殊名词

**Comment by qqxhb** [comment]
@rea1shane 你可以看下，这个算规范哈
https://github.com/golang/lint/blob/master/lint.go#L770

如果你实在要改 也是可以的
参考下这个 https://gorm.io/docs/gorm_config.html#NamingStrategy
