### ISSUE TITLE
Gentool generates invalid tags on Postgres SERIAL PRIMARY KEY column

### ISSUE THREAD

**Issue by rabarar** [go-gorm/gen#1128]
## GORM Playground Link

generated code from gentool utility

AppID is defined as a Serial primary key in the database…

// App mapped from table <Apps>
type App struct {
	AppID       int32  `gorm:"column:AppID;type:integer;primaryKey;default:nextval('"Apps_AppID_seq"" json:"AppID"`
	Port        int32  `gorm:"column:Port;type:integer" json:"Port"`
	AppName     string `gorm:"column:AppName;type:character varying(255);not null" json:"AppName"`
	Description string `gorm:"column:Description;type:text" json:"Description"`
}

https://github.com/go-gorm/playground/pull/1

**Comment by qqxhb** [comment]
https://gorm.io/gen/database_to_structs.html#Field-Options
```go
 gen.FieldGORMTag("extra", func(tag field.GormTag) field.GormTag {
   return tag.Set("default", "nextval(xx")
})
```

**Comment by ferluk** [comment]
how to get table name ?

```
gen.FieldGORMTag("extra", func(tag field.GormTag) field.GormTag {

  tableName := "User" // how to get tablename ??

   return tag.Set("default", "nextval('"+tableName+"_AppID_seq')")
})
```
