### ISSUE TITLE
Query generation with existing database table named "fields"

### ISSUE THREAD

**Issue by pbarnum** [go-gorm/gen#1129]
## Your Question

I wanted to generate the query files for my existing database structure but found that when it generated the query file for my database table named "fields", the `field` import collided with the generated struct name `field`. What is the proper way to go about this?

## The document you expected this should be explained

If this is meant to be fixed via a configuration option, then the documentation to explain this would be [here](https://gorm.io/gen/gen_tool.html) within "Usage". Otherwise, the imports should be aliased to avoid conflicts.

## Expected answer

The imports should be aliased to avoid conflicts.

**Comment by qqxhb** [comment]
https://gorm.io/gen/database_to_structs.html#Global-Generating-Options
