### ISSUE TITLE
gorm Gen Tool int32

### ISSUE THREAD

**Issue by WaterCool8258** [go-gorm/gen#1134]
## Your Question
想请问下gorm 的 Gen Tool使用配置文件生成模型的时候，可以像代码那样指定INTEGER为int64吗？我使用的数据库是sqlite，目前会把INTEGER类型定义为int32，但是数据库存储值范围已经大于int32了

**Comment by zplzpl** [comment]
`
	g := gen.NewGenerator(gen.Config{
		OutPath:      "./dal",
		ModelPkgPath: "./models",
		Mode:         gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface, // generate mode

	})

	g.WithOpts(gen.FieldModify(func(field gen.Field) gen.Field {
		if field.Type == "int32" {
			field.Type = "int64"
		}
		return field
	}))
`

maybe like that.

**Comment by qqxhb** [comment]
或者是单个字段也可以用gen.FieldTyoe
某个类型的字段 可以用datamapping
