### ISSUE TITLE
Same table names cannot be generated across different schemes

### ISSUE THREAD

**Issue by auxpd** [go-gorm/gen#1135]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

If there is a table "A" in different schemes, the second structure file will not be generated because the generated file name is the same, resulting in the structure of the specific object does not exist

**Comment by auxpd** [comment]
Can you make QueryStructMeta's fileName a more unique value? Including my gorm multi-database query, there are often tables with the same name, this scenario can not generate files correctly.

**Comment by Rellopn** [comment]
same question

**Comment by qqxhb** [comment]
There are only two scenarios where the table name is the same
The first is when both the table name and structure are the same, and only one is generated
The second type is different in table structure, should it be generated in two paths
