### ISSUE TITLE
如何不重复生成query/gen.go

### ISSUE THREAD

**Issue by RockyS7** [go-gorm/gen#1137]
如果想每次只生成指定表的model和query，又不想覆盖之前的gen.go内容，只需基于之前的gen.go追加或修改，需要修改什么配置

重新生成gen.go，会造成之前在gen.go引入的query结构体丢失，有什么补救的方法，或者开发规范可以避免这个问题

**Comment by Illidanfan0414** [comment]
same question

**Comment by qqxhb** [comment]
生成的脚本跟着代码提交不要删除，每次新增表就行
每次执行都是全量的就好了。

比如
第一次
`	g.ApplyBasic(model.User{}, g.GenerateModel("company"))
`
第二次
`g.ApplyBasic(model.User{}, g.GenerateModel("company"), g.GenerateModelAs("people", "Person", gen.FieldIgnore("address"))）`
