### ISSUE TITLE
If there is a unique index in the generated unit test, an error will be reported.

### ISSUE THREAD

**Issue by eleztian** [go-gorm/gen#1148]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

If there is a unique index in the generated unit test, an error will be reported.

```go
func Test_tblUserQuery(t *testing.T) {
.....
	err = _do.CreateInBatches([]*model.TblUser{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <tbl_user> fail:", err)
	}
}
```

```shell
tbl_user.gen_test.go:57: create item in table <tbl_user> fail: UNIQUE constraint failed: tbl_user.ns, tbl_user.identity_id, tbl_user.name
```

**Comment by EZ4BRUCE** [comment]
same problem

**Comment by qqxhb** [comment]
The generated unit test is just a template and can be modified by yourself. Just don't generate a unit test next time it is generated.
