### ISSUE TITLE
How to customize the field names of the generated model?

### ISSUE THREAD

**Issue by szerr** [go-gorm/gen#1150]
Recently I want to switch to gen to generate models. "id" and "*_id" in the table are all converted to "ID", and the existing field in the project is "Id". I want to reduce the impact on the project. Is it possible to use a callback function to return a custom name?

**Comment by qqxhb** [comment]
You can try to modify the NamingStrategy.
 https://gorm.io/docs/gorm_config.html#NamingStrategy
 `NameReplacer: strings.NewReplacer("ID", "Id")`
