### ISSUE TITLE
Why smallint is mapped to int32 by default?

### ISSUE THREAD

**Issue by eeczw** [go-gorm/gen#1152]
https://github.com/go-gorm/gen/blob/536bc2692a89f03301f8c87975f7d657f96a4a6f/internal/model/base.go#L117

I searched in [Postgres docs](https://www.postgresql.org/docs/current/datatype-numeric.html) and [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html) and found out that both of their smallint types hava a storage size of 2 bytes. So I'm wondering why smallint is currently mapped to int32 by default. Will int16 be a better choice?

**Comment by qqxhb** [comment]
The default type is determined based on business usage; generally, int16 is rarely used, and more int32 is used.
If it does not meet your needs, you can configure it through Data Mapping.
[https://gorm.io/gen/database_to_structs.html#Data-Mapping](https://gorm.io/gen/database_to_structs.html#Data-Mapping)
