### ISSUE TITLE
指定表名后生成的sql无法执行

### ISSUE THREAD

**Issue by heykb** [go-gorm/gen#1155]
`query.Segment.Table(route.SegmentTableName()).
			Unscoped().
			WithContext(ctx).Where(query.Segment.ChatID.Eq(input.ChatID)).Where(query.Segment.ID.Gte(segment.ID)).Delete();`

![1717758033332_6B655E89-394B-4b24-9F7A-9206B11FE79D](https://github.com/go-gorm/gen/assets/38965571/82618d31-93dd-4f8b-a992-fbd3c2f35304)
field的前缀还是旧的

**Comment by qqxhb** [comment]
```go
seg := query.Segment.Table(route.SegmentTableName())
seg.WithContext(ctx).Where(seg.ChatID.Eq(input.ChatID)).Where(seg.ID.Gte(segment.ID)).Unscoped().Delete();
```
