### ISSUE TITLE
Can't generate association tags for the dao through the gentool.

### ISSUE THREAD

**Issue by TsubasaEX** [go-gorm/gen#1157]
## Description

I found there are use cases for the associations between two or more models, but I can get those associations and the association tags for the generated dao through the gentool.
https://gorm.io/gen/associations.html

![image](https://github.com/go-gorm/gen/assets/34151841/ad4f30f2-a313-4ed2-b6e6-a869a22a8f17)

Seems like there's no option to get the association tags.
https://gorm.io/gen/gen_tool.html

Here's one of the foreign keys in my generated dao model to another dao model.
![image](https://github.com/go-gorm/gen/assets/34151841/c6bb915d-71e7-45b1-bc02-dff25de4f262)

Do I miss something here? Could you provide any suggestion?

Thanks in advance.

**Comment by qqxhb** [comment]
Gentool provides a relatively simple usage, not flexible enough.
Code generation is recommended.

https://gorm.io/gen/database_to_structs.html
