### ISSUE TITLE
生成代码时，query和model写入的文件名相同

### ISSUE THREAD

**Issue by dawnmn** [go-gorm/gen#1185]
generator.go

在不配置ModelPkgPath值时，generateSingleQueryFile与generateModelFile写入了相同的文件
![企业微信截图_17228527392388](https://github.com/user-attachments/assets/9ac82bdb-c43f-4c5d-b4b4-d28368ce088b)
![企业微信截图_17228527669058](https://github.com/user-attachments/assets/5a96961a-6855-4ed0-b954-7885577ab08a)

**Comment by qqxhb** [comment]
@dawnmn 应文件名是相同的，路径不同，model，默认是写到model路径写的
```go
	g := bytedgen.NewGenerator(gen.Config{
		OutPath: "../../dal/query",
		Mode:    gen.WithDefaultQuery,
	})
```
 比如这个，query生成到dal/query路径下，model生成的是dal/model路径
