### ISSUE TITLE
如何生成sql.NullTime这样的字段

### ISSUE THREAD

**Issue by mengyan258** [go-gorm/gen#1186]
在使用gen对代码进行生成时，如何对日期字段生成sql.NullTime，我试过修改Data Mapping，但会连同create_time这样的字段都进行了修改！
![微信截图_20240809135659](https://github.com/user-attachments/assets/4ba82042-facc-4453-b225-8fdd706cc231)

**Comment by qqxhb** [comment]
单个字段可以用，gen.FieldType

**Comment by qqxhb** [comment]
datamapping 是对【某个类型】的字段 
FieldType 针对的是 特定字段
