### ISSUE TITLE
MySQL表结构为TINYINT的field，自动生成的是int32，而不是int8

### ISSUE THREAD

**Issue by zaaztt** [go-gorm/gen#1189]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

table原始表中是tinyint的项目，应该对应go中的int8，但是经过gen生成的全都是int32

**Comment by qqxhb** [comment]
@zaaztt 这个是设计如此哈；业务场景使用更多的就是 int32和int64,所以默认都是生成这两个了

不满足你们诉求的可以通过FIeldType或者是datamapping 配置哈

**Comment by zaaztt** [comment]
> @zaaztt 这个是设计如此哈；业务场景使用更多的就是 int32和int64,所以默认都是生成这两个了
> 
> 不满足你们诉求的可以通过FIeldType或者是datamapping 配置哈

@qqxhb 推荐我直接修改gen生成的struct吗？比如手动把int32改成int8

**Comment by qqxhb** [comment]
> > @zaaztt 这个是设计如此哈；业务场景使用更多的就是 int32和int64,所以默认都是生成这两个了
> > 不满足你们诉求的可以通过FIeldType或者是datamapping 配置哈
> 
> @qqxhb 推荐我直接修改gen生成的struct吗？比如手动把int32改成int8

不推荐哈，因为直接改struct下次生成又被覆盖了
