### ISSUE TITLE
使用数据库文件生成实体类，怎么配置每个表都带上hook

### ISSUE THREAD

**Issue by kuangshp** [go-gorm/gen#1192]
自定义hook，现在我的业务需求是每次做增删改的时候都需要在数据库上记录创建人，更新人，我想到用hook来说，但是使用gen来生成的实体类，希望直接在生成文件的代码中直接配置，自动给所有表都加上hook,

**Comment by qqxhb** [comment]
@kuangshp https://gorm.io/gen/database_to_structs.html#Methods-Template
https://gorm.io/docs/update.html#Update-Hooks

**Comment by kuangshp** [comment]
> @kuangshp https://gorm.io/gen/database_to_structs.html#Methods-Template https://gorm.io/docs/update.html#Update-Hooks
我就是不想给每个表去手动加，想根据配置文件生成数据模型的时候直接生成

**Comment by qqxhb** [comment]
你要布置仔细看下这个文档？ 这个就是配置生成的，不是每个都写一遍

**Comment by kuangshp** [comment]
> > @kuangshp https://gorm.io/gen/database_to_structs.html#Methods-Template https://gorm.io/docs/update.html#Update-Hooks
> > 我就是不想给每个表去手动加，想根据配置文件生成数据模型的时候直接生成

接收不到上下文中的数据
