### ISSUE TITLE
Rows() 方法没有

### ISSUE THREAD

**Issue by shuqingzai** [go-gorm/gen#1228]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

文档 https://gorm.io/zh_CN/gen/query.html#Group-By-amp-Having 可以使用 `Rows()` 迭代结果，可生成的 gen dao 中并没有该方法？

**Comment by qqxhb** [comment]
是不是你的版本不对更新版本看看呢，这个是基础方法,在 Do上

**Comment by shuqingzai** [comment]
> 是不是你的版本不对更新版本看看呢，这个是基础方法,在 Do上

@qqxhb Do 上确实存在 `Rows` 方法，但是如果生成代码使用接口模式，`IxxxDo` 接口不会生成该方法，导致使用时，无法引用
![image](https://github.com/user-attachments/assets/7876117b-2174-4e3b-a974-4bbe3da5aba2)

**Comment by qqxhb** [comment]
@shuqingzai 
#1245
