### ISSUE TITLE
gen  怎么写 RAW SQL

### ISSUE THREAD

**Issue by boringplay** [go-gorm/gen#1240]
## Describe the feature

一些复杂的 SQL，在 Where、GroupBy、Select 场景怎么写RawSQL？

例如 `select YEAR(CAST(release_time as Date)) as year`

**Comment by paradox-lab2** [comment]
调用原生的使用gorm.DB，Select方法可以自定义查询字段内容

```golang
	type Result struct {
		Year      int
		Id        int
		FirstName string
	}
	var result Result
	author.WithContext(ctx).Where(author.ID.Eq(1)).UnderlyingDB().Select(
		[]string{string(
			author.ID.ColumnName()),
			"YEAR(CAST(birth_date as DATE)) as year",
			"first_name",
		}).Debug().Scan(&result)
```
执行的sql: SELECT `id`,YEAR(CAST(birth_date as DATE)) as year,`first_name` FROM `author` WHERE `author`.`id` = 1

参考文档: [选择特定字段](https://gorm.io/zh_CN/docs/query.html#%E9%80%89%E6%8B%A9%E7%89%B9%E5%AE%9A%E5%AD%97%E6%AE%B5)
