### ISSUE TITLE
leftjoin 查询结果 group by 暴露的 bug

### ISSUE THREAD

**Issue by zhangya4548** [go-gorm/gen#142]
leftjoin 查询结果 group by 时候生成的 sql 显示 字段未带表名,导致count时候sql执行报错.

![image](https://user-images.githubusercontent.com/8876518/137129849-74d7a35f-9158-4022-a00a-bfd20cd21679.png)

**Comment by longlihale** [comment]
@zhangya4548  hello, can you provide a demo in https://github.com/go-gorm/playground ？？
