### ISSUE TITLE
如何指定自定义方法只生成在部分model

### ISSUE THREAD

**Issue by szpnygo** [go-gorm/gen#176]
method里的自定义方法并不是适用于所有的model，但是现在好像所有方法里都生成了

**Comment by qqxhb** [comment]
https://github.com/go-gorm/gen#quick-start
    参考Readme 分开写就可以哈
   //不需要DIY method的 model
    g.ApplyBasic(model.User{}, g.GenerateModel("company"), g.GenerateModelAs("people", "Person", gen.FieldIgnore("address")))
    
    // 需要DIY method的model
    g.ApplyInterface(func(method model.Method) {}, model.User{}, g.GenerateModel("company"))

    g.Execute()
