### ISSUE TITLE
传入*gorm_adapter.GormDB无法读取DB生成代码

### ISSUE THREAD

**Issue by dino-ma** [go-gorm/gen#177]
对象有效，可以从DB中获取数据。
但是传入gen后，没办法读取表结构。

//查询返回的数据
orderData.ID: 1384821646614859776

//gen执行的过程
2021/11/03 17:47:50.269758 generator.go:262: got 0 columns from table <orders>
2021/11/03 17:47:50.320858 generator.go:262: got 0 columns from table <orders_medical_advice>
2021/11/03 17:47:50.336705 generator.go:262: generate query file: /Users/mashengjie03/Work/code/heytea/cmd/dal/query/gen.go
2021/11/03 17:47:50.336723 generator.go:262: Generate code done.

wechat 9393103

**Comment by qqxhb** [comment]
config 设置下获取dbname方法
// WithDbNameOpts set get database name function

**Comment by waltcow** [comment]
// db, _ := gorm.Open(mysql.Open("root:@(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local"))

参考readme的配置有问题，翻到这里才解决
