### ISSUE TITLE
try clickhouse database generate has panic

### ISSUE THREAD

**Issue by leeyf888** [go-gorm/gen#191]
panic: generate struct fail

goroutine 1 [running]:
gorm.io/gen.(*Generator).GenerateModelAs(0xc000166f00, {0xbf0003, 0x31}, {0xc00032b810, 0x0}, {0x0, 0x0, 0xc000322150})
        /home/xxx/xxx/go/pkg/mod/gorm.io/gen@v0.1.16/generator.go:166 +0x2cd
gorm.io/gen.(*Generator).GenerateModel(0xc000166f00, {0xbf0003, 0x12}, {0x0, 0x0, 0x0})
        /home/xxx/xxx/go/pkg/mod/gorm.io/gen@v0.1.16/generator.go:150 +0x73
main.main()
        /home/xxx/xxx/GolandProjects/sdk-server/cmd/generate/generate.go:19 +0xc5

Does it support clickhouse, i used driver that gorm/clickhouse.

**Comment by riverchu** [comment]
coming soon

**Comment by zachspar** [comment]
> coming soon

Any updates on this?

**Comment by riverchu** [comment]
emmm, no, waiting for jinzhu's free

**Comment by zachspar** [comment]
Sorry, I meant to ask about the update on issue #271
