### ISSUE TITLE
generated Do.FindInBatches func parameter issue

### ISSUE THREAD

**Issue by francistm** [go-gorm/gen#194]
In the method `func (t tDo) FindInBatches)` generated for each of models by the template below:

https://github.com/go-gorm/gen/blob/d2560a66f483a19705c1f12c66f14dc654c127d8/internal/template/method.go#L154-L156

Could the 1st parameter `result` need to be an pointer to slice? Otherwise the caller can't read the result of each batch.

**Comment by riverchu** [comment]
yeah, i will fix it ASAP
