### ISSUE TITLE
DIY method模板的更多语法支持

### ISSUE THREAD

**Issue by Nomango** [go-gorm/gen#207]
## Describe the feature

希望在DIY method中支持更多语法，例如数组遍历：

```golang
type Method interface {
    /* select * from @@table
      {{where}}
          {{ range $idx, $elem := @names }}
              {{ if $idx }} or {{ end }} name={{ $elem }}
          {{ end }}
      {{end}}
    */
    FindByNames(names []string) ([]gen.T, error)
}
```

如果能像go template一样注册自定义函数就更好了

## Motivation

DIY method编写raw sql能力受限

**Comment by Umenezumi** [comment]
```go
{{if len(appId) > 0}}
    ad.app_id IN @appId
{{end}}

```


------

我试了下 这种写法也不支持

` err:unknow parameter: len(appId)`

**Comment by idersec** [comment]
暂时if，len可以单独传个参数进去，再进行比较，支持数组与nil比较：appId==nil.看看能不能满足。

**Comment by idersec** [comment]
暂时if不支持函数，len可以单独传个参数进去，再进行比较，支持数组与nil比较：appId==nil.看看能不能满足。

**Comment by Dawinia** [comment]
感觉range的用处也不是很多，示例可以改成name in @names，会更方便吧。

**Comment by idersec** [comment]
> 觉得范围的用处也不是很多，可以在@NAMEs 中改成名字，会更方便吧。

会支持到for循环，为格式统一，还是go语言的语法，{{for _,name:=range names}}现在在测试中了，很快会上线发布

**Comment by Dawinia** [comment]
> 会支持到for循环，为格式统一，还是go语言的语法，{{for _,name:=range names}}现在在测试中了，很快会上线发布

这个我也实现了，但是实现过程中感觉应用场景不明显，所以没提pr

**Comment by idersec** [comment]
@Nomango @Dawinia  v0.1.27 已发布，已经支持for range。赶紧试试吧！
