### ISSUE TITLE
Joins语句中支持select

### ISSUE THREAD

**Issue by Nomango** [go-gorm/gen#208]
## Describe the feature

希望在关联查询时，可以指定select字段，例如有下面两个表：

```golang
type A struct {
	gorm.Model
	B *B
	... // other fields
}

type B struct {
	gorm.Model
	AID uint
	Config string
	... // other fields
}
```

关联查询b表：

```golang
ax := a.WithContext(ctx).Joins(a.B)
ax.Where(a.ID.Eq(1)).Take()
```

当b表字段较多时，希望select b表的指定字段，例如：

```golang
ax := a.WithContext(ctx).Joins(a.B.Select(b.Config))
ax.Where(a.ID.Eq(1)).Take()
```

## Motivation

不支持这样的写法：

```golang
ax := a.WithContext(ctx).Select(a.ALL, b.Config).Joins(a.B)
ax.Where(a.ID.Eq(1)).Take()
```

**Comment by qqxhb** [comment]
单纯的join是支持select的 [https://github.com/go-gorm/gen#joins](https://github.com/go-gorm/gen#joins)
例：u.WithContext(ctx).Select(u.Name, e.Email).LeftJoin(e, e.UserID.EqCol(u.ID)).Scan(&results)
你是希望preload的方式，支持selectB表吗？

**Comment by Nomango** [comment]
@qqxhb 是的，不想用LeftJoin+Scan方式实现的原因一个是结构体里已经定义了AB表的关联，还有就是Scan要求声明一个新的结构体，不知道最佳实现应该把这个结构体放到什么地方起什么名字，比如可能写起来长下面这样：

```golang
// biz.go
type UserWithEmail struct {
    models.User
    Email string
}

var ues []*UserWithEmail
u.WithContext(ctx).Select(u.ALL, e.Email).LeftJoin(e, e.UserID.EqCol(u.ID)).Scan(&ues)

// main.go
var ues []*biz.UserWithEmail // 用了一个biz里定义的结构体，感觉不太对劲
```

**Comment by qqxhb** [comment]
@Nomango 了解。所以我理解这个问题不是要join支持select，而是希望preload支持select对吧？

**Comment by Nomango** [comment]
@qqxhb Joins语句也是需要的，有Joins的写法，和Preload类似

**Comment by qqxhb** [comment]
@Nomango join现在支持select的哦

**Comment by Nomango** [comment]
@qqxhb join和joins不太一样，joins和preload的参数一样，虽然不是很理解joins的s的含义哈哈

**Comment by riverchu** [comment]
Joins是和`GORM`对齐的，可以参考文档：https://gorm.io/docs/query.html#Joins-Preloading

**Comment by riverchu** [comment]
> @qqxhb 是的，不想用LeftJoin+Scan方式实现的原因一个是结构体里已经定义了AB表的关联，还有就是Scan要求声明一个新的结构体，不知道最佳实践应该把这个结构体放到什么地方起什么名字，比如可能写起来长下面这样：
> 
> ```go
> // biz.go
> type UserWithEmail struct {
>     models.User
>     Email string
> }
> 
> var ues []*UserWithEmail
> u.WithContext(ctx).Select(u.ALL, e.Email).LeftJoin(e, e.UserID.EqCol(u.ID)).Scan(&ues)
> 
> // main.go
> var ues []*biz.UserWithEmail // 用了一个biz里定义的结构体，感觉不太对劲
> ```

这个如果不是很多地方要用的话可以做个匿名结构体定义在函数里？

**Comment by Nomango** [comment]
@riverchu 我遇到的场景是要带着另一个表的其中一个字段用到各个地方 /泣不成声

**Comment by riverchu** [comment]
目前还是不支持这种功能的，主要是gorm上就没有实现这种能力，可以去gorm那边提个issue推进一下
