### ISSUE TITLE
How to use aggregation function with condition?

### ISSUE THREAD

**Issue by Umenezumi** [go-gorm/gen#209]
## Your Question

database:Mysql

i want gen SQL like this:

```sql
SELECT
    IFNULL(AVG(IF(ad_d.fix_cost_time > 0, ad_d.duration, NULL)), 0)                AS avg_duration,
    IFNULL(AVG(IF(ad_d.fix_cost_time > 0, ad_d.fix_cost_time, NULL)), 0)           AS avg_fix_cost_time
FROM xxxx
Where 
  -- omit
```

i write code like:

```GO
query.Q.XXXX.WithContext(ctx).Select(XXX.FixCostTime.Avg())......
```

How do I pass conditions to aggregation function？

**Comment by idersec** [comment]
For complex SQL, we recommend using DIY SQL template.  https://github.com/go-gorm/gen#diy-method

**Comment by Umenezumi** [comment]
> For complex SQL, we recommend using DIY SQL template. https://github.com/go-gorm/gen#diy-method

thx,You answered my question

**Comment by randree** [comment]
What about `COALESCE`? In Postgres I can't use `IFNULL`.
