### ISSUE TITLE
Generate all Model （生成所有table对应的model ）

### ISSUE THREAD

**Issue by eddie-fangv** [go-gorm/gen#218]
希望有一个能生成所有table对应的model ，谢谢 
   db, _ := gorm.Open(mysql.Open("root:@(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local"))
    g.UseDB(db)
    g.ApplyBasic(生成所有table对应的model)

**Comment by dino-ma** [comment]
这个目前已经支持了，依赖GORM几个PR。后续就会提上来。 @eddie-fangv

**Comment by dino-ma** [comment]
同 https://github.com/go-gorm/gen/issues/202 会一起提上来做发布 @eddie-fangv

**Comment by eddie-fangv** [comment]
好的，感谢 @dino-ma

**Comment by dino-ma** [comment]
这个问题已经处理了。可以看https://github.com/go-gorm/gen/blob/master/tools/gentool/gentool.go#L50

**Comment by riverchu** [comment]
等我在config里加上相关配置就close这个issue，还是给个选项比较方便

**Comment by riverchu** [comment]
已更新
```go
 g.ApplyBasic(g.GenerateAllTable()...)
```
