### ISSUE TITLE
model生成时，int类型问题

### ISSUE THREAD

**Issue by eddie-fangv** [go-gorm/gen#219]
**### int类型设置问题,长度不够用**

**数据库设置的类型为int, 长度为11
生成的model类型为int32**

![Snipaste_2021-11-12_18-59-34](https://user-images.githubusercontent.com/34231359/141456865-61928ab8-26a0-45b2-ac7d-e8edf8fbad72.png)

**另外，发现一个单词的bug**
![image](https://user-images.githubusercontent.com/34231359/141457044-f8d1fd51-76b4-48a0-ac23-679af64f685e.png)

**Comment by riverchu** [comment]
这个问题可以和 #190 一起解决
