### ISSUE TITLE
different than gorm?

### ISSUE THREAD

**Issue by jinfagang** [go-gorm/gen#220]
what's the difference between gorm and gen? what's their usage differences?

**Comment by qqxhb** [comment]
A safer orm base on GORM, aims to be developer friendly.
1. Auto migration from database to code.
2. Fully compatible with Gorm: Gen's API is basically the same as Gorm's
3. Developer friendly: more efficient and convenient operation
4. More secure: prevent SQL injection by limiting input parameter types and security verification

**Comment by jincheng9** [comment]
@qqxhb why not just implement these features on gorm itself, instead building a new module but still relying on gorm.

**Comment by jinfagang** [comment]
@jincheng9 I have same concern

**Comment by jincheng9** [comment]
@jinfagang I think it's kind of a tradeoff between jinzhu and bytedance, so that jinzhu don't need to rely on bytedance and can control the gorm's developement.

**Comment by riverchu** [comment]
> @jinfagang I think it's kind of a tradeoff between jinzhu and bytedance, so that jinzhu don't need to rely on bytedance and can control the gorm's developement.

please don't overthink it. Bytedance never thought about getting involved in the development process of `GORM`

**Comment by riverchu** [comment]
> @qqxhb why not just implement these features on gorm itself, instead building a new module but still relying on gorm.

Actually, these features almost all based on code generation, and it means if we implement these in GORM, it will greatly increase the complexity of engineering use. We want to maximize the simplicity of GORM. So build another project based on GORM is a better choice.

**Comment by jincheng9** [comment]
@riverchu @qqxhb thanks for the clarification.

**Comment by riverchu** [comment]
@jinfagang Any other questions?
