### ISSUE TITLE
JSON tag naming style can be configurable 

### ISSUE THREAD

**Issue by waltcow** [go-gorm/gen#234]
## Describe the feature

JSON tag naming style  can be configurable,

various options like (e.g. [snake case](https://en.wikipedia.org/wiki/Snake_case) or [camel case](https://en.wikipedia.org/wiki/CamelCase)), by default use columnName

**Comment by riverchu** [comment]
There are two way to diy json tag name strategy,

global:
```go
g.WithJSONTagNameStrategy(func(col string) (tag string) { return col + "_" })
```

scope:
```go
g.ApplyBasic(g.GenerateModel("table", gen.FieldJSONTagWithNS(func(col string) (tag string) { return col+"_" })))
```
