### ISSUE TITLE
关于排序的疑问

### ISSUE THREAD

**Issue by Umenezumi** [go-gorm/gen#237]
生成的 `GetFieldByName()`方法返回的对象为`field.Expr`

无法调用

```go
func (e expr) Desc() Expr {
	return e.setE(clause.Expr{SQL: "? DESC", Vars: []interface{}{e.RawExpr()}})
}
```
导致前端发送的对某个字段的`Desc`排序需求我无法实现，因为获取不到具体的 field.type。

**Comment by Umenezumi** [comment]
> 获取之后做一下类型断言？

谢谢，看到了 field.Field 的这个 struct。

**Comment by Umenezumi** [comment]
很抱歉我又打开了这个 issue。

当我仅仅对获取结果做`field.Field`类型断言是匹配不上的

```
if f, ok := columnMap[condition.Key]; ok {
    
    column := f.(field.Field)
    xxxx = xxxx.Order(condition.Build(f))
}

func (s *SortCondition) Build(field field.Field) field.Expr {
	if s.Opt == DESC {
		return field.Desc()
	}
	return field
}```

因为实际类型是 `filed.Int64`、`field.Float32` 等

难道需要我做全部类型的 switch 判断吗？

```
switch f.(type){
  case xxxx
  case xxxx
}
```

额，我 golang 使用的很少，掌握的不太好，望知道 ，thx



**Comment by weizhengde** [comment]
if orderExpr, ok := bf.GetFieldByName(req.Sorter.Field); ok {
	switch o := orderExpr.(type) {
	case interface{ Desc() field.Expr }:
		orderExpr = o.Desc()
	}
	do = do.Order(orderExpr).Order(bf.ID)
}
用接口**interface{ Desc() field.Expr }**做类型断言，然后通过**o.Desc()**转换，亲测可行

**Comment by riverchu** [comment]
每个数据类型都实现了`Desc()`方法，所以也可以简写
```go
if orderExpr, ok := bf.GetFieldByName(req.Sorter.Field); ok {
    do = do.Order(orderExpr.(interface{ Desc() field.Expr }).Desc())
}
```

**Comment by Umenezumi** [comment]
> 每个数据类型都实现了`Desc()`方法，所以也可以简写
> 
> ```go
> if orderExpr, ok := bf.GetFieldByName(req.Sorter.Field); ok {
>     do = do.Order(orderExpr.(interface{ Desc() field.Expr }).Desc())
> }
> ```

原来是这样，多谢回复

**Comment by Umenezumi** [comment]
> ```go
> if orderExpr, ok := bf.GetFieldByName(req.Sorter.Field); ok {
>     switch o := orderExpr.(type) {
>     case interface{ Desc() field.Expr }:
>         orderExpr = o.Desc()
>     }
>     do = do.Order(orderExpr).Order(bf.ID)
> }
> ```
> 
> 用接口`interface{ Desc() field.Expr }`做类型断言，然后通过`o.Desc()`转换，亲测可行

thx，确实解决了我的需求
