### ISSUE TITLE
`gentool` accept config file

### ISSUE THREAD

**Issue by riverchu** [go-gorm/gen#252]
## Describe the feature

Accept config file and parse config from file. And accept command line parameters in the meanwhile. 
Command line has higher priority.

```bash
gentool -c ./conf/gen.yml

# specify dsn instead of using configuration in file
gentool -c ./conf/gen.yml -dsn <dsn>
```

**Comment by riverchu** [comment]
@dino-ma

**Comment by dino-ma** [comment]
You can just assign it to me

**Comment by dino-ma** [comment]
You can close it.
