### ISSUE TITLE
是否可以仅生成 query

### ISSUE THREAD

**Issue by twotigers93** [go-gorm/gen#259]
## Your Question
非常赞的的发现已经加上 example 了, 同时使用了一下,  发现 model 也是一并生成的, 理解这个对于已经存在的使用 gorm 的项目不是很友好? 因为会重新生成 model, 所以想问下是否可以仅生成 query

- 这里还有个问题, 在现有的项目中我们使用gorm model 有点类似 Django, model 是分散在不同的 app 内的, 如果可以仅生成query 的话, 理解这个问题也会能得到解决

**Comment by qqxhb** [comment]
g.ApplyBasic(),可以直接传已经有的model，这种不会重新生成model，比如
g.ApplyBasic(model.User,model.Role)

**Comment by riverchu** [comment]
可以直接复用原来gorm工程里写好的数据库表对应结构体，不是一定要从数据库生成对应结构体的

**Comment by riverchu** [comment]
有空会加一个不使用同步数据库，直接复用已有结构体的example的
