### ISSUE TITLE
能否支持下字段属性的枚举生成

### ISSUE THREAD

**Issue by waltcow** [go-gorm/gen#262]
在编码过程中，经常会遇到用某个数值来表示某种状态、类型或者阶段的情况，比如有这样一个枚举：

```java
public enum ComputerState {
    OPEN(10),         //开启
    CLOSE(11),         //关闭
    OFF_LINE(12),     //离线
    FAULT(200),     //故障
    UNKNOWN(255);     //未知

    private int code;
    ComputerState(int code) { this.code = code; }
}

```
通常我们希望将表示状态的数值存入数据库，即ComputerState.OPEN存入数据库取值为10。

能否通过field comment的中备注，来生成对应枚举值

比如可以约定注释检查规则的正则表达式如下

```js
REMARKS_PATTERN = ".*\\s*\\[\\s*(\\w+\\s*\\(\\s*[\\u4e00-\\u9fa5_\\-a-zA-Z0-9]+\\s*\\)\\s*:\\s*[\\u4e00-\\u9fa5_\\-a-zA-Z0-9]+\\s*\\,?\\s*)+\\s*\\]\\s*.*";

```

```sql

CREATE TABLE `tb` (
  `type` smallint(3) COMMENT '注释[success(0):成功, fail(1):失败]',                       
);
```

提取出字段属性相应的枚举

```golang
type Type int

const (
        Success  Type = 0 //成功
        Fail Type = 1 //失败
)


```

**Comment by riverchu** [comment]
如果只是对数字类型的枚举可以通过在生成的时候加入`gen.FieldType("type", "basic.Type")`方式直接将对应字段指定为相应类型就可以了 https://github.com/go-gorm/gen#generate-model

**Comment by riverchu** [comment]
如果是字符串或者其他的枚举类型就实现[ScanValuer](https://github.com/go-gorm/gen/blob/master/field/field.go#L9)接口就可以了

**Comment by waltcow** [comment]
> 如果只是对数字类型的枚举可以通过在生成的时候加入`gen.FieldType("type", "basic.Type")`方式直接将对应字段指定为相应类型就可以了 https://github.com/go-gorm/gen#generate-model

如果这样的话，“basic.Type" 的 import 路径如何适配，这类constant文件不在一个package里

**Comment by riverchu** [comment]
可以直接用`constant.Type`这种形势，生成代码的过程中有一步是使用goimports修正格式和引用路径，可以试一下

**Comment by waltcow** [comment]
> 可以直接用`constant.Type`这种形势，生成代码的过程中有一步是使用goimports修正格式和引用路径，可以试一下

https://github.com/go-gorm/gen/blob/d69c6d66a8abff47f6d36d80ae19ec70e1337a9f/generator.go#L479

https://github.com/go-gorm/gen/blob/d69c6d66a8abff47f6d36d80ae19ec70e1337a9f/internal/template/model.go#L7

这里model的模版都是写死了的

但生成出来的model  头竟然是这样的，不知道是哪一步修正依赖的😅

```go

import (
	"encoding/json"
	"time"

	"gorm.io/gorm"
)
```

**Comment by riverchu** [comment]
用 `gen.FieldType("type", "constant.Type")`就可以了

**Comment by waltcow** [comment]
在使用枚举类时， 这个ScanValuer接口，无法兼容 database/sql scanner 接口 

https://husobee.github.io/golang/database/2015/06/12/scanner-valuer.html

![image](https://user-images.githubusercontent.com/3941174/147224565-9e673218-deb1-4246-a351-d64771decfbc.png)

![image](https://user-images.githubusercontent.com/3941174/147224641-3983214e-3644-4a75-ad42-8a49fbbba60d.png)

**Comment by riverchu** [comment]
是因为没有用指针吧？ ScanValuer接口的Scan用的就是database/sql的Scanner方法

**Comment by waltcow** [comment]
> 可以给多点提示吗😭

**Comment by waltcow** [comment]
> 是因为没有用指针吧？ ScanValuer接口的Scan用的就是database/sql的Scanner方法

 可以给多一点提示吗😭

**Comment by waltcow** [comment]
我发现数据库读出来的record里面的值无法映射成枚举类

**Comment by riverchu** [comment]
> > 是因为没有用指针吧？ ScanValuer接口的Scan用的就是database/sql的Scanner方法
> 
> 可以给多一点提示吗😭

😂就是说 Type这个字段，类型可以用 `*const.ArtworkSnapshotType` 而不是单纯的类型`const.ArtworkSnapshotType`

**Comment by riverchu** [comment]
> 我发现数据库读出来的record里面的值无法映射成枚举类

因为scan方法没有生效吧

**Comment by waltcow** [comment]
原来我是这样写的
```go
func (a ArtworkSnapshotType) Scan(value interface{}) error {
	return nil
}
```

**Comment by riverchu** [comment]
> 原来我是这样写的
> 
> ```go
> func (a ArtworkSnapshotType) Scan(value interface{}) error {
> 	return nil
> }
> ```
> 
> 后面写成这样
> 
> ```go
> func (a *ArtworkSnapshotType) Scan(value interface{}) error {
> 	if v, ok := value.(int64); ok {
> 	
> 		*a = ArtworkSnapshotType(v)
> 		return nil
> 	}
> 	return errors.New("failed to scan ArtworkSnapshotType")
> }
> ```
> 
> 编译不过
> 
> > cannot use constant.ArtworkSnapshotWeixinChatBackground (type constant.ArtworkSnapshotType) as type field.ScanValuer in argument to Template.Type.In:
> > constant.ArtworkSnapshotType does not implement field.ScanValuer (Scan method has pointer receiver)

用指针做接收器就是*constant.ArtworkSnapshotType实现了field.ScanValuer，而不是constant.ArtworkSnapshotType实现了field.ScanValuer

另外，只能用指针作为接收器，不然不能修改自身的值

**Comment by waltcow** [comment]
字段如果用了*const.ArtworkSnapshotType，业务编码时将带来更多的复杂性，思虑再三还是不想用枚举了

还有就是scan 出来的value竟然是`uint8[]`, 

![image](https://user-images.githubusercontent.com/3941174/147314692-7e135fb5-0f1c-4d10-8bd4-d249f669ef96.png)

查了下也有类似的 https://github.com/go-sql-driver/mysql/issues/441

**Comment by riverchu** [comment]
嗯嗯，自定义类型的方法如果不用指针是不能修改自身值的，这是go本身的特性。这个value类型是[]uint8应该是受数据库里的类型影响吧，确实比较奇怪
