### ISSUE TITLE
查询条件判断问题

### ISSUE THREAD

**Issue by eddie-fangv** [go-gorm/gen#264]
## Describe the feature
 当前端传递的查询参数不为空时，才查询该字段
如何拼接这种查询条件
尝试过使用变量Do去接收，但是有的返回时表达式Expr，无法使用

 
![Snipaste_2021-12-01_17-23-59](https://user-images.githubusercontent.com/34231359/144208046-34be23f0-5144-4d90-8c65-9875e44427bf.png)

**Comment by riverchu** [comment]
可以用Scopes方法 https://github.com/go-gorm/gen#scopes

**Comment by riverchu** [comment]
还有就是最好使用这种形式做状态叠加
```go
t = t.Where(...)
```

**Comment by eddie-fangv** [comment]
> 

这种使用where时，返回的时xxxDo,但是使用in，between这种，返回的是Expr

**Comment by riverchu** [comment]
举个具体的例子？返回xxxDo的是查询用的，返回Expr是作为查询条件使用的，使用的时候应该不会混在一起呀？

**Comment by eddie-fangv** [comment]
> 

![Snipaste_2021-12-01_17-23-59](https://user-images.githubusercontent.com/34231359/144210906-6d810cb5-59b9-496e-a159-4dcfccc8a5c5.png)

**Comment by riverchu** [comment]
这个`t.CreateOn.Between()`如果不放进`Where()`里面是不起作用的

**Comment by eddie-fangv** [comment]
可以了，谢谢

![Snipaste_2021-12-01_17-23-59](https://user-images.githubusercontent.com/34231359/144212244-2dc35aef-034c-4778-a45c-700ffbb0e2ea.png)

**Comment by kuangshp** [comment]
> 

可以指点下我写这个吗，我也遇到这个问题了

**Comment by qqxhb** [comment]
@kuangshp 看下上面的记录吧，是用法问题

**Comment by kuangshp** [comment]
> @kuangshp 看下上面的记录吧，是用法问题

&t.ticketBachDo这个是取不到的吧

**Comment by kuangshp** [comment]
> > @kuangshp 看下上面的记录吧，是用法问题
> 
> &t.ticketBachDo这个是取不到的吧，我这边Account是我的表对应的结构体

![image](https://github.com/go-gorm/gen/assets/15928680/9b6da40b-c647-493e-a631-8a30191693db)

**Comment by qqxhb** [comment]
> > > @kuangshp 看下上面的记录吧，是用法问题
> > 
> > 
> > &t.ticketBachDo这个是取不到的吧，我这边Account是我的表对应的结构体
> 
> ![image](https://user-images.githubusercontent.com/15928680/246817573-9b6da40b-c647-493e-a631-8a30191693db.png)

没懂过，这个是要取什么？

**Comment by fangvvvvv** [comment]
你这个应该是  do:= queryAccountBuilder.AccountDo， 取的是生成的代码里其中有个属性

**Comment by fangvvvvv** [comment]
你这个应该是  do:= &queryAccountBuilder.AccountDo， 取的是生成的代码里其中有个属性
if len(username)>0{
  do=do.where(queryAccountBuilder.UserName.Like(xxx))
}

**Comment by kuangshp** [comment]
> 你这个应该是 do:= &queryAccountBuilder.AccountDo， 取的是生成的代码里其中有个属性 if len(username)>0{ do=do.where(queryAccountBuilder.UserName.Like(xxx)) }

![image](https://github.com/go-gorm/gen/assets/15928680/950009ca-2a14-4393-a8ab-0e07eb4d994a)
还是没有这个属性，我配置的生成文件如下,不需要需要配置哪里要生成那个
```go
package main

import (
	"fmt"
	"gorm.io/driver/mysql"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"strings"
)

// Case2Camel 下划线转驼峰(大驼峰)
func Case2Camel(name string) string {
	name = strings.Replace(name, "_", " ", -1) // 根据_来替换成
	name = strings.Title(name)                 // 全部大写
	return strings.Replace(name, " ", "", -1)  // 删除空格
}

// LowerCamelCase 转换为小驼峰
func LowerCamelCase(name string) string {
	name = Case2Camel(name)
	return strings.ToLower(name[:1]) + name[1:]
}
func main() {
	const dsn = "root:123456@(localhost:3306)/gin-admin-api?charset=utf8mb4&parseTime=True&loc=Local"

	// 连接数据库
	db, err := gorm.Open(mysql.Open(dsn))
	if err != nil {
		panic(fmt.Errorf("cannot establish db connection: %w", err))
	}

	// 构造生成器实例
	g := gen.NewGenerator(gen.Config{
		// 相对执行`go run`时的路径, 会自动创建目录

		OutPath:      "./dao",   //curd代码的输出路径
		ModelPkgPath: "./model", //model代码的输出路径

		// WithDefaultQuery 生成默认查询结构体(作为全局变量使用), 即`Q`结构体和其字段(各表模型)
		// WithoutContext 生成没有context调用限制的代码供查询
		// WithQueryInterface 生成interface形式的查询代码(可导出), 如`Where()`方法返回的就是一个可导出的接口类型
		Mode: gen.WithDefaultQuery | gen.WithoutContext | gen.WithQueryInterface,

		// 表字段可为 null 值时, 对应结体字段使用指针类型
		FieldNullable: false, // generate pointer when field is nullable

		// 表字段默认值与模型结构体字段零值不一致的字段, 在插入数据时需要赋值该字段值为零值的, 结构体字段须是指针类型才能成功, 即`FieldCoverable:true`配置下生成的结构体字段.
		// 因为在插入时遇到字段为零值的会被GORM赋予默认值. 如字段`age`表默认值为10, 即使你显式设置为0最后也会被GORM设为10提交.
		// 如果该字段没有上面提到的插入时赋零值的特殊需要, 则字段为非指针类型使用起来会比较方便.
		FieldCoverable: false, // generate pointer when field has default value, to fix problem zero value cannot be assign: https://gorm.io/docs/create.html#Default-Values

		// 模型结构体字段的数字类型的符号表示是否与表字段的一致, `false`指示都用有符号类型
		FieldSignable: false, // detect integer field's unsigned type, adjust generated data type
		// 生成 gorm 标签的字段索引属性
		FieldWithIndexTag: false, // generate with gorm index tag
		// 生成 gorm 标签的字段类型属性
		FieldWithTypeTag: true, // generate with gorm column type tag
	})
	// 设置目标 db
	g.UseDB(db)

	// 自定义字段的数据类型
	// 统一数字类型为int64,兼容protobuf和thrift
	dataMap := map[string]func(detailType gorm.ColumnType) (dataType string){
		"tinyint":   func(detailType gorm.ColumnType) (dataType string) { return "int64" },
		"smallint":  func(detailType gorm.ColumnType) (dataType string) { return "int64" },
		"mediumint": func(detailType gorm.ColumnType) (dataType string) { return "int64" },
		"bigint":    func(detailType gorm.ColumnType) (dataType string) { return "int64" },
		"int":       func(detailType gorm.ColumnType) (dataType string) { return "int64" },
		"timestamp": func(detailType gorm.ColumnType) (dataType string) { return "LocalTime" }, // 自定义时间
		"decimal":   func(detailType gorm.ColumnType) (dataType string) { return "Decimal" },   // 金额类型全部转换为第三方库,github.com/shopspring/decimal
	}
	// 要先于`ApplyBasic`执行
	g.WithDataTypeMap(dataMap)

	// 自定义模型结体字段的标签
	// 将特定字段名的 json 标签加上`string`属性,即 MarshalJSON 时该字段由数字类型转成字符串类型
	jsonField := gen.FieldJSONTagWithNS(func(columnName string) (tagContent string) {
		toStringField := `id, `
		if strings.Contains(toStringField, columnName) {
			return columnName + ",string"
		} else if strings.Contains(`deleted_at`, columnName) {
			return "-"
		}
		return LowerCamelCase(columnName) // 下划线转小驼峰
	})
	// 将非默认字段名的字段定义为自动时间戳和软删除字段;
	// 自动时间戳默认字段名为:`updated_at`、`created_at, 表字段数据类型为: INT 或 DATETIME
	// 软删除默认字段名为:`deleted_at`, 表字段数据类型为: DATETIME
	autoUpdateTimeField := gen.FieldGORMTag("updated_at", func(tag field.GormTag) field.GormTag {
		return map[string]string{
			"column":  "updated_at",
			"comment": "更新时间",
		}
	})
	autoCreateTimeField := gen.FieldGORMTag("created_at", func(tag field.GormTag) field.GormTag {
		return map[string]string{
			"column":  "created_at",
			"comment": "创建时间",
		}
	})
	softDeleteField := gen.FieldType("deleted_at", "gorm.DeletedAt")
	// 模型自定义选项组
	fieldOpts := []gen.ModelOpt{jsonField, autoCreateTimeField, autoUpdateTimeField, softDeleteField}
	//fieldOpts := []gen.ModelOpt{jsonField, softDeleteField}

	// 创建模型的结构体,生成文件在 model 目录; 先创建的结果会被后面创建的覆盖
	// 这里创建个别模型仅仅是为了拿到`*generate.QueryStructMeta`类型对象用于后面的模型关联操作中
	//User := g.GenerateModel("user")
	// 如果传递了表名的时候就单独创建单独的表
	allModel := g.GenerateAllTable(fieldOpts...)
	// 创建有关联关系的模型文件
	// 可以用于指定外键
	//Score := g.GenerateModel("score",
	// append(
	//    fieldOpts,
	//    // user 一对多 address 关联, 外键`uid`在 address 表中
	//    gen.FieldRelate(field.HasMany, "user", User, &field.RelateConfig{GORMTag: "foreignKey:UID"}),
	// )...,
	//)

	// 创建模型的方法,生成文件在 query 目录; 先创建结果不会被后创建的覆盖
	//g.ApplyBasic(User)

	g.ApplyBasic(allModel...)

	g.Execute()
}

```

**Comment by fangvvvvv** [comment]
![image](https://github.com/go-gorm/gen/assets/34231359/219bd2a2-f656-4dba-ba2f-af9a7f5a4e35)

生成的数据库对象，是包含这个do的。
其实主要核心就是，你用一个对象去接where之后的对象。
 条件1：
    t=t.where(条件1)
条件2：
    t=t.where(条件2)

**Comment by kuangshp** [comment]
> ![image](https://user-images.githubusercontent.com/34231359/247503475-219bd2a2-f656-4dba-ba2f-af9a7f5a4e35.png)
> 
> 生成的数据库对象，是包含这个do的。 其实主要核心就是，你用一个对象去接where之后的对象。 条件1： t=t.where(条件1) 条件2： t=t.where(条件2)

![image](https://github.com/go-gorm/gen/assets/15928680/91529600-3592-40e4-84a5-59f08fca2dbd)
我这个地方是这个类型的，
我数据库连接的时候是这样赋值的，
![image](https://github.com/go-gorm/gen/assets/15928680/858eb09c-dde3-4abe-8978-bfaebc0d76ad)
在路由的时候是这样传递的
![image](https://github.com/go-gorm/gen/assets/15928680/66a86d1d-47ea-42e4-9958-c23da4e66bc9)
在控制层是这样的
![image](https://github.com/go-gorm/gen/assets/15928680/6d2f0201-7cf7-4830-8cf7-18a9f89e4402)
不知道是哪个环节赋值错了，麻烦大佬指点下

**Comment by fangvvvvv** [comment]
你直接用queryAccountBuilder.AccountDo.where 这样不行吗

**Comment by kuangshp** [comment]
> 你直接用queryAccountBuilder.AccountDo.where 这样不行吗

不可以的，都没有AccountDo

**Comment by fangvvvvv** [comment]
看一下，你生成的xxx.gen.go的dao层文件

**Comment by qqxhb** [comment]
> > ![image](https://user-images.githubusercontent.com/34231359/247503475-219bd2a2-f656-4dba-ba2f-af9a7f5a4e35.png)
> > 生成的数据库对象，是包含这个do的。 其实主要核心就是，你用一个对象去接where之后的对象。 条件1： t=t.where(条件1) 条件2： t=t.where(条件2)
> 
> ![image](https://user-images.githubusercontent.com/15928680/247561070-91529600-3592-40e4-84a5-59f08fca2dbd.png) 我这个地方是这个类型的， 我数据库连接的时候是这样赋值的， ![image](https://user-images.githubusercontent.com/15928680/247561663-858eb09c-dde3-4abe-8978-bfaebc0d76ad.png) 在路由的时候是这样传递的 ![image](https://user-images.githubusercontent.com/15928680/247561820-66a86d1d-47ea-42e4-9958-c23da4e66bc9.png) 在控制层是这样的 ![image](https://user-images.githubusercontent.com/15928680/247561950-6d2f0201-7cf7-4830-8cf7-18a9f89e4402.png) 不知道是哪个环节赋值错了，麻烦大佬指点下，或者大佬有简单的案例dmeo地址吗

参考下：[go-gorm/gendemo](https://github.com/go-gorm/gendemo)

**Comment by fangvvvvv** [comment]
> 

这个地方生成的db对象要跟普通的数据库对象区分，使用的是gen.go文件生成的Query对象
 genOrm:= dao.Use(dao.db)
  dao即dao对象  db=某个具体的数据,类型是 *grom.DB
  genOrm生成的是Query对象
  
![image](https://github.com/go-gorm/gen/assets/34231359/53ae9fa2-076f-4bcd-8f8a-51bba78a0449)
