### ISSUE TITLE
Not working for postgresql

### ISSUE THREAD

**Issue by wmh** [go-gorm/gen#271]
It failed with the following error message: 
```
ERROR: column "column_comment" does not exist (SQLSTATE 42703)
```

**Comment by zhangzitao** [comment]
same problem:

go/pkg/mod/gorm.io/gen@v0.1.30-0.20211206072007-1328240f6539/generator.go:189
[error] generate struct from table fail: ERROR: column "column_comment" does not exist (SQLSTATE 42703); ERROR: column "column_comment" does not exist (SQLSTATE 42703)

**Comment by riverchu** [comment]
its same with #191

**Comment by riverchu** [comment]
Postgres has its own way to query table meta info, so it cannot be queried by embedded SQL which compatible with MySQL.
We will refactor migrator to provide method to get column info from Postgres ASAP.

**Comment by cymon1997** [comment]
Hi @riverchu @jinzhu is there any progress related to this? I also face the same issue 
```
/.../go/pkg/mod/gorm.io/gen@v0.2.29/internal/check/tb_info.go:70 ERROR: column "column_comment" does not exist (SQLSTATE 42703)
```
I think this is because of this definition
```
// Column table column's info
type Column struct {
	TableName     string   `gorm:"column:TABLE_NAME"`
	ColumnName    string   `gorm:"column:COLUMN_NAME"`
	ColumnComment string   `gorm:"column:COLUMN_COMMENT"`
	DataType      string   `gorm:"column:DATA_TYPE"`
	ColumnKey     string   `gorm:"column:COLUMN_KEY"`
	ColumnType    string   `gorm:"column:COLUMN_TYPE"`
	ColumnDefault string   `gorm:"column:COLUMN_DEFAULT"`
	Extra         string   `gorm:"column:EXTRA"`
	IsNullable    string   `gorm:"column:IS_NULLABLE"`
	Indexes       []*Index `gorm:"-"`

	dataTypeMap map[string]func(detailType string) (dataType string) `gorm:"-"`
	jsonTagNS   func(columnName string) string                       `gorm:"-"`
	newTagNS    func(columnName string) string                       `gorm:"-"`
}
```
What's the point of having `column_comment` for model generation though? I mean if that's not necessary, can we just remove it so other driver won't get any trouble. Thanks!

**Comment by francistm** [comment]
I create a fork version at <https://github.com/francistm/gen/tree/feat/using-gorm-migrator>, using `gorm.Migrator` to generate postgre tables.

Index in table doesn't work at this moment, can be used to generate postgre table models emergency by `go mod replace`.

**Comment by riverchu** [comment]
> Hi @riverchu @jinzhu is there any progress related to this? I also face the same issue
> 
> ```
> /.../go/pkg/mod/gorm.io/gen@v0.2.29/internal/check/tb_info.go:70 ERROR: column "column_comment" does not exist (SQLSTATE 42703)
> ```
> 
> I think this is because of this definition
> 
> ```
> // Column table column's info
> type Column struct {
> 	TableName     string   `gorm:"column:TABLE_NAME"`
> 	ColumnName    string   `gorm:"column:COLUMN_NAME"`
> 	ColumnComment string   `gorm:"column:COLUMN_COMMENT"`
> 	DataType      string   `gorm:"column:DATA_TYPE"`
> 	ColumnKey     string   `gorm:"column:COLUMN_KEY"`
> 	ColumnType    string   `gorm:"column:COLUMN_TYPE"`
> 	ColumnDefault string   `gorm:"column:COLUMN_DEFAULT"`
> 	Extra         string   `gorm:"column:EXTRA"`
> 	IsNullable    string   `gorm:"column:IS_NULLABLE"`
> 	Indexes       []*Index `gorm:"-"`
> 
> 	dataTypeMap map[string]func(detailType string) (dataType string) `gorm:"-"`
> 	jsonTagNS   func(columnName string) string                       `gorm:"-"`
> 	newTagNS    func(columnName string) string                       `gorm:"-"`
> }
> ```
> 
> What's the point of having `column_comment` for model generation though? I mean if that's not necessary, can we just remove it so other driver won't get any trouble. Thanks!

ok we will optimize `gorm` tag soon

**Comment by zachspar** [comment]
Will postgresql be supported anytime in the near future?

**Comment by agravelot** [comment]
Just done some test with postgres, i no longer face the same issue.
But schema annotation seems to be broken, type is always empty.

ex: `gorm:"column:name;type:;not null`

**Comment by riverchu** [comment]
> 

i will fix it ASAP

**Comment by riverchu** [comment]
> Just done some test with postgres, i no longer face the same issue. But schema annotation seems to be broken, type is always empty.
> 
> ex: `gorm:"column:name;type:;not null`

i will fix it ASAP
