### ISSUE TITLE
many2many not work

### ISSUE THREAD

**Issue by gozelus** [go-gorm/gen#285]
## Your Question
I have episode and user entity, the user has many episodes and episode has many episodes.
There are  three tables:
```
CREATE TABLE `episodes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
);
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nickname` varchar(255) NOT NULL DEFAULT '',
);
```
And I also create the relation table : 
```
CREATE TABLE `episode_user_creative_relations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20),
  `episode_id` bigint(20),
);
```

`gen` generator model just like :
```
// Episode mapped from table <episodes>
type Episode struct {
	ID                 int64        `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title              string       `gorm:"column:title;type:varchar(255);not null;index:idx_title,priority:1" json:"title"`
	Authors            []*User       `gorm:"gorm:"many2many:episode_user_creative_relations"`
}
// User mapped from table <users>
type User struct {
	ID                int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`                                   
	Nickname          string     `gorm:"column:nickname;type:varchar(175);not null;uniqueIndex:uniq_idx_nickname,priority:1" json:"nickname"` 
	Episodes          []*Episode `gorm:"gorm:"many2many:episode_user_creative_relations"`
}
```
But when run 
```
q := Use(db).Episode
e, _ := q.WithContext(context.Background()).Where(q.ID.Eq(123)).Preload(q.Authors).Take()
```
I got error 
`[error] invalid field found for struct /project_name/data/model.User's field Episodes: define a valid foreign key for relations or implement the Valuer/Scanner interface`

## Expected answer
Why it not work?

**Comment by riverchu** [comment]
🤔  seems like a issue about `GORM` tag, 
did `GEN` generate tag with 2 gorm like `gorm:"gorm:"many2many:episode_user_creative_relations"` ??

**Comment by gozelus** [comment]
> 🤔 seems like a issue about `GORM` tag, did `GEN` generate tag with 2 gorm like `gorm:"gorm:"many2many:episode_user_creative_relations"` ??

Yep

**Comment by riverchu** [comment]
> > 🤔 seems like a issue about `GORM` tag, did `GEN` generate tag with 2 gorm like `gorm:"gorm:"many2many:episode_user_creative_relations"` ??
> 
> Yep

try remove verbose `gorm` like: `gorm:"many2many:episode_user_creative_relations"`
And maybe you can show the generate code which config many to many relationships

**Comment by riverchu** [comment]
show me your generate code?

**Comment by riverchu** [comment]
Has the issue been solved?

**Comment by riverchu** [comment]
After testing for many2many, i found no bug in both generation and query progress. So i will close this issue.
If has any question, you can feel free to reopen this issue.
