### ISSUE TITLE
关于如何使用In查询问题

### ISSUE THREAD

**Issue by eddie-fangv** [go-gorm/gen#286]
目前有个需求是需要使用 in 查询

查看API 发现，in 条件后面跟的是一个可变参数，根据当前字段类型确定的类型

搜索使用样例，看到内容如下
···
u := query.Use(db).User
users, err := u.WithContext(ctx).Where(u.Columns(u.ID, u.Name).In(field.Values([][]inferface{}{{1, "modi"}, {2, "zhangqiang"}}))).Find()
// SELECT * FROM `users` WHERE (`id`, `name`) IN ((1,'humodi'),(2,'tom'));
···
关于这个样例：看到field.Values()返回的是一个value对象，如何转成的?没看懂

有没有一个直接使用的子查询作为in的参数呢

select * from A where A.id in (select B.a_id  from B)  这种

**Comment by qqxhb** [comment]
@eddie-fangv 
https://github.com/go-gorm/gen#subquery
orders, err := a.WithContext(ctx).Where(a.Columns(a.Amount).In(b.WithContext(ctx).Select(b.Amount)).Find()

**Comment by eddie-fangv** [comment]
@qqxhb 非常感谢，我在subquery下找了半天没找到，哈哈哈，尴尬

**Comment by riverchu** [comment]
> @qqxhb 非常感谢，我在subquery下找了半天没找到，哈哈哈，尴尬

问题解决了吗？

**Comment by eddie-fangv** [comment]
@riverchu 按照他的方法，已经解决了，谢谢
