### ISSUE TITLE
How to use limit in hasmany preload?

### ISSUE THREAD

**Issue by gozelus** [go-gorm/gen#291]
## Your Question

How to use limit in hasmany preload ? I didn't find limit func in `RelationField` interface.

**Comment by riverchu** [comment]
Offset/Limit will be provided in next release version

**Comment by gozelus** [comment]
> Offset/Limit will be provided in next release version
Is there an estimated release time？

**Comment by gozelus** [comment]
> Offset/Limit will be provided in next release version

Is there an estimated release time？

**Comment by riverchu** [comment]
try v0.2.23
