### ISSUE TITLE
请问如何支持表名的前缀

### ISSUE THREAD

**Issue by sunquangang** [go-gorm/gen#295]
## Your Question
所有的表都有一个统一的前缀，不想在生成的代码中显示这个前缀，有什么好的办法么

**Comment by qqxhb** [comment]
https://gorm.io/docs/gorm_config.html#NamingStrategy
@sunquangang 初始化db的时候配置下，表前缀就可以了
``` &gorm.Config{
  NamingStrategy: schema.NamingStrategy{
    TablePrefix: "t_",   // table name prefix, table for `User` would be `t_users`
  }```

**Comment by sunquangang** [comment]
我是想生成的pre_xxx.gen.go 不带前缀 pre_ , 只有xxx.gen.go
db 初始化传的prefix ，在后续的调用中不能直接拿到。

我增加了一个字段，只传没有前缀的表名，TableName 字段通过gorm 方法自动生成。
生成文件的时候使用没有前缀的表名。
不知道有没有更优雅的解决方案。


![image](https://user-images.githubusercontent.com/13553236/146163654-6d108054-020f-4c55-b921-58b4c58bf542.png)

**Comment by sunquangang** [comment]
另外，建议生成的文件名 model 和query 的名字不要完全一样，假如想放到同一个目录下，就会被覆盖了
![image](https://user-images.githubusercontent.com/13553236/146175209-1499b335-0237-499a-8659-6c6d3ff13ec4.png)

**Comment by riverchu** [comment]
> 另外，建议生成的文件名 model 和query 的名字不要完全一样，假如想放到同一个目录下，就会被覆盖了
> 
> ![image](https://user-images.githubusercontent.com/13553236/146175209-1499b335-0237-499a-8659-6c6d3ff13ec4.png)
> 
> 

这个有意设计的，不建议放在一个目录下

**Comment by sunquangang** [comment]
> > 另外，建议生成的文件名 model 和query 的名字不要完全一样，假如想放到同一个目录下，就会被覆盖了
> > ![image](https://user-images.githubusercontent.com/13553236/146175209-1499b335-0237-499a-8659-6c6d3ff13ec4.png)
> 
> 这个有意设计的，不建议放在一个目录下


放在一起有什么问题么？我是想每个表一个目录，放着三个文件，这三个文件不是一起使用的么

**Comment by riverchu** [comment]
预期是model文件单独在一个packgae里面，query文件单独一个package

**Comment by riverchu** [comment]
> 

传没有前缀的表名可以支持，不过生成的文件名没有修改的必要吧？也不影响什么

**Comment by riverchu** [comment]
> 我是想生成的pre_xxx.gen.go 不带前缀 pre_ , 只有xxx.gen.go db 初始化传的prefix ，在后续的调用中不能直接拿到。
> 
> 我增加了一个字段，只传没有前缀的表名，TableName 字段通过gorm 方法自动生成。 生成文件的时候使用没有前缀的表名。 不知道有没有更优雅的解决方案。
> 
> ![image](https://user-images.githubusercontent.com/13553236/146163654-6d108054-020f-4c55-b921-58b4c58bf542.png)

使用`NameStategy`的`TableName`方法是有副作用的，比如你原本的表名有大写字母的情况就会被转换成下划线分段的格式

**Comment by sunquangang** [comment]
> > 
> 
> 传没有前缀的表名可以支持，不过生成的文件名没有修改的必要吧？也不影响什么

前缀通常是业务不需要感知的内容，在配置层面可以切换，但是在业务代码里面是不应该体现的内容。

**Comment by riverchu** [comment]
go语言的文件命名不会对文件有任何影响呀，你是说配置层面切换前缀会对生成文件名造成影响吗？

**Comment by sunquangang** [comment]
> go语言的文件命名不会对文件有任何影响呀，你是说配置层面切换前缀会对生成文件名造成影响吗？

代码运行是没有问题的，只是不想看到，其实也不应该被看到

**Comment by riverchu** [comment]
我考虑一下实现方式吧，应该可以支持

**Comment by sunquangang** [comment]
> 我考虑一下实现方式吧，应该可以支持

 非常感谢

**Comment by riverchu** [comment]
实现了一个新功能，在初始化`generator`之后可以直接指定对应文件的命名策略，这样就可以清理掉前缀了
```go
g.WithFileNameStrategy(func(tableName string) string {
    tablePrefix := "t_"
    return strings.TrimPrefix(tableName, tablePrefix)
})
```
