### ISSUE TITLE
是否可以只返回select 的字段，而不是struct的所有字段

### ISSUE THREAD

**Issue by sunquangang** [go-gorm/gen#300]
自动生成的model 设置了json tag，系统统一json的结构。但是不同场景希望返回不同的字段。
所以，希望通过select 控制每个场景希望查询的字段。

现在用Find()返回的是model中struct的所有字段，如果没在select中，则返回默认值。
这样api接口输出的数据就都是全部字段了。
有没有办法通过select 直接控制输出哪些字段，且不用每次查询都创建一个struct ，因为不想每次都写tag

**Comment by qqxhb** [comment]
@sunquangang 不建议直接吧db层的model返回端上哈，他们之间应该要存在一个转换层。
select之动态返回不的struct，目前可能只能考虑用map了

**Comment by sunquangang** [comment]
> @sunquangang 不建议直接吧db层的model返回端上哈，他们之间应该要存在一个转换层。 select之动态返回不的struct，目前可能只能考虑用map了

好的，谢谢
