### ISSUE TITLE
Is there a way to Generate only Models and skip query file

### ISSUE THREAD

**Issue by avvineed** [go-gorm/gen#306]
## Can i generate only table models skipping query and extra ORM part
Yes its developer friendly and more secure as mentioned in https://github.com/go-gorm/gen/issues/220 but would be great if we get extra option to generate only models

**Comment by qqxhb** [comment]
@avvineed 
```go
g.GenerateModel("company")
g.GenerateModelAs("people", "Person", gen.FieldIgnore("address")))
g.Execute()
 ```

**Comment by avvineed** [comment]
yes, had tried it just create below files.
db
├── query
│   └── gen.go

no Model files

**Comment by riverchu** [comment]
try upgrade to latest version

**Comment by avvineed** [comment]
yes, worked with latest version 
thank you
