### ISSUE TITLE
gorm-gen 支持 postgres 数据库吗

### ISSUE THREAD

**Issue by catbugdemo** [go-gorm/gen#317]
我使用的数据库是 postgres，但是在使用 gorm-gen 的时候 查询表的信息查的是 mysql 的 information_schema.COLUMNS表，想问下是没有支持 postgres 数据库吗

**Comment by riverchu** [comment]
和 #271 是一样的问题，目前是因为不同数据库查表结构的语法不同，所以不能直接用同一个语句查询
计划gorm的migrator直接提供方法获取不同数据库的表结构，目前还没有完成，不过应该很快就会做了

**Comment by catbugdemo** [comment]
好的，谢谢说明
