### ISSUE TITLE
[error] gentool:   parse model pkg path fail: err: exit status 1: stderr: go: cannot find main module; see 'go help modules'

### ISSUE THREAD

**Issue by leiyang** [go-gorm/gen#318]
gentool -dsn "xxxx:xxxx@tcp(xxxx)/my_db?parseTime=true&loc=Local"

2021/12/24 14:27:25 got 6 columns from table <users>
2021/12/24 14:27:25 Start generating code.
2021/12/24 14:27:25 generate model file(table <users> -> {model.User}): /tmp/model/users.gen.go

2021/12/24 14:27:25 /home/lyang001/go/pkg/mod/gorm.io/gen@v0.2.29/generator.go:461
[error] parse model pkg path fail: err: exit status 1: stderr: go: cannot find main module; see 'go help modules'
2021/12/24 14:27:25 generate query file: /tmp/hellow/users.gen.go
2021/12/24 14:27:25 generate query file: /tmp/hellow/gen.go

what's wrong with it ?

**Comment by riverchu** [comment]
nothing special, actually it is a warning log, we will change log level later
