### ISSUE TITLE
如何获取生成的SQL string？

### ISSUE THREAD

**Issue by Trim21** [go-gorm/gen#330]
## Your Question

gorm 的文档 https://gorm.io/docs/sql_builder.html#DryRun-Mode 说可以直接使用db.Statment.SQL.String()获取最后生成的SQL字符串，但是gen生成的Do似乎没有办法获取到最终的字符串？

我尝试了文档中的几个方法 比如 `.UnderlyingDB().Statment.SQL.String()`，但是都获取不到正常的结果

**Comment by riverchu** [comment]
目前还不支持这个功能，是什么场景下的需求呢？

**Comment by Trim21** [comment]
debug （虽然也可以用logger）

**Comment by riverchu** [comment]
哦哦，Debug的话可以在执行`First`或者`Find`这类finish api之前加一个`Debug()`就可以了，比如`.Debug().First()`，这样具体执行的SQL会在命令行输出出来。如果太麻烦可以在开始用`Use(db.Debug())`这种形式，可以实现全局所以查询都打印SQL语句
