### ISSUE TITLE
gen命令行工具(gentool)新增参数支持只生成model文件

### ISSUE THREAD

**Issue by taobig** [go-gorm/gen#333]
## Describe the feature

目前gen命令行工具(gentool)会一起生成query文件和model文件，希望新增参数支持只生成model文件。有点类似https://github.com/go-gorm/gen/issues/306 ，但是希望gen 命令行工具直接就支持。

**Comment by riverchu** [comment]
可以支持的，下一版加上这个功能

**Comment by taobig** [comment]
使用v0.2.33版本的-onlyModel参数会报错： flag provided but not defined: -onlyModel

命令如下：
```bash
gentool -dsn "username:password@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local" -outPath ./dao -modelPkgName=model  -onlyModel
```
