### ISSUE TITLE
指定只生成model文件的情况时，任然会生成query空目录

### ISSUE THREAD

**Issue by taobig** [go-gorm/gen#334]
## Description

对于 https://github.com/go-gorm/gen/issues/306  描述的只生成model文件的情况，在指定OutPath配置项后还是会生成dal/query目录（空目录，目录下无文件生成）；但是不指定OutPath配置项（使用默认配置）则不会生成dal/query空目录。希望在没有query文件生成的时候不要创建空目录。
```
	g := gen.NewGenerator(gen.Config{
		OutPath: "../dal/query",
		//...
	})
	g.UseDB(db)
	g.GenerateAllTable()
	g.Execute()
```

**Comment by riverchu** [comment]
用的是哪个版本？

**Comment by taobig** [comment]
> 用的是哪个版本？

最新版 v0.2.32
