### ISSUE TITLE
帮助里增加查看当前版本的选项

### ISSUE THREAD

**Issue by taobig** [go-gorm/gen#337]
## Describe the feature

帮助里增加查看当前版本的选项，比如-v选项可以查看当前的版本。

**Comment by riverchu** [comment]
版本号手动写太麻烦也容易忘记更新，我了解一下看看有没有办法在go install的时候引入编译参数吧

**Comment by taobig** [comment]
@riverchu 
since go 1.18, go命令会将版本控制信息嵌入到二进制文件当中：https://tip.golang.org/doc/go1.18#go-command  
然后通过go version -m `gentool`可以看到打包的时间、hash值等信息。
