### ISSUE TITLE
Mock with interface style 

### ISSUE THREAD

**Issue by zhangzitao** [go-gorm/gen#342]
## Describe the feature

Interface style 

## Motivation

Why this project doesn't write in interface style ?

## Related Issues

It's impossible to mock xxxDo struct when importing dao in other packages, the only way to write unit test for these packages is to launch a sqlite database then fill some fake records.
Is there any way to mock method of  xxxDo struct?
if not, I think it's not appropriate for serious project, only suitable for project that is not in need for unit test.

**Comment by zhangzitao** [comment]
take a look on this:

https://github.com/gogf/gf

**Comment by riverchu** [comment]
maybe u should try sqlmock? https://www.google.com.hk/search?q=gorm+sqlmock&oq=gorm+sqlmock&aqs=chrome..69i57j0i512l4j69i60l3.2218j0j7&sourceid=chrome&ie=UTF-8

**Comment by zhangzitao** [comment]
Sqlmock is a kind of integrated test, not unit test. And it's hard to compose test case.

Interface style will not change the api, but provide a way to mock.

**Comment by riverchu** [comment]
i don't understand, do you mean you want to mock with interface in orm's unit test?

**Comment by zhangzitao** [comment]
> i don't understand, do you mean you want to mock with interface in orm's unit test?

Not in in orm's unit test. But in other packages which import orm and need to mock orm.

I've pushed a pr, you may understand what I mean after gen some code.

**Comment by riverchu** [comment]
i know about the interface style you said, just curious about its applicable scenes

**Comment by zhangzitao** [comment]
## foler tree

- service
  - service.go
- orm
  - mock
    - mock.orm.go
  - user.gen.go
  - gen.go
- model
  - user.gen.go
 
## service.go

```go
package service

import (
    myproject/orm
)

type service struct {
    QueryCtx orm.QueryCtx
}

func (s service) CreateUserIfCapacious() error {
     users, err := s.Query.User.Find()
     if len(users)>0 {
        return nil
     }
     return s.Query.User.Create(&model.User{ID:123, Name:"123"})
}
```

## service_test.go

```go
package service

import (
	mock_orm "myproject/service/mock"
	orm "myproject/orm"
)
...

serviceInstance := new(service)
serviceInstance.QueryCtx = orm.QueryCtx{}
serviceInstance.QueryCtx.User = mock_orm.NewMockIUserDo(mockCtrl) // This is the point

Describe("Service", func() {
    Context("CreateUserIfCapacious", func() {
	    It("should be ok", func() {
	   	   mockOrmUser.EXPECT().Find().Return([]model.User{}, nil)
	   	   mockOrmUser.EXPECT().Create(gomock.Any()).Return(nil)
	   	   Expect(serviceInstance.CreateUserIfCapacious()).Error().To(BeNil())
	    })
    })
})
...
```

**Comment by riverchu** [comment]
ok, i will carefully consider your proposal

**Comment by riverchu** [comment]
I will implement this feature in the near future.

**Comment by dcaf-mocha** [comment]
Hey folks, @riverchu any updates on this issue?

**Comment by FLAGLORD** [comment]
Now gen only generates interface for DO object. Is it possible to generate interface for `Query` in gen.go. Most services would import `Query` instead of some DO object(because DO object would use context to initialilze). It would be easier to mock if we have a interface for `Query` and `queryCtx`
