### ISSUE TITLE
How to count in group

### ISSUE THREAD

**Issue by myml** [go-gorm/gen#344]
## Your Question

Hello! I have a problem. I want to do a simple group count? like this `select name,count(*) from t group by name`

## The document you expected this should be explained

Yes

## Expected answer
I try to user `All.Count` to solve, but it does not work.
log output
```text
SELECT `t`.`name` ,COUNT(`t`.`*`) FROM `t` GROUP BY `t`.`name`
Error 1054: Unknown column 't.*' in 'field list'
```

**Comment by riverchu** [comment]
try `primkey.Count()`?

**Comment by myml** [comment]
i have try, it causes an exception: reflect: reflect.Value.Set using unaddressable value
Do you need a detailed stack log?

**Comment by riverchu** [comment]
ok, logs can help

**Comment by myml** [comment]
You are right. The panic is because I passed a non-pointer.
Too much interference whit the project code. 
Thanks for your quick answer.
