### ISSUE TITLE
FindOne API

### ISSUE THREAD

**Issue by to2false** [go-gorm/gen#351]
## Describe the feature
FindOne => `db.Limit(1).Find(&user)`

https://gorm.io/docs/query.html
> If you want to avoid the ErrRecordNotFound error, you could use Find like db.Limit(1).Find(&user), the Find method accepts both struct and slice data

**Comment by riverchu** [comment]
api explosion is what we don't want to see. So we may not implement api which is not necessary

**Comment by to2false** [comment]
Just avoid the ErrRecordNotFound error, but `Find()` return slice[]
Or is there another way?

**Comment by riverchu** [comment]
I still don't  understand why `Find()` return slice can be a problem? check the length of return array is not complicate in my mind

**Comment by riverchu** [comment]
Actually, GORM `Find()` do not support nil struct pointer, so it can't help you judge if query find data. And `FindOne()` is redundant.

**Comment by to2false** [comment]
If sql is not executed correctly, an error will be returned, it's easy to interrupt the flow.
If sql is executed correctly, the query gets 0 rows and the result will be nil, determining nil is handled in much the same way as determining if it is `ErrRecordNotFound`

This demand is not so urgent, just want to know whether the official will provide.

**Comment by zohar-soul** [comment]
希望能支持一下, 没有真的很不方便.

**Comment by riverchu** [comment]
比较`len(records) > 0`和比较`record == nil`差很多吗？

**Comment by riverchu** [comment]
> 希望能支持一下, 没有真的很不方便.

比较`len(records) > 0`和比较`record == nil`差很多吗？

**Comment by zohar-soul** [comment]
> 比较`len(records) > 0`和比较`record == nil`差很多吗？

差别很小, 但是比较完之后, record 的话就可以直接用了, 而 records 还要取出来第一个(也许还要创建一个新的变量, 不然每次都要records[0].xxxx), 
最最最关键的是 findOne 是一个非常高频的操作.... 反复重复书写一样的模板代码太折腾人了.

**Comment by zohar-soul** [comment]
也许是不是可以通过某种方式允许用户来自定义/扩展 model 里面的方法, 既能灵活定制, 也能避免预制的方法数的膨胀.
