### ISSUE TITLE
DIY methods of model struct?

### ISSUE THREAD

**Issue by to2false** [go-gorm/gen#352]
## Your Question

Is there a way to diy methods of model struct?

## The document you expected this should be explained

Want to add some common custom methods, not sure how to implement it
example:
```
func (m *User) IsEmpty() bool {
    if m == nil {
        return true
    }

    return m.ID == 0
}
```

**Comment by riverchu** [comment]
Maybe you can express it more clearly

**Comment by to2false** [comment]
user.gen.go:
```
// User mapped from table <user>
type User struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`        // 主键ID
}

// DIY method
func (m *User) IsEmpty() bool {
    if m == nil {
        return true
    }

    return m.ID == 0
}
```

**Comment by riverchu** [comment]
emmm,  it seems like not a common feature

**Comment by to2false** [comment]
The example may not be clear, the main thing is to have a way to extend the model methods

**Comment by riverchu** [comment]
do u think providing a method to accept a function template an acceptable solution?

**Comment by to2false** [comment]
Yes.

**Comment by riverchu** [comment]
ok, we will discuss a most suitable implementation method, And more ideas from you are welcome👍

**Comment by to2false** [comment]
👌
