### ISSUE TITLE
工程开发中需支持全量&增量

### ISSUE THREAD

**Issue by dino-ma** [go-gorm/gen#357]
问题：
在工程中出现某个数据表字段变动、增减数据表时，重新gentool -c gen.yml指定某个数据表会导致所有的代码全部重新生成，不太友好对代码颠簸极大。

希望：

- [ ] 可识别变动字段、数据表，并不全部重新生成
- [ ] 支持增量与全量，并且处理不同逻辑
- [ ] 支持特殊TAG标记，允许业务侧自己传入分库、分表等业务不会进行替换

**Comment by riverchu** [comment]
生成的速度可接受吗？

**Comment by dino-ma** [comment]
> 生成的速度可接受吗？

当然是越快越好。譬如 10张表初次生成的速度为5S，增量的时候尽量不要超过10S我认为是没问题的。
感觉通过文件Hash可以过滤掉没有变更的文件，公共文件需要费心处理一下。

**Comment by riverchu** [comment]
我是说目前生成代码的速度可接受么？还需要优化么？

**Comment by dino-ma** [comment]
> 我是说目前生成代码的速度可接受么？还需要优化么？

目前的生成的速度可接受，如果可以更快的话更好。
明后天我可以测试一个单库分了500张数据表的生成时间。

**Comment by game1991** [comment]
请问这个增量生成的问题解决了吗？有没有example演示下~谢谢
