### ISSUE TITLE
Options to disallow pointers

### ISSUE THREAD

**Issue by Trim21** [go-gorm/gen#370]
## Describe the feature

A new config field to disallow field to be generate as pointer type.

## Motivation

Currently I'm stuck at v0.2.37 because I have many `not null` field with default value.

In v0.2.38, the `FieldNullable` config only work with field `null` and has no default value, so in this case, I still get many field generated as pointers type. Which I'd like a option to disable this behavior 

## Related Issues

https://github.com/go-gorm/gen/pull/361

https://github.com/go-gorm/gen/blob/c62696dfd0373fd686d02fa93b7a28a16d36fda9/internal/model/tbl_column.go#L63

**Comment by riverchu** [comment]
ok, i will fix this issue very soon

**Comment by riverchu** [comment]
u may try `go get gorm.io.gen@6a91eff225835cd79db300791b8e8718772c7173`, i try to fix this issue in this commit

**Comment by Trim21** [comment]
> u may try `go get gorm.io.gen@6a91eff225835cd79db300791b8e8718772c7173`, i try to fix this issue in this commit

LGTM

**Comment by riverchu** [comment]
Docs has been updated [here](https://github.com/go-gorm/gen#quick-start), and [example](https://github.com/go-gorm/gen/blob/master/examples/cmd/sync_table/generate.go#L38) updated too.
