### ISSUE TITLE
table sharding support

### ISSUE THREAD

**Issue by jiekun** [go-gorm/gen#382]
## Describe the feature
Add table sharding support.

## Motivation
Table sharding is used in many enterprise applications. Those tables share the same struct/model and contain special prefix/suffix.

e.g. my_table_00000000 / my_table_00000001 / ...

I think we could build a feature to support this, and let users config their customed prefix/suffix rule or we could say a naming rule.

```
u := query.Use(db).User
u.WithContext(ctx).Sharding(HERE WE PASS A SHARDING VALUE).Select(u.Name, u.Age).Create(&user)
```

**Comment by riverchu** [comment]
https://github.com/go-gorm/sharding is recommended way for this issue

**Comment by jiekun** [comment]
Currently, the sharding plugin is too weak without `JOIN` support...
