### ISSUE TITLE
Should we allow mysql json field as datatypes.JSON

### ISSUE THREAD

**Issue by lilien1010** [go-gorm/gen#388]
```
type Bill struct {
	ID              int32     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Detail        string ->  datatypes.JSON    `gorm:"column:detail;type:json" json:"detail"`
}
```

in some cases, we have already defined the field as type `JSON`, gen gorm also have `gorm.io/datatypes` to support it.

but when code was generated by go-gorm/gen it will define all `type:json` field as string

**Comment by riverchu** [comment]
u may try this https://github.com/go-gorm/gen#data-mapping
