### ISSUE TITLE
gentool generate default value tag

### ISSUE THREAD

**Issue by zhuxubin01** [go-gorm/gen#399]
## Describe the feature
now when i use gentool generate model,it can not generate the default value that set in the create table ddl.

**Comment by zhuxubin01** [comment]
> 

default不是空格的时候能生成,比如的定义的default 是' '，中间有个空格tag里面无法正确生成 

![image](https://user-images.githubusercontent.com/23697363/159755855-ba0f8ee3-5d68-4fe0-88e9-5af6a2bb3eb3.png)

**Comment by riverchu** [comment]
默认值为纯空格的时候gorm处理时trim掉了，有需求要默认值是纯空格么？还是只是测试一下？

**Comment by zhuxubin01** [comment]
> 

有需求,我们在单元测试的时候,会通过model migrate 如果没有这个空的默认值,数据插不进去会报错

**Comment by riverchu** [comment]
抱歉，有点忙。”没有这个空的默认值,数据插不进去会报错“ 是什么意思？可以列一下具体执行的SQL语句么？

**Comment by YakultGo** [comment]
默认为NULL的时候，为什么也不会加上呢，当我申明一个类型为time.Time的时候，如果tag里面没有default:null，那么如果该字段不传值，会报错，得显示的写上default:null，但是好像生成的代码是不会带上default:null的
