### ISSUE TITLE
结构体名字生成错误

### ISSUE THREAD

**Issue by zhuxubin01** [go-gorm/gen#409]
数据库表名字是project_canvas

生成结构体名字少了s

![image](https://user-images.githubusercontent.com/23697363/161998012-dde57b4f-2cbc-42f1-b2d7-b22f9943b3a4.png)

canvas 是画布 复数是canvases

初步理解程序把canvas理解成了复数

**Comment by riverchu** [comment]
是单复数转化的问题，需要自己单独制定规则了，参考：https://github.com/jinzhu/inflection#register-rules
```golang
inflection.AddIrregular("convas", "convases")
```
