### ISSUE TITLE
Sqlite必须注册类型否则生成无类型(全是field.Field)

### ISSUE THREAD

**Issue by EwingTsai** [go-gorm/gen#415]
// Sqlite必须注册类型映射
	config.WithDataTypeMap(map[string]func(detailType string) (dataType string){
		"integer":  func(detailType string) (dataType string) { return "int64" },
		"real":     func(detailType string) (dataType string) { return "float64" },
		"text":     func(detailType string) (dataType string) { return "string" },
		"datetime": func(detailType string) (dataType string) { return "time.Time" },
	})

**Comment by EwingTsai** [comment]
还有这个 func(detailType string) (dataType string) { return "int64" } 为什么不可以直接用 int64 ？

**Comment by riverchu** [comment]
`integer`和`datetime`是有支持的：
- https://github.com/go-gorm/gen/blob/master/internal/model/base.go#L80
- https://github.com/go-gorm/gen/blob/master/internal/model/base.go#L103

其他类型会考虑支持，如果你能给个更全的列表我就可以更快的支持了

**Comment by riverchu** [comment]
text也有：https://github.com/go-gorm/gen/blob/master/internal/model/base.go#L98

**Comment by EwingTsai** [comment]
所以我现在是为generator单独准备了一个db，规避了这些问题

**Comment by riverchu** [comment]
1. 列的这4个数据类型，只有real是之前没有支持的
2. 零值的default tag这个问题刚刚解决了 #428 一会儿我发个版
3. `Sqlite表存在主键以外的索引，会报invalid DDL`这个是tag的解析问题，可以单独在[GORM](https://github.com/go-gorm/gorm)那边提个issue

**Comment by xtulnx** [comment]
举个爪：

请问一下， @riverchu 从本地 struct 生成 query 怎么支持定义类型呢？

比如：

```

type ProjectReserve struct {
   gorm.Model
   BaseDay   datatypes.Date
   BeginTime datatypes.Time
   EndTime   datatypes.Time
}
// ...

g := gen.NewGenerator(gen.Config{ OutPath:  "./query" } )
g.UseDB(db)
g.ApplyBasic(ProjectReserve{})
g.Execute()
```

**Comment by riverchu** [comment]
就这样写就可以了，不过建议放在单独的package下面，不要放在这里定义
