### ISSUE TITLE
希望把生成的类型公开，方便封装条件方法

### ISSUE THREAD

**Issue by EwingTsai** [go-gorm/gen#419]
我有一个查询方法，中间有一段条件解析的语句，希望抽象为方法，但是userDo(代码中的udo变量)是个私有类型，无法定义参数类型

`
func QueryUser(ctx context.Context, option QueryOption, pager common.Pager) ([]*model.User, int64, error) {
	db := config.GetDB(ctx)
	u := query.Use(db).User

	var omitFields []field.Expr
	if option.OmitHeader {
		omitFields = append(omitFields, u.Header)
	}
	if option.OmitPassword {
		omitFields = append(omitFields, u.Password)
	}
	udo := u.Omit(omitFields...)

	if option.IdEq > 0 {
		udo = udo.Where(u.ID.Eq(option.IdEq))
	}
	if len(option.NameEq) > 0 {
		udo = udo.Where(u.Name.Eq(option.NameEq))
	}
	nameStartWith := converter.RemoveSqlWildcard(option.NameStartWith)
	if len(nameStartWith) > 0 {
		udo = udo.Where(u.Name.Like(nameStartWith + "%"))
	}
	if len(option.GenderEq) > 0 {
		udo = udo.Where(u.Gender.Eq(option.GenderEq))
	}
	if option.StatusEq > 0 {
		udo = udo.Where(u.Status.Eq(option.StatusEq))
	}

	var err error
	var count int64
	var data []*model.User
	if pager.GetCount {
		count, err = udo.Count()
		if err != nil {
			return data, count, err
		}
	}
	if pager.GetRows && (!pager.GetCount || count > 0) {
		data, err = udo.Find()
		if err != nil {
			return data, count, err
		}
	}
	return data, count, err
}
`

**Comment by EwingTsai** [comment]
我也参考了它实现的接口，都不能满足要求

**Comment by riverchu** [comment]
条件方法可以用`Scopes` https://github.com/go-gorm/gen#scopes

**Comment by riverchu** [comment]
类型后面会考虑用接口形式开放

**Comment by EwingTsai** [comment]
谢谢！
