### ISSUE TITLE
希望生成Model可以把FieldName直接生成。

### ISSUE THREAD

**Issue by m430** [go-gorm/gen#420]
场景：
当用protobuf的fieldMask场景对实体做更新的时候，需要根据fieldmask的paths对实体属性做判断，这个时候需要实体的属性名去跟path对比对，所以希望可以直接生成model的时候，把属性名生成了。期望生成在DO对象上。

类似ent生成如下图：

![image](https://user-images.githubusercontent.com/4023173/163778822-c4ab0967-28e6-495e-aa42-e01c393acdbb.png)

这样方便用户在dao层对更新属性做比对。

**Comment by riverchu** [comment]
`u.ID.ColumnName()`是说这种数据吗？

**Comment by m430** [comment]
看了下，返回的sql原来是string别名，可以满足需求。谢谢您的回复。 @riverchu
