### ISSUE TITLE
希望增加动态条件支持

### ISSUE THREAD

**Issue by EwingTsai** [go-gorm/gen#422]
例如以下代码：
if option.IdEq > 0 {
	udo = udo.Where(u.ID.Eq(option.IdEq))
}
udo.Find()

可以改成：
udo.WhereIf(option.IdEq>0, u.ID.Eq(option.IdEq)).Find()
或
udo.WhereIf(**ifs.GtZero**(option.IdEq), u.ID.Eq(option.IdEq)).Find()

ifs包中可以有常见的判断方法：
GtZero(int64)
LtZero(int64)
GteZero(int64)
LteZero(int64)
LengthGtZero(string)
NotAllSpace(string)
......

**Comment by EwingTsai** [comment]
WhereIf 第一个参数为bool

**Comment by riverchu** [comment]
这个实现方式会让工具这边的复杂度提升很多，而且也不是一个最基础的通用方法，属于`语法糖`一样的封装，这种需求支持下去的话可能造成工具API爆炸，最终导致使用上学习成本过高，开发者也难以维护，所以暂时不考虑支持。

**Comment by EwingTsai** [comment]
从技术角度可以理解。但是工具为用户而生，并非为技术而生，Gorm的诞生就是为了sql更好用

如果只增加 WhereIf 方法的话只需要多几行代码即可呢（不止我一个人需要，这是个热门需求，望采纳）

**Comment by jinzhu** [comment]
使用 `Scopes` 比 WhereIf 灵活的多
