### ISSUE TITLE
是否支持 INSERT INTO SELECT 语句

### ISSUE THREAD

**Issue by sswanv** [go-gorm/gen#427]
## Your Question
```sql
INSERT INTO user(user_id, name, age) SELECT 1001, name, age WHERE age = 20;
```

## Expected answer

这种语句用 gen 该怎么写呢？

**Comment by riverchu** [comment]
可以用[DIY方法](https://github.com/go-gorm/gen#diy-method)实现，或者分两次操作来实现

**Comment by sswanv** [comment]
SELECT 1001, name, age 这种单独查询可以实现吗

**Comment by riverchu** [comment]
是指1001这种硬编码的方式吗？这个不支持的，查询的时候都是会转义的，查询的时候会变成`1001`的形式被当成列名来处理

**Comment by sswanv** [comment]
```sql
SELECT 1001, name, age
```
> 查询的时候会变成1001的形式被当成列名来处理。

我就想要这样的效果可以怎么处理呢
