### ISSUE TITLE
SQL Server With Multiple Schema

### ISSUE THREAD

**Issue by bashdrew** [go-gorm/gen#440]
## Your Question
Does the generator support multiple schema?  I have SQL Server database which has 2 schema.  When I ran the generator, it gives me the error below.  It's because table1 is in a different schema.  It needs to be fully qualified as schema2.table1.  Is there a way to go around this?  Thank you in advance.

mssql: Invalid object name 'table1'.
[4.423ms] [rows:-] SELECT * FROM "table1" ORDER BY (SELECT NULL) OFFSET 0 ROW FETCH NEXT 1 ROWS ONLY

2022/05/06 12:14:31 /home/bashdrew/go/pkg/mod/gorm.io/gen@v0.3.4/generator.go:139
[error] generate struct from table fail: mssql: Invalid object name 'table1'.
panic: generate struct fail

**Comment by riverchu** [comment]
maybe u should try connecting schema with different dsn by [dbresolevr](https://gorm.io/docs/dbresolver.html#content-inner)

**Comment by bashdrew** [comment]
Thank you for your response.  The problem is for both schema, we use the same dsn.  to access the non-default schema tables, we just fully qualify it.  I looked into the mssql driver and in the function GetTables(), it executes:

"SELECT table_name FROM INFORMATION_SCHEMA.tables WHERE  table_catalog = ?"

This will grab all the tables regardless of table_schema so it's throwing an error if the table is not in the default schema.  Is there a way to filter out by schema, too?

**Comment by riverchu** [comment]
sorry, there is no reliable way to filter schema, we still recommend you using different `DSN`.

**Comment by bashdrew** [comment]
thanks for your help on this.  btw, can i clone the sqldriver and write my own implementation of GetTables()?

**Comment by riverchu** [comment]
of course, you can implement a sql driver by yourself

**Comment by bashdrew** [comment]
Thank you.  Writing a driver solved my issue.

**Comment by bashdrew** [comment]
Thank you.  Writing a driver solved my issue.
