### ISSUE TITLE
Generate structure from postgresql table, problem with default value

### ISSUE THREAD

**Issue by eva005** [go-gorm/gen#444]
1.  my postgresql table build statement
```
create table test
(
    address varchar(100) default ''
);
```

2.  gorm-gen generate config
```
g := gen.NewGenerator(gen.Config{
		WithUnitTest:      false,
		FieldNullable:     false,
		FieldCoverable:    false,
		FieldSignable:     false,
		FieldWithIndexTag: true,
		FieldWithTypeTag:  true,
		Mode:              gen.WithoutContext,
})
```

3. generated result
```
type Test struct {
	Address string `gorm:"column:address;type:character varying(100);default:'''::character varying'" json:"address"`
}
```

4. question: when the create() method of [gorm](https://github.com/go-gorm/gorm) is called, will generate this sql statement, the default value is incorrect
`insert into test(address) values ('::character varying');`

5. the sql statement I want to generate:
`insert into test(address) values ('');`

**Comment by garlicPasta** [comment]
Similar problems with floats here:
```
type Project struct {
	Budget                     float64        `gorm:"column:budget;type:float8;not null;default:''0'::double precision'" json:"budget"
}
```
Then i receive:
```
[error] failed to parse ''0'::double precision' as default value for float, got error: strconv.ParseFloat: parsing "''0'::double precision'": invalid syntax
``` 
I guess the generator should create `default:'0'` instead of `default:''0'::double precision'`

**Comment by yout0703** [comment]
@riverchu 这个问题依然存在，在 Postgresql 中如果有默认值就有可能出现这个情况。默认值会带上强制转换符号(如：::text)。
![image](https://github.com/go-gorm/gen/assets/63359656/5e6ed93a-64ba-416c-8129-6054db965853)
最后写到数据库中的时候就会变成 ::text 。
