### ISSUE TITLE
使用ApplyBasic传入model struct情况，可以指定生成代码中struct的名称，避免代码冲突

### ISSUE THREAD

**Issue by leostudio** [go-gorm/gen#456]
## Describe the feature

使用g.ApplyBasic()传入model struct情况下，希望可以指定生成代码中的struct的名称，解决代码冲突的问题。
一个具体的case，生成的struct名称和model所在的package name冲突，如下图所示：
![image](https://user-images.githubusercontent.com/6102493/171431230-072cc20f-698b-4258-855f-274322ea982c.png)

两个参考的思路：
1. 对实现某interface的model struct，通过interface的方法获取生成代码的struct name，如：

```go
type xxx interface {
  GeneratedStructName() string
}
```

2. Generator新增`GenerateQueryAs(model interface{},  structName  string) *check.BaseStruct`，方法提供自定义structName能力。ps：名字可以调整GenerateQueryAs只是参考。

## Motivation

可以新增可选配置生成struct name的的能力，避免生成代码的冲突的问题，让gen可以适配更多的业务场景。

## Related Issues

N/A

**Comment by riverchu** [comment]
为结构体实现`GenInternalDoName() string`方法就可以指定内部结构体的名字了
