### ISSUE TITLE
[FirstOrCreate](https://github.com/go-gorm/gen#firstorcreate) 方法不支持传入参数，是否是需要更新README文档？

### ISSUE THREAD

**Issue by wulorn** [go-gorm/gen#459]
## [FirstOrCreate](https://github.com/go-gorm/gen#firstorcreate) 方法不支持传入参数，是否是需要更新README文档？

![image](https://user-images.githubusercontent.com/34245549/172077550-f0214e58-6217-4343-9ec8-503315e1d47c.png)

**Comment by riverchu** [comment]
你要提个PR来修吗？

**Comment by wulorn** [comment]
> 

可以的。补充一个问题 ：有什么方式可以支持在`FirstOrCreate`里面传参呢？ 这样能与gorm使用保持一致 。能更容易的实现[Upsert](https://gorm.io/zh_CN/docs/create.html#upsert)
