### ISSUE TITLE
能否自定义field类型，现在expr是私有的，没办法拓展

### ISSUE THREAD

**Issue by szmgfcsp** [go-gorm/gen#460]
## Describe the feature
框架的expr(field/expr.go)没办法拓展，如果能开放就好了，然后大家可以一起来丰富类型, @riverchu 
``` go
type expression interface{}

type sql string

func (e sql) String() string { return string(e) }

type expr struct {
	col clause.Column

	e         clause.Expression
	buildOpts []BuildOpt
}
```
目前我想实现自己的类型应该怎么做，不然全是 field.Field，只能用过定义接口来实现 ApplyInterface 来实现，比较麻烦

**Comment by szmgfcsp** [comment]
> 自定义类型实现这个接口就行 type ScanValuer interface { Scan(src interface{}) error // sql.Scanner Value() (driver.Value, error) // driver.Valuer } Scan查询需要 Value修改或做条件比如eq这类操作需要 可以按需实现

实现了的，只不过 生成的代码gen 还是 field.Field，我先变成自己的field 好拓展

**Comment by crazy6995** [comment]
> 

附议！

**Comment by riverchu** [comment]
这个类型是刻意限制了不可以自己实现的，是为了防止一些非预期的使用造成安全风险，不过扩展性我们会认真考虑的

**Comment by szmgfcsp** [comment]
> 这个类型是刻意限制了不可以自己实现的，是为了防止一些非预期的使用造成安全风险，不过扩展性我们会认真考虑的 好起待此拓展性能开放，继续支持gen
