### ISSUE TITLE
生成model时指定fieldname生成的name有ID时会失效

### ISSUE THREAD

**Issue by Sun-Jingjun** [go-gorm/gen#461]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/55533902/172359724-70c85a5d-99a5-423d-882d-c47cb77ec7ec.png">
背景是需要修改生成的model的字段名称，这里的EmployeeID不符合预期，需要修改为EmployeeId，找了api，使用gen.FieldRename来进行修改名称，改成xxx的时候，是可以生效的
<img width="831" alt="image" src="https://user-images.githubusercontent.com/55533902/172360092-2ec407e8-0028-4068-b2c6-3334ad8ad0a8.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/55533902/172360118-b6613ed2-487a-4dda-921a-149e004275eb.png">

但是如果修改成这种，则会失效
<img width="867" alt="image" src="https://user-images.githubusercontent.com/55533902/172360251-e4e4c0f3-b7d5-42a3-9fc6-1574ab169870.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/55533902/172360278-6df03371-cc14-48d8-bf7b-2891f3649c5e.png">

**Comment by riverchu** [comment]
不是失效，是对于Field名字有规范，ID就是要全大写的

**Comment by Sun-Jingjun** [comment]
感谢回复，这里和proto生成的规范不太兼容，proto生成的是这种EmployeeId。导致使用fieldmask的时候有点问题

**Comment by riverchu** [comment]
https://github.com/go-gorm/gorm/blob/master/schema/naming.go 这个确实没有办法，gen和gorm遵循的是golang的命名规范，不太好改
