### ISSUE TITLE
暴露 Query 的 gorm.DB

### ISSUE THREAD

**Issue by sswanv** [go-gorm/gen#465]
遇到了一个 gen 不支持的 sql 语句，想用 gorm.DB 来执行，有把 db 暴露出来的打算吗？

```golang
type Query struct {
	db *gorm.DB
        # ...
}
```

**Comment by riverchu** [comment]
实现了`UnderlyingDB`方法，不过定位类似go的`unsafe`模块，不建议使用，因为有可能会引入SQL注入之类的安全风险
