### ISSUE TITLE
Data Mapping 提供针对某个字段的映射设定。

### ISSUE THREAD

**Issue by crazy6995** [go-gorm/gen#471]
希望提供针对某个字段的映射设定。

需求如下：

```go
type Model struct {
    ID                                    int64 `gorm:"id";primaryKey`
    Test                                 int64 `gorm:"test"`
    Version optimisticlock.Version `gorm:"version"` // 乐观锁
}
```

乐观锁字段为 version ，数据库（MYSQL）中类型为 bigint

现有的映射关系仅是通过数据类型进行映射，所有的bigint均会映射为int64

不知道怎么独立对某个字段进行映射。

**Comment by riverchu** [comment]
https://github.com/go-gorm/gen#data-mapping 看下这个？

**Comment by crazy6995** [comment]
了解了，`g.GenerateModel("xxx")` 当中添加 `gen.FieldType("version", "optimisticlock.Version") 即可满足要求。

**Comment by crazy6995** [comment]
> https://github.com/go-gorm/gen#data-mapping 看下这个？

这个不行，它会将所有的 bigint 全部替换为 optimisticlock.Version
