### ISSUE TITLE
Add mode for exporting Do models (Default inside models folder)

### ISSUE THREAD

**Issue by alfarih31** [go-gorm/gen#479]
## Describe the feature

I add new mode for Exporting generated Do models. Currently all of the models is un-exported (uncapitalized).

## Motivation

On some circumstance the Do models (Default inside models folder) need to be used on other packages. Hence, it need to be exported

**Comment by riverchu** [comment]
fix in #492, try generate mode `WithQueryInterface`

**Comment by alfarih31** [comment]
@riverchu I've tried #492  but it's not what i expected. What I need is `Fields` of the models `struct`. Here is an example use case with exported Do models. Consider the model `struct` inside the `models` folder is exported like this:

```golang
type News struct {
	NewsDo

	ALL          field.Field
	ID           field.Int64
	Slug         field.String
	Title        field.String
	Sort         field.Int64
	CategoryID   field.Int32
	Content      field.String
	StatusID     field.Int32
	Metadata     field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	ModifiedBy   field.String
	Version      field.Int64
	NewsCategory NewsBelongsToNewsCategory

	Tags NewsManyToManyTags

	fieldMap map[string]field.Expr
}
```

By accessing `Fields` of `News` struct, I can use this struct like this:
<img width="698" alt="Screen Shot 2022-06-29 at 14 48 06" src="https://user-images.githubusercontent.com/36299112/176381691-7faf0868-ce1a-4d90-9b31-2b6c604fa69c.png">

**Comment by riverchu** [comment]
why do you want to pass `models.News`, it just a receiver for `CRUD` methods and fields, it make no sense to pass it. It's ok for you to call it directly like `query.News.ID.Eq(...)` (under `WithDefaultQuery` mode)

**Comment by ZheruiL** [comment]
> why do you want to pass `models.News`, it just a receiver for `CRUD` methods and fields, it make no sense to pass it. It's ok for you to call it directly like `query.News.ID.Eq(...)` (under `WithDefaultQuery` mode)

Hi @ tr1v3r, how can I add a custom method in this mode? For example, in DefaultQuery:
```go
func (p *productDo) PreloadAll() *productDo {
	return p.Preload(field.Associations)
}

// I can call this method
Q.Product.WithContext(ctx).PreloadAll().Find()
```

In QueryInterface mode: 
```go
func (p *productDo) PreloadAll() IProductDo {
	return p.Preload(field.Associations)
}

// I can not find this method anymore as WithContext(ctx) returns an interface
Q.Product.WithContext(ctx).
```
