### ISSUE TITLE
A way to solve `.In(values ...driver.Valuer)` with column type

### ISSUE THREAD

**Issue by Trim21** [go-gorm/gen#481]
## Describe the feature

I'm using a type definition in column.

Which look like this:

```golang
type Subject struct {
	ID model.SubjectID `gorm:"..."`
}
```

and `model.SubjectID` is a `driver.Valuer`

Then in dao, I want to select with sql `in`, so i need to do this:

```golang
var q *query.Query
q.Subject.WithContext(ctx).Where(q.Subject.ID.In(ids...)).Find()
```

This method has a signature of this

```
// In ...
func (field Field) In(values ...driver.Valuer) Expr {
	return expr{e: clause.IN{Column: field.RawExpr(), Values: field.toSlice(values...)}}
}
```

which means in this case, it doesn't fit the type requirements:

```golang
func (r mysqlRepo) GetByIDs(ctx context.Context, ids ...model.SubjectID) {
	records, err := r.q.Subject.WithContext(ctx).Joins(r.q.Subject.Fields).Where(r.q.Subject.ID.In(ids...)).Find()
    ...
}
```

and ids has a type `[]model.SubjectID` which doesn't work with `[]driver.Valuer`

I know it's a problem from go type system, But I wonder if there could be a way to solve this with a new field method?

**Comment by riverchu** [comment]
If `GEN` provides a method to solve it, it will inevitably call package `reflect`'s methods and will make some unnecessary complexity, so we prefer to let the user implement the method to do this type conversion, which will have better performance in terms of efficiency and stability.
