### ISSUE TITLE
为什么所有的日志消息都打印了两次？

### ISSUE THREAD

**Issue by Trim21** [go-gorm/gen#489]
## Your Question

https://github.com/go-gorm/gen/blob/8012a3fbfac22dcb6d868528f93234d3454c6a36/generator.go#L256-L261

**Comment by idersec** [comment]
你是不是修改了把GORM logger的 logLevel，默认是不会打印info日志的。https://gorm.io/docs/logger.html#content-inner

**Comment by Trim21** [comment]
谢谢
