### ISSUE TITLE
gentool 在带有-的目录下不能正常gen

### ISSUE THREAD

**Issue by kurimi1** [go-gorm/gen#491]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

log:
2022/06/25 06:38:07 got 16 columns from table <kcdj>
2022/06/25 06:38:07 Start generating code.
2022/06/25 06:38:07 generate model file(table <kcdj> -> {model.Kcdj}): /root/model/kcdj.gen.go

2022/06/25 06:38:07 /root/go/pkg/mod/gorm.io/gen@v0.3.8/generator.go:503
[warn] parse model pkg path fail: err: exit status 1: stderr: go: go.mod file not found in current directory or any parent directory; see 'go help modules'
Format fail: 6 /root/L-GIS/kcdj.gen.go:6:10: expected ';', found '-'
1 // Code generated by gorm.io/gen. DO NOT EDIT.
2 // Code generated by gorm.io/gen. DO NOT EDIT.
3 // Code generated by gorm.io/gen. DO NOT EDIT.
4 
5 package L-GIS
6 
7 import(
8       "context"
9       "database/sql"
10      "strings"
11 
2022/06/25 06:38:07 generate query file: /root/L-GIS/kcdj.gen.go

2022/06/25 06:38:07 /root/go/pkg/mod/gorm.io/gen@v0.3.8/generator.go:248
[error] generate query code fail: cannot format file: /root/L-GIS/kcdj.gen.go:6:10: expected ';', found '-'
panic: generate query code fail

goroutine 1 [running]:
gorm.io/gen.(*Generator).Execute(0xc0004a0000)
        /root/go/pkg/mod/gorm.io/gen@v0.3.8/generator.go:249 +0x15a
main.main()
        /root/go/pkg/mod/gorm.io/gen@v0.3.8/tools/gentool/gentool.go:201 +0x2fd

**Comment by defp** [comment]
类似 

```
 ~/Projects/nocode/gorm-nocode-demo/ ./gorm-nocode-demo
2022/06/27 11:47:48 got 30 columns from table <bdl_doctor>
2022/06/27 11:47:48 Start generating code.
2022/06/27 11:47:48 generate model file(table <bdl_doctor> -> {model.BdlDoctor}): /Users/lidashuang/Projects/nocode/model/bdl_doctor.gen.go

2022/06/27 11:47:48 /Users/lidashuang/.asdf/installs/golang/1.18/packages/pkg/mod/gorm.io/gen@v0.3.8/generator.go:503
[warn] parse model pkg path fail: err: exit status 1: stderr: go: go.mod file not found in current directory or any parent directory; see 'go help modules'
2022/06/27 11:47:48 Generate code done.

```

**Comment by riverchu** [comment]
看的不是很清楚，是不是相对路径有问题？直接跳出project目录了？跟"-"没有关系？

**Comment by upkit** [comment]
![image](https://github.com/go-gorm/gen/assets/31933684/6c1ee682-ee67-442b-8a68-a7c9efecb4aa)
![image](https://github.com/go-gorm/gen/assets/31933684/cd92aadc-0d60-49da-beca-91de29579555)
确实目录有-就会报错，改掉就正常了
