### ISSUE TITLE
install failed on windows

### ISSUE THREAD

**Issue by leyou240** [go-gorm/gen#503]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
windows will return err.

` go install gorm.io/gen/tools/gentool@latest

  github.com/mattn/go-sqlite3

cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%`

**Comment by riverchu** [comment]
emmm，maybe u should install `gcc` first
