### ISSUE TITLE
期望增加配置分片参数、支持分表模型

### ISSUE THREAD

**Issue by wulorn** [go-gorm/gen#507]
## 水平分表创建模型需要建立多张表，期望收敛在一个模型中，能定制模型的TableName

###DDL
```SQL
CREATE TABLE IF NOT EXISTS `mytables_[0-127]` (
	`ID` int(11) NOT NULL," 
	`username` varchar(16) DEFAULT NULL,
	`age` int(8) NOT NULL," 
	`phone` varchar(11) NOT NULL,
	INDEX `idx_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

### 生成模型
```
g.GenerateModelAs("mytables_0", "Mytable")
```
### model
```
package model

const TableNameMytable = "mytables_0"

// Mytable mapped from table <mytables_[0-127]>
type Mytable struct {
	ID       int32   `gorm:"column:ID;type:int(11);not null" json:"ID_example"`
	Username *string `gorm:"column:username;type:varchar(16);index:idx_username,priority:1;default:NULL" json:"username_example"`
	Age      int32   `gorm:"column:age;type:int(8);not null" json:"age_example"`
	Phone    string  `gorm:"column:phone;type:varchar(11);not null" json:"phone_example"`
}

// TableName Mytable's table name
func (*Mytable) TableName() string {
	return TableNameMytable
}

```

## 期望在模板中增加一个分片参数、通过分片参数可以自定义TableName()方法。
![image](https://user-images.githubusercontent.com/34245549/176849947-e8fa85c2-e509-420a-87ff-598bd438b799.png)

![image](https://user-images.githubusercontent.com/34245549/176852782-4470b717-ac41-478a-be49-f338ede72196.png)

## 预期想要生成的模型
```
package model

import (
	"fmt"
)

const TableNameMytable = "mytables"
const TableNameMytableShardNumber = 128

// Mytable mapped from table <mytables_[0-127]>
type Mytable struct {
	ID       int32   `gorm:"column:ID;type:int(11);not null" json:"ID_example"`
	Username *string `gorm:"column:username;type:varchar(16);index:idx_username,priority:1;default:NULL" json:"username_example"`
	Age      int32   `gorm:"column:age;type:int(8);not null" json:"age_example"`
	Phone    string  `gorm:"column:phone;type:varchar(11);not null" json:"phone_example"`
}

// TableName Mytable's table name
func (*Mytable) TableName(id int32) string {
	return TableNameMytable + fmt.Sprintf("_%v", id%TableNameMytableShardNumber) // 自定义方法
```

**Comment by qqxhb** [comment]
TableName是gorm那边的接口Tabler方法不支持入参
可以看下这样的能解决你的问题：
假如是user表
生成的时候只生成user_0的model，然后在你具体用的时候指定表名称
dal.User.Table("user_1").WithContext(ctx).Where(xxx)

**Comment by qqxhb** [comment]
TableName是gorm那边的接口Tablerd的方法不支持入参
可以看下这样的能解决你的问题：
假如是user表
生成的时候只生成user_0的model，然后在你具体用的时候指定表名称
dal.User.Table("user_1").WithContext(ctx).Where(xxx)

**Comment by wulorn** [comment]
> 

是的 在使用时需要手动传入table。 
不过因为是生成的模型，期望能在模板中声明分片的信息，且不生成默认的TableName。
所以希望生成一个定制的分片获取表名方法，看起来会比较直观

**Comment by qqxhb** [comment]
@wulorn 了解了。这个你可以自定义一个方法，名字需要改下，比如TableNameByShard(shard int)
然后生成user_0的model时给他绑定上这个方法,类似这样
g.GenerateModel("user").AddMethod(user.TableNameByShard)
具体可以参考下文档[generate-model](https://github.com/go-gorm/gen#generate-model)
> Generate model bind custom method

**Comment by wulorn** [comment]
> 
是否可以增加一个参数、可以控制不生成默认TableName以及常量的表名

**Comment by riverchu** [comment]
什么场景下要用这个？

**Comment by wulorn** [comment]
> 什么场景下要用这个？
在水平分表的时候，期望通过diy method 生成TableName方法和常量表名

**Comment by wulorn** [comment]
> 在水平分表的时候，期望通过diy method 生成TableName方法和常量表名



> 什么场景下要用这个？



> 什么场景下要用这个？
在水平分表的时候，期望通过diy method 生成TableName方法和常量表名

**Comment by wulorn** [comment]
> 
在水平分表的时候，期望通过diy method 生成TableName方法和常量表名

**Comment by gh-zhangpeng** [comment]
我下午研究了下。
1. 同一组表只生成一个结构体，应该还比较好实现。
只需要修改 `generator.go` 中的 `generateModelFile` 函数就可以了。比如在 `473` 行后，根据分表逻辑修改 `FileName`、`ModelStructName`、`QueryStructName`、`TableName` 的值。
2. 自动添加一个用于获取表名的函数比较麻烦。我感觉这玩意应该强关联业务，所以做通用确实比较繁琐。如果非要做的话，那需要在某个阶段指定某个表是根据哪个字段进行的分表。可能就需要一个配置的过程了。感觉不是一个通用工具的范畴了～

**Comment by gh-zhangpeng** [comment]
> @wulorn 了解了。这个你可以自定义一个方法，名字需要改下，比如TableNameByShard(shard int) 然后生成user_0的model时给他绑定上这个方法,类似这样 g.GenerateModel("user").AddMethod(user.TableNameByShard) 具体可以参考下文档[generate-model](https://github.com/go-gorm/gen#generate-model)
> 
> > Generate model bind custom method

我觉得这个也挺复杂的，毕竟不是所有表的分表逻辑都相同。所以需要为每个需要分表的结构体添加不同的 `TableNameByShard` 函数。

我觉得是不是可以考虑添加一个 TableNum() 的函数，用于获取当前表共分了多少张（通过读数据库就可以自动算出），然后写一个 `scope`，传入 `xxModel.TableName()`、`xxModelID`，在 `scope` 内使用 `xxModelID` % `xxModel.TableNum()`，然后就得到数据实际所在的表了。

**Comment by gh-zhangpeng** [comment]
我这这边完成了一版，根据同类型表总数判断，是否添加 `TableCount` 函数的代码，希望大佬能帮忙 `review` 下。谢谢～
