### ISSUE TITLE
能像ent那样支持自定义的template吗

### ISSUE THREAD

**Issue by fitan** [go-gorm/gen#513]

**Comment by riverchu** [comment]
你是说这个吗？https://github.com/go-gorm/gen#diy-method

**Comment by fitan** [comment]
> 你是说这个吗？https://github.com/go-gorm/gen#diy-method

不是。类似这种https://entgo.io/docs/templates
暴露出内部的模板数据，引入外部的template。这样可以生成简单的resful或者[GraphQL](https://entgo.io/docs/graphql)

**Comment by riverchu** [comment]
这种目前不支持
