### ISSUE TITLE
当查询条件需要使用sql中的字段时如何写

### ISSUE THREAD

**Issue by dinofei** [go-gorm/gen#516]
select * from work_orders where updated_at >= DATE_ADD(`updated_at`,INTERVAL 1000 MICROSECOND)

**Comment by riverchu** [comment]
try https://github.com/go-gorm/gen#diy-method

**Comment by dinofei** [comment]
> try https://github.com/go-gorm/gen#diy-method

业务场景可能还会增加其他的where条件, 如果使用diy-method where的数量就固定了, 我可不可以把这个where写成一个自定义的gen.Condition , 然后可以和其他的where随意组装

**Comment by riverchu** [comment]
只是where条件的话是可以叠加的
```go
    // where("name=@name and age=@age")
    SimpleFindByNameAndAge(name string, age int) (gen.T, error)
```

**Comment by dinofei** [comment]
好的 我再自己尝试一下 谢谢

**Comment by riverchu** [comment]
关于这个issue还有什么疑问吗？
