### ISSUE TITLE
`go install gorm.io/gen/tools/gentool@latest` is currently having an issue

### ISSUE THREAD

**Issue by jjalfaro9** [go-gorm/gen#522]
`go install gorm.io/gen/tools/gentool@latest`
produces the following error:
```
go: downloading gorm.io/gen v0.3.10
go: gorm.io/gen/tools/gentool@latest (in gorm.io/gen@v0.3.10):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Looks like https://github.com/go-gorm/gen/pull/484 introduced the replace in go.mod.
#484 was a part of the https://github.com/go-gorm/gen/releases/tag/v0.3.9 release.

**Comment by riverchu** [comment]
try `go install gorm.io/gen/tools/gentool@7d4e27eab3b36f3c2079d405492944bd060c26d1` temporarily. Next release will fix this bug
