### ISSUE TITLE
Missing `defineMethodStruct` on generate modes `WithoutContext`

### ISSUE THREAD

**Issue by alfarih31** [go-gorm/gen#525]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

Maybe you forgot to put `defineMethodStruct` to the template `TableQueryStruct` as the template for the generate mode `WithoutContext`. Check the template [here](https://github.com/go-gorm/gen/blob/19c330c0a288ae440d6d8efa551f5caf7b2d60b0/internal/template/struct.go#L10)

**Comment by riverchu** [comment]
fix on #524

**Comment by riverchu** [comment]
same with #523
