### ISSUE TITLE
生成对应表的query时，少了 type xxxDo struct{ gen.DO }

### ISSUE THREAD

**Issue by zhoushun5678** [go-gorm/gen#528]
g.ApplyBasic(g.GenerateModel("user"))
生成的文件dal/query/user.gen.go中发现少了一行类型定义： type userDo struct{ gen.DO }。
这句没有生成不知道为啥
环境：go version go1.15 darwin/amd64
gorm.io/gen v0.3.10

**Comment by goodking-bq** [comment]
同样的问题

**Comment by zhoushun5678** [comment]
> 同样的问题

我重新试了，又可以了😊

**Comment by riverchu** [comment]
跟 #523 一样的问题，已经决解了，我一会儿发个新版吧

**Comment by riverchu** [comment]
拉一下v0.3.11试一下吧

**Comment by zhoushun5678** [comment]
> 拉一下v0.3.11试一下吧

可以了，感谢。
