### ISSUE TITLE
export.go 中暴露了type FieldOpt model.FieldOpt 但是沒有 type Field model.Field，这样FieldOpt外部不是还是无法定义吗？

### ISSUE THREAD

**Issue by Esp9527** [go-gorm/gen#532]

**Comment by riverchu** [comment]
具体的option类型在这里，暂时没有让外部定义内容的打算，写在export.go是为了当类型去使用的
https://github.com/go-gorm/gen/blob/9b0e713c0dfcadf9b0deb4dbbe69c5605ba4dc35/field_options.go#L17-L226

**Comment by Esp9527** [comment]
哦哦， 谢谢, 利用field_options中的FieldNewTag,  也可以实现我的需求， 就是要GenerateModel同一个表两次
