### ISSUE TITLE
如何在事务中删除关联的行

### ISSUE THREAD

**Issue by leeming87v5** [go-gorm/gen#537]
## Your Question
比如现在我有这么两个表：
```golang
type User struct {
    ID                   int	
    UserInfo             UserInfo
    CreatedAt            time.Time
    UpdatedAt            time.Time
}

type UserInfo struct {
    ID           int
    UserID       int
    DisplayName  string
    Address      string
    Age          int
    CreatedAt    time.Time
    UpdatedAt    time.Time
}

```
我需要在`事务中`删除`User`及其关联的`UserInfo`，代码需要怎么写呢？
下面👇这个代码只会删除掉`User`，但`UserInfo`没有删除
```golang
q := query.Use(db)

q.Transaction(func(tx *query.Query) error {
  if _, err := tx.User.WithContext(ctx).Where(tx.User.ID.Eq(100)).Delete(); err != nil {
    return err
  }
  return nil
})
```
另外，如果在删除的时候，需要根据 join 后的过滤条件进行删除（这里我需要删除的是 user），那么，根据下面的代码但生成的 sql 会报错，正确的做法是什么？
```golang
q := query.Use(db)

// 这里生成的 sql 有误，大概长这样:
// DELETE FROM `users` INNER JOIN `user_infos` ON `user_infos`.`user_id` = `users`.`id` WHERE `user_infos`.`id` = 100 
q.Transaction(func(tx *query.Query) error {
	if _, err := tx.User.WithContext(ctx).
		Join(tx.UserInfo, tx.UserInfo.UserID.EqCol(tx.User.ID)).
		Where(tx.UserInfo.ID.Eq(100)).
		Delete(); err != nil {
		return err
	}
	return nil
})

```

**Comment by qqxhb** [comment]
q.Transaction(func(tx *query.Query) error {
  if _, err := tx.User.WithContext(ctx).Where(tx.User.ID.Eq(100)).Delete(); err != nil {
    return err
  }
 if _, err := tx.UserInfo.WithContext(ctx).Where(tx.UserInfo.ID.UserID(100)).Delete(); err != nil {
    return err
  }
  return nil
})
@leeming87v5 这样就行？

**Comment by riverchu** [comment]
用的是MySQL吗？

**Comment by riverchu** [comment]
MySQL不支持DELETE配合JOIN吧？方便的话写个可以执行的SQL？

**Comment by leeming87v5** [comment]
> ```go
> DELETE FROM `users` INNER JOIN `user_infos` ON `user_infos`.`user_id` = `users`.`id` WHERE `user_infos`.`id` = 100
> ```
预想的可执行 sql 大概这样：
```sql
DELETE `user_infos` FROM `users` INNER JOIN `user_infos` ON `user_infos`.`user_id` = `users`.`id` WHERE `user_infos`.`id` = 100
```

**Comment by leeming87v5** [comment]
> MySQL不支持DELETE配合JOIN吧？方便的话写个可以执行的SQL？

预想的可执行 sql 大概这样：
```sql
DELETE `user_infos` FROM `users` INNER JOIN `user_infos` ON `user_infos`.`user_id` = `users`.`id` WHERE `user_infos`.`id` = 100
```

**Comment by riverchu** [comment]
这个不符合SQL的语法

**Comment by leeming87v5** [comment]
> 这个不符合SQL的语法

那用 gen 有什么推荐的办法来达到相同的效果吗？

**Comment by qqxhb** [comment]
https://gorm.io/docs/associations.html#Delete-with-Select
@leeming87v5 看下这个

**Comment by leeming87v5** [comment]
> https://gorm.io/docs/associations.html#Delete-with-Select @leeming87v5 看下这个

这个是 gorm 的用法，当初就是不想手写各种字符串才用的 gen，现在着实不想回去

**Comment by riverchu** [comment]
什么ORM都跳不出SQL语法的限制，这种需求只能分开成查询和删除两个操作了，最简单也要用Pluck的方式把目标的主键用数组的形式查出来，然后拿去Delete

**Comment by leeming87v5** [comment]
> 什么ORM都跳不出SQL语法的限制，这种需求只能分开成查询和删除两个操作了，最简单也要用Pluck的方式把目标的主键用数组的形式查出来，然后拿去Delete

有没有可能，未来把这种功能内建到 gen？一方面，感觉内建之后写起来更加流畅；另一方面，像现在我这样子写 gen， 会生成出来错误的 sql ，会让我有点意外

**Comment by riverchu** [comment]
> > https://gorm.io/docs/associations.html#Delete-with-Select @leeming87v5 看下这个
> 
> 这个是 gorm 的用法，当初就是不想手写各种字符串才用的 gen，现在着实不想回去

gen生成的代码是侧重和数据库同步的，这种关联删除的方式用的字段名和关联关系都不是数据库里实际存在的，所有要使用的话需要新建对应的字段来指向代码中的字段，具体来说就是想删除关联的`UserInfo`的话，需要用`Select(field.NewStirng("","UserInfo"))`这种方式来前置指定

**Comment by riverchu** [comment]
> > 什么ORM都跳不出SQL语法的限制，这种需求只能分开成查询和删除两个操作了，最简单也要用Pluck的方式把目标的主键用数组的形式查出来，然后拿去Delete
> 
> 有没有可能，未来把这种功能内建到 gen？一方面，感觉内建之后写起来更加流畅；另一方面，像现在我这样子写 gen， 会生成出来错误的 sql ，会让我有点意外

你的预期SQL就是不符合语法的，这种方式是没有办法内建的，不过一些类似语法糖的功能会考虑支持
