### ISSUE TITLE
帮忙看下我这样写为啥不行呢

### ISSUE THREAD

**Issue by zhoushun5678** [go-gorm/gen#544]
tb := query.Use(db).User
do := tb.WithContext(context.Background())
do.Where(tb.ID.Eq(10000))
do.Find()
你好，请问下：我这样写，where条件怎么不生效呢

**Comment by riverchu** [comment]
要写成链式的
```go
do.Where(tb.ID.Eq(10000)).Find()
```
或者
```go
do = do.Where(tb.ID.Eq(10000))
do.Find()
```
