### ISSUE TITLE
Insert clause is banned error

### ISSUE THREAD

**Issue by gozelus** [go-gorm/gen#545]
I got a error `clause INSERT is banned` when I try to use `insert ignore`, there is my code:
```go
// db is postgres
q := dal.Use(n.data.DB(ctx)).Model
if err := q.WithContext(ctx).Clauses(clause.Insert{Modifier: "IGNORE"}).Create(waitToCreate...); err != nil {
	return nil, err // will return err : clause INSERT is banned
}
```
 So the `insert ignore` doesn't support in `gen` now?

**Comment by riverchu** [comment]
Yeah, clause.Insert's field `Table` may contains raw table name which may lead to SQL injection vulnerability, so we banned it, i will create another PR to check it with more detail
