### ISSUE TITLE
能否支持对decimal的支持，以及默认*gorm.DB

### ISSUE THREAD

**Issue by hinego** [go-gorm/gen#555]
一，希望支持可选将decimal类型的数据库字段映射到 github.com/shopspring/decimal （默认还是映射到float64 但是可以使用命令例如 --useDecimal=1 来启用将其映射到 github.com/shopspring/decimal）
二，默认*gorm.DB的支持
```
当前写法：需要手动使用use函数传入database.DB
test.Use(database.DB).Category.WithContext(context.Background()).Where().First()
希望写法：默认指定为database.DB
test.Category.WithContext(context.Background()).Where().First()

如果需要指定非默认*gorm.DB时再手动传入（例如嵌套事务时）
	database.DB.Transaction(func(tx *gorm.DB) error {
		_, err := test.Use(tx).Category.WithContext(context.Background()).Where(test.Category.Status.Eq(0)).Delete()
		if err != nil {
			return err
		}
		_, err = test.Use(tx).Category.WithContext(context.Background()).Where(test.Category.Status.Eq(1)).Delete()
		return err
	})
```

**Comment by Trim21** [comment]
decimal类decimal的话可以add import path和datamap

https://github.com/go-gorm/gen#data-mapping

**Comment by qqxhb** [comment]
@hinego 可以生成代码的时候配置生成默认的query：gen.WithDefaultQuery
然后在quey下创建意义init文件，在里面初始化设置默认db，类似这样
```go
func init() {
	mysql.Init()
	SetDefault(mysql.DB(context.Background()))
}
```
使用的时候就可以直接用，不需要设置db
xxx.Category.WithContext(ctx)
xxx.User.WithContext(ctx)

**Comment by gh-zhangpeng** [comment]
> 

完整的 `SetDefault` 代码是：

```golang
query.SetDefault(preload.DB)
```

**Comment by qqxhb** [comment]
@gh-zhangpeng 
参考下 [gendemo](https://github.com/go-gorm/gendemo)

**Comment by gh-zhangpeng** [comment]
> @gh-zhangpeng 参考下 [gendemo](https://github.com/go-gorm/gendemo)

理解了，可是 `gen.go` 里应该是自动生成的代码呀，这么改完以后，是不是每次重新生成都会被覆盖掉？

**Comment by Trim21** [comment]
这个文件夹是不会被删除的，你放在另一个文件的`init`里面，不要跟生成的文件重名就可以了。

**Comment by qqxhb** [comment]
> > @gh-zhangpeng 参考下 [gendemo](https://github.com/go-gorm/gendemo)
> 
> 理解了，可是 `gen.go` 里应该是自动生成的代码呀，这么改完以后，是不是每次重新生成都会被覆盖掉？

gen.go是自动生成的没有改动，只是加了一个init文件（仅初始化db），这个不会被覆盖

**Comment by gh-zhangpeng** [comment]
> > > @gh-zhangpeng 参考下 [gendemo](https://github.com/go-gorm/gendemo)
> > 
> > 
> > 理解了，可是 `gen.go` 里应该是自动生成的代码呀，这么改完以后，是不是每次重新生成都会被覆盖掉？
> 
> gen.go是自动生成的没有改动，只是加了一个init文件（仅初始化db），这个不会被覆盖

嗯嗯，是我没有指定 `mode` 的原因，所以没有自动生成 `SetDefault` 的代码。。。
