### ISSUE TITLE
期望DO对象可以增加getDB方法

### ISSUE THREAD

**Issue by m430** [go-gorm/gen#561]
通常调用DO上下文的地方不能直接获取db对象。但是有些GORM操作暂时gen还不能满足，期望可以通过DO对象获取到db对象，进而进行GORM的操作。

**Comment by qqxhb** [comment]
@m430 有一个UnderlyingDB()方法
方便说下gen不满足的具体场景吗

**Comment by riverchu** [comment]
跳过GNE使用GORM的时候需要特别注意不要写出安全漏洞

**Comment by m430** [comment]
@qqxhb @riverchu 非常感谢2位的回复，说下我的看法。gen存在的意义是在于在GORM之上，为开发者提供了一套开箱即用的封装层，提供了很大方便，但是目前感觉GEN还没有跟GORM的能力完全对齐。比如我提了一个问题 #560 ，针对多对多自动删除关联表记录。db对象操作就可以。GEN目前还不行。

**Comment by riverchu** [comment]
一些场景的覆盖确实没有一次到位，需要慢慢在实践中发现再寻找合适的方案改造，getDB方法已经实现了，名字叫`UnderlyingDB`需要的话可以调用，不过要注意安全风险

**Comment by m430** [comment]
谢谢，我已经使用`UnderlyingDB`完成了想要的功能。这个问题我就关闭了
