### ISSUE TITLE
指定数据类型生成json标签格式

### ISSUE THREAD

**Issue by zsy619** [go-gorm/gen#576]
## 数据类型int、int64生成json标签

是否统一加上 json:"column,string" 按指定类型加上,string

**Comment by riverchu** [comment]
指定类型？比如？

**Comment by qqxhb** [comment]
@zsy619 可以用gen.FieldJSONTag或者gen.FieldJSONTagWithNS 自定 json tag

**Comment by zsy619** [comment]
比如字段类型是int\int64\int32等数字类型的，统一加上,string

**Comment by riverchu** [comment]
这个目前没有支持，确定具体字段的话可以自己用`FieldJSONTagWithNS`这个选项实现
