### ISSUE TITLE
多字段in获取不到Columns

### ISSUE THREAD

**Issue by Sun-Jingjun** [go-gorm/gen#578]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/55533902/181169001-811ed585-04db-4c72-b6b6-1fd3f0579a96.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/55533902/181169195-a32cbaba-b796-4a35-9cc2-4602b0ebe613.png">

想使用多个字段in操作，但是获取不到Columns方法，求解大佬是什么原因？

**Comment by Sun-Jingjun** [comment]
版本使用了最新的
<img width="521" alt="image" src="https://user-images.githubusercontent.com/55533902/181169781-f955f17b-bc48-47f7-88d5-cd6ab7b7c859.png">

**Comment by riverchu** [comment]
哪里找到的老文档？可以看看现在的版本，要先调用WithContext

**Comment by Sun-Jingjun** [comment]
感谢回复，问题解决了
看的gitee上的文档
https://gitee.com/gorm/gen?_from=gitee_search#%E6%A0%B9%E6%8D%AE%E4%B8%BB%E9%94%AE%E6%9F%A5%E8%AF%A2%E6%95%B0%E6%8D%AE

**Comment by riverchu** [comment]
那个落后比较多了，最好可以换到github上这个来
