### ISSUE TITLE
生成的测试用例报错

### ISSUE THREAD

**Issue by optimistic9527** [go-gorm/gen#582]
### 问题
生成的测试用例在进行批量插入的时候报错

代码如下：
![image](https://user-images.githubusercontent.com/37545032/181707938-97621b06-e472-4d25-8f03-06ac353506c3.png)
当主键是string的时候会报错

![image](https://user-images.githubusercontent.com/37545032/181708067-d4cfe511-d96d-4860-ba24-f689fc70d384.png)

**Comment by riverchu** [comment]
这个报错是数据库错误 跟orm无关了，生成的单元测试仅供参考，有需要可以自己修改。
