### ISSUE TITLE
Insert error caused by PostgreSQL default value

### ISSUE THREAD

**Issue by cachalots** [go-gorm/gen#591]
create table sql
```
create SCHEMA test;

CREATE TYPE "public".fruit_color AS ENUM ('unknown', 'red', 'green', 'orange');

create table "test"."fruits"(
  "name" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "color" "public"."fruit_color" NOT NULL DEFAULT 'unknown'::fruit_color
)
```
fruits.gen.go
```
package types

const TableNameFruit = "fruits"

// Fruit mapped from table <fruits>
type Fruit struct {
	Name  string `gorm:"column:name;type:character varying(64);default:''::character varying" json:"name"`
	Color string `gorm:"column:color;type:public.fruit_color;not null;default:'unknown'::public.fruit_color" json:"color"`
}

// TableName Fruit's table name
func (*Fruit) TableName() string {
	return TableNameFruit
}
```

name default value is `::character varying` not `empty string`.
color default value is `'unknown'::public.fruit_color` not `unknown`.

**Comment by pwnoz0r** [comment]
Ran into the same issue generating my schema from an old database. Definitely not the right way to do this, but a quick and dirty work around is replace the short statement: https://github.com/go-gorm/gen/blob/09c260fb92e462034e30824cc9e170c10f3a0fcb/internal/model/tbl_column.go#L118-L121

with:

```golang
if dtValue := c.defaultTagValue(); !isValidPriKey && c.needDefaultTag(dtValue) { // cannot set default tag for primary key
	if strings.Contains(dtValue, "::character varying") {
		dtValue = strings.Replace(dtValue, "::character varying", "", -1)
	}
	buf.WriteString(fmt.Sprintf(`;default:%s`, dtValue))
}
```

Changed the field from:
```sql
SuperCoolColumn     string `gorm:"column:timerec;default:NULL::character varying" json:"superCoolColumn"`
```
to
```sql
SuperCoolColumn     string `gorm:"column:timerec;default:NULL" json:"superCoolColumn"`
```

Inserts are now working without an issue. Would be nice to have the option to disable defaults when generating models and / or an option to disable filling in default values when executing insert statements and just let the database handle it.

**Comment by qqxhb** [comment]
```go
gen.FieldGORMTag("supercoolcolumn", func(tag field.GormTag) field.GormTag {
				tag.Set("default", "xxx") //update default tag
				//tag.Remove("default")     //remove default
				return tag
			}),
```

**Comment by mmaquevice** [comment]
Why the issue is closed? I'm having the same issue with latest version.

**Comment by van-scott** [comment]
> ```go
> gen.FieldGORMTag("supercoolcolumn", func(tag field.GormTag) field.GormTag {
> 				tag.Set("default", "xxx") //update default tag
> 				//tag.Remove("default")     //remove default
> 				return tag
> 			}),
> ```

I want you to give me the configuration, not the code. I did not find the corresponding configuration to remove the default value generated

**Comment by qqxhb** [comment]
@van-scott @mmaquevice 
The solution has already been provided, just modify or delete the default tag through configuration.
refe: [Field-Options](https://gorm.io/gen/database_to_structs.html#Field-Options)
```go
// Configure global validation

g.WithOpts(gen.FieldGORMTag("supercoolcolumn", func(tag field.GormTag) field.GormTag {
				tag.Set("default", "xxx") //modify default tag
				//tag.Remove("default")     //remove default
				return tag
			}),
)
```

**Comment by qqxhb** [comment]
@wubin1989 Excellent. This is the correct usage and very flexible settings
