### ISSUE TITLE
如何设置自定义类型与gen类型的对应

### ISSUE THREAD

**Issue by goodking-bq** [go-gorm/gen#594]
## The document you expected this should be explained

我又一个自定义类型
```
type MyTime struct {
	time.Time
}
```

然后再模型中引用：
```
type MyModel {
 gorm.Model
 SubmittedAt   *MyTime         `gorm:"column:submitted;type:datetime(6)" json:"submitted_at"` // 提交时间
}
```
然后生成
```
g.ApplyBasic(MyModel{})
```

## Expected answer
字段 *SubmittedAt* 的类型 为 *field.Field* ,我想让其为 *field.Time* 怎么设置呢？

**Comment by riverchu** [comment]
暂时不支持这种配置，但是可以先用强制类型转换来使用：`field.Time(m.SubmittedAt)`

**Comment by goodking-bq** [comment]
谢谢答复，像这种配置有没有开发计划呢。

**Comment by shuqingzai** [comment]
同样的问题
