### ISSUE TITLE
Incompatible comment format 

### ISSUE THREAD

**Issue by wmh** [go-gorm/gen#599]
**gen** produce field comment as below:

```
Field1      *string    `gorm:"column:field1;type:varchar(10)" json:"field1"` // this is field1 desc
```

but gorm migration has different definition as below:

```
Field1      *string    `gorm:"column:field1;type:varchar(10);comment:this is field1 desc" json:"field1"`
```

Looking forward to see the solution. Thanks.

**Comment by riverchu** [comment]
it is as expected.we do not have plan to change it.

**Comment by wmh** [comment]
but how can I use this for migration?

**Comment by riverchu** [comment]
We do not recommend using generated structures to migrate, it may lead to info miss(index or else) and incompatible between different types of database,
You can use DDL to create tables

**Comment by qqxhb** [comment]
#784
