### ISSUE TITLE
field.OrderExpr interface 可以合并到 field.Expr interface

### ISSUE THREAD

**Issue by canuran** [go-gorm/gen#617]
源自代码：`Order(call.ErrQPS.Avg().DivCol(call.QPSAvg.Avg()).(field.Field).Desc())` 的思考
可以计算值的表达式应该都可以排序，无须再断言为 field.Field 或 field.OrderExpr

**Comment by defp** [comment]
GetFieldByName 也只返回field.OrderExpr类型的， field.Field 拿不到

**Comment by riverchu** [comment]
> GetFieldByName 也只返回field.OrderExpr类型的， field.Field 拿不到

只能返回通用的接口类型，需要具体的类型可以用类型断言

**Comment by canuran** [comment]
详见：https://github.com/go-gorm/gen/issues/723
