### ISSUE TITLE
是否支持通过ctx来确定tablename

### ISSUE THREAD

**Issue by notech** [go-gorm/gen#622]
## 是否支持通过ctx来确定tablename

gorm的tablename方法 不能定义参数， 对于 多租户系统来说， 通常会使用基于schema隔离的方式，如PGSQL，中 tenant_schema.tablename. 这就依赖ctx传入对应的 租户ID，  这种方式在构建 连接查询时十分有必要。

**Comment by gh-zhangpeng** [comment]
感觉这个是个业务上的需求，可以通过动态名实现吧？
