### ISSUE TITLE
Find method can return slice of structs or pointers

### ISSUE THREAD

**Issue by ddman** [go-gorm/gen#642]
## Describe the feature

Some libraries accept slice of structs and some use slice of pointers, but find method can only generate slice of pointers.

hopefully the return value can be changed at configuration or execution stage.

**Comment by qqxhb** [comment]
@ddman #261

**Comment by luisescotob** [comment]
What was the resolution on this ? 

Is there any way i can set a configuration for it to not generate only a slice of pointers for the return type ?
