### ISSUE TITLE
是否可以支持只生成model file或者query file的选项？我只想根据model文件生成query文件，不想重新生成model。

### ISSUE THREAD

**Issue by verson1** [go-gorm/gen#650]
// Execute generate code to output path
func (g *Generator) Execute() {
	g.info("Start generating code.")

	if err := g.generateModelFile(); err != nil {
		g.db.Logger.Error(context.Background(), "generate model struct fail: %s", err)
		panic("generate model struct fail")
	}

	if err := g.generateQueryFile(); err != nil {
		g.db.Logger.Error(context.Background(), "generate query code fail: %s", err)
		panic("generate query code fail")
	}

	g.info("Generate code done.")
}

**Comment by verson1** [comment]
// Execute generate code to output path
func (g *Generator) Execute() {
	g.info("Start generating code.")

	if err := g.generateModelFile(); err != nil {
		g.db.Logger.Error(context.Background(), "generate model struct fail: %s", err)
		panic("generate model struct fail")
	}

	if err := g.generateQueryFile(); err != nil {
		g.db.Logger.Error(context.Background(), "generate query code fail: %s", err)
		panic("generate query code fail")
	}

	g.info("Generate code done.")
}

**Comment by qqxhb** [comment]
@verson1 参考[gen](https://gorm.io/gen/index.html)，类似这样直接传你的model就行`g.ApplyBasic(model.User{})`

**Comment by verson1** [comment]
使用g.ApplyBasic(model.User{})生成query的时候怎么去掉表前缀
