### ISSUE TITLE
update使用迷惑

### ISSUE THREAD

**Issue by optimistic9527** [go-gorm/gen#655]
## Your Question
比如我现在有 id，name，name_test字段
我如何实现 update xxx set name = name_test where id=xxx; 更新的数据来自于另外一个字段怎么做？

**Comment by qqxhb** [comment]
@optimistic9527 `UpdateSimple(dal.XXX.Name.SetCol(dal.XXX.NameTest))`

**Comment by optimistic9527** [comment]
> SetCol

谢谢
