### ISSUE TITLE
转化structModelName问题

### ISSUE THREAD

**Issue by huqiuyun** [go-gorm/gen#659]
有一个表叫： tb_XXX_data
通过工具转化后，type TbXXXdatum struct{
}
通过代码看到，有一个正则表达式 {"([ti])a$", "${1}um"},
把 tbXXXData  变成TbXXXDatum 不知道，是不是这里引起，为什么会改变呢？

**Comment by riverchu** [comment]
底层用的是这个单复数转换 https://github.com/jinzhu/inflection

**Comment by gh-zhangpeng** [comment]
> 底层用的是这个单复数转换 https://github.com/jinzhu/inflection

对对对，昨天看到这个库，感觉贼帅。
