### ISSUE TITLE
与gorm v1.24.0与dbresolver v1.2.3 冲突，项目不能编译通过

### ISSUE THREAD

**Issue by zsy619** [go-gorm/gen#663]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

详情查询：
https://github.com/go-gorm/dbresolver/issues/84

**Comment by zsy619** [comment]
@jinzhu 哥们，什么时候进行修订，急等

**Comment by jinzhu** [comment]
你可以自己直接更新项目的 go mod 的，没必要等 gen 更新依赖
