### ISSUE TITLE
能不能把query里面的字段生成分离出来

### ISSUE THREAD

**Issue by Carlos-Yuan** [go-gorm/gen#674]
![image](https://user-images.githubusercontent.com/53415158/195504151-11b8dc6d-c1b4-4432-9633-a6221785c989.png)
生成可导出的，现在没法导出，这些字段能统一方法初始化。

**Comment by qqxhb** [comment]
@Carlos-Yuan 没太懂，详细描述下？

**Comment by Carlos-Yuan** [comment]
找到了其他方式，暂时不用了
