### ISSUE TITLE
使用find获取model切片，如何只想拿到model中某一列用作子查询该怎么做

### ISSUE THREAD

**Issue by Sun-Jingjun** [go-gorm/gen#683]

**Comment by Sun-Jingjun** [comment]
现在有一个场景要将查询的结果用作子查询，但是子查询中find直接返回了model切片，但是我只想要其中的id列表，因为在主查询中会这样写
... in(子查询返回的id列表)

求助下该如何写

**Comment by qqxhb** [comment]
@Sun-Jingjun [SubQuery](https://gorm.io/gen/query.html#SubQuery)
