### ISSUE TITLE
请求支持每张表生成的都到单独的目录

### ISSUE THREAD

**Issue by solarhell** [go-gorm/gen#693]
## Describe the feature
支持配置每张表生成到单独的目录，形如 `/query/user/...go`, `/query/company/...go`

## Motivation
简单清晰

想通过 `gen.GenerateAllTable()` 来range了实现，但是返回的结果是个interface，而且实际的类型是个internal的struct。

**Comment by JasonTangJun** [comment]
generate后的类型是internal，想用这个类型做些额外的操作都不行，不明白为什么要将这个返回的类型放到internal里

**Comment by qqxhb** [comment]
直接每张表单独执行gen 就好了？
