### ISSUE TITLE
生成的代码中的tablename有schema，导致select update 模式不工作

### ISSUE THREAD

**Issue by defp** [go-gorm/gen#695]
## Description

如图，生成的mode 表名中有schema字段，这样会导致使用 Select Updates，指定字段更新时，不会更新select指定的字段

<img width="747" alt="image" src="https://user-images.githubusercontent.com/612381/198490374-fceb90ec-5b85-4676-825e-2cf275359082.png">

测试代码

```

func main() {
	q := query.Use(model.DB).BizDisease
	d := &model.BizDisease{
		Name: "甲状腺功能减退",
	}
	updateResult, err := q.WithContext(context.Background()).Debug().Select(q.Name).Where(q.ItemID.Eq("Q4jpj31enua1")).Updates(d)

	if err != nil {
		nclog.Errorf("Error updating model: %v", err)
		return
	}
	nclog.Infof("updateResult: %v", updateResult)
}

```

代码输出测试

<img width="2069" alt="image" src="https://user-images.githubusercontent.com/612381/198491494-e0793ed9-aec1-424a-b55a-aae4509af6de.png">

类似问题 

https://github.com/go-gorm/gen/issues/569 

docs:

https://gorm.io/gen/update.html#Update-selected-fields

**Comment by defp** [comment]
deubg 
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/612381/198495457-2d19850a-0f9d-4126-bb68-ce92a1d10ffe.png">

**Comment by qqxhb** [comment]
升级gorm到最新版试下

**Comment by defp** [comment]
```
	gorm.io/datatypes v1.0.7
	gorm.io/driver/postgres v1.3.9
	gorm.io/gen v0.3.16
	gorm.io/gorm v1.24.0
	gorm.io/plugin/dbresolver v1.3.0
```
@qqxhb  最新版本也不行

**Comment by defp** [comment]
对于postgresql，gen在表名之前加了schema，如果没有schema是可以的工作的
```
const TableNameBizDisease = "public.biz_disease"
```

如上，schema是 public

**Comment by qqxhb** [comment]
postgresql这种可能确实没有兼容

**Comment by qqxhb** [comment]
@defp 可以通过这个配置，把schema去掉
[WithTableNameStrategy](https://gorm.io/gen/database_to_structs.html#Global-Generating-Options)

**Comment by defp** [comment]
@qqxhb 
// WithTableNameStrategy specify table name naming strategy, only work when syncing table from db

这个去掉schema查不出字段列表了

**Comment by defp** [comment]
```
  g.WithTableNameStrategy(func(tableName string) (targetTableName string) {
    fmt.Println(tableName)

    if strings.Contains(tableName, ".") {
      return strings.Split(tableName, ".")[1]
    }
    return tableName
  })
```

但是这个会用于查询数据库中表的字段名字吧

```
[339.390ms] [rows:-] SELECT c.column_name, constraint_type FROM information_schema.table_constraints tc JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name) JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema AND tc.table_name = c.table_name AND ccu.column_name = c.column_name WHERE constraint_type IN ('PRIMARY KEY', 'UNIQUE') AND c.table_catalog = 'dataengine' AND c.table_schema = CURRENT_SCHEMA() AND c.table_name = 'biz_disease'
2022/11/03 16:18:14 got 27 columns from table <biz_disease>
public.biz_table
2022/11/03 16:18:14 got 6 columns from table <biz_table>
public.biz_table_column
2022/11/03 16:18:14 got 10 columns from table <biz_table_column>
raw.raw_data_history
2022/11/03 16:18:14 got 0 columns from table <raw_data_history>
kg.kg_claim
2022/11/03 16:18:14 got 0 columns from table <kg_claim>
kg.kg_item_type_property
2022/11/03 16:18:14 got 0 columns from table <kg_item_type_property>
kg.kg_source
2022/11/03 16:18:14 got 0 columns from table <kg_source>
kg.kg_property
2022/11/03 16:18:14 got 0 columns from table <kg_property>
kg.kg_item_type
2022/11/03 16:18:14 got 0 columns from table <kg_item_type>
kg.kg_item
2022/11/03 16:18:15 got 0 columns from table <kg_item>
kg.kg_item_term
2022/11/03 16:18:15 got 0 columns from table <kg_item_term>
```

去查询的字段的话，不是public就会导致` 0 columns ` 
查询不到字段列表

**Comment by defp** [comment]
```
[423.700ms] [rows:-] SELECT c.column_name, c.is_nullable = 'YES', c.udt_name, c.character_maximum_length, c.numeric_precision, c.numeric_precision_radix, c.numeric_scale, c.datetime_precision, 8 * typlen, c.column_default, pd.description FROM information_schema.columns AS c JOIN pg_type AS pgt ON c.udt_name = pgt.typname LEFT JOIN pg_catalog.pg_description as pd ON pd.objsubid = c.ordinal_position AND pd.objoid = (SELECT oid FROM pg_catalog.pg_class WHERE relname = c.table_name AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = c.table_schema)) where table_catalog = 'dataengine' AND table_schema = CURRENT_SCHEMA() AND table_name = 'kg_item_type_property'
```

CURRENT_SCHEMA() 这个是不是有问题？

目前支持PG数据库连接的时候的search_path参数吗

**Comment by qqxhb** [comment]
@defp 那如果你现在是只有public的表才有 select update的需求，那你这里就先过滤public这个schema吧，我们看下兼容下带schema的 select update

**Comment by defp** [comment]
@qqxhb 有其他schema的需求，感谢🙏

**Comment by defp** [comment]
https://github.com/go-gorm/gorm/blob/master/callbacks/update.go#L207 

gorm 这个去查询 selectColumns 里的字段，参数的字段不匹配，就会忽略

**Comment by defp** [comment]
* GenerateModelAs 目前对于不是public schema的表，必须加schema才能查询到
* 如果不写schema，gorm.Open 的dsn加了search_path 也不行

**Comment by jjkoh95** [comment]
请问有更好的解决方法吗？

我遇到相似的问题 手动改每个`TableName` (不知道是否有Global改TableName的方法)

```go
user := g.GenerateModelAs(...)
user.TableName = "user" // 手动改TableName

g.Execute()
```

**Comment by qqxhb** [comment]
加schema其实主要是join场景，解决同名字段。确实不需要的话，可以全局通过option的方式，自定义tableName方法

**Comment by defp** [comment]
我目前遇到的加schema会导致select udpate 执行出错

**Comment by jjkoh95** [comment]
想请问
如果想要通过 def.user 取出 可是tablename为def 要用哪个option? 
尝试过 `g.WithTableNameStrategy` 得出没有table

因为我有同样的table definition, 只是data在不同的schema (eg staging.user, production.user)
然后在 `gorm` 里 我用Global的NamingStrategy.Prefix来替换schema

**Comment by qqxhb** [comment]
车上没电脑，等回家了，我发下

**Comment by qqxhb** [comment]
和表上的option一样，WithMethod

**Comment by jjkoh95** [comment]
谢谢你
我也尝试过用 WithMethod 可是需要复制很多 struct 来 return 每个不同的 TableName (还是可以有更好的方法?)
我现在只是在最后 QueryStructMeta 手动改 TableName 
如果可以 support NamingStrategy 在最后会更方便些

**Comment by jjkoh95** [comment]
也尝试过了手动改 TableName, 在利用 gorm 时 NamingStrategy 不会被采用
我只有手动删掉 ModelMethods

```go
user := g.GenerateModelAs(...)
user.TableName = "user" // 手动改TableName
user.ModelMethods = nil // 手动去掉TableName func

g.Execute()
```

想知道是否有 Option 不generate TableName 函数? （可否考虑加这）

**Comment by qqxhb** [comment]
@jjkoh95 
支持gorm的NamingStrategy，可以直接这样
	`conf.WithOpts(gen.WithMethod(gen.DefaultMethodTableWithNamer))`

**Comment by qqxhb** [comment]
如果是自定义TabelName也是可以的
方式和上面一样，自己实现一个TableName方法就可以了

**Comment by qqxhb** [comment]
新年快乐

**Comment by qqxhb** [comment]
[DIY-TableName](https://gorm.io/gen/database_to_structs.html#DIY-TableName)
参考 ，全局自定义表名，应该可以解决你们的问题
@defp @jjkoh95

**Comment by u-bing** [comment]
> 

@qqxhb 请教一下使用DIYMethods自定义TableName，如何实现如下的TableName：
```
func (m mytbale)TableName(shardId int32) string {
    const shardNumber = 100 // 这是自定义的常量
    return “mytbale_” + fmt.Sprintf("%d", shardId%shardNumber)
}
```

通过DIYMethods发现不能自定义函数body。 是否考虑把DIYMethods移出internal或提供外部option、通过直接定义DIYMethods的方式更灵活的diy。或者有其他更好的方式吗？ 感谢~~

```
// GetModelMethod get diy methods
func GetModelMethod(v interface{}, skip int) (method *DIYMethods, err error) {
        // 对于外部传进来的参数可以先进行断言
	if m, ok := v.(*DIYMethods); ok {
		return m, nil
	}
	method = new(DIYMethods)
        ...
```

**Comment by qqxhb** [comment]
@u-bing 通过DIYMethods发现可以自定义函数body呀，整个方法都是你自定义的，表名称可以用变量替换，比如：
```go
func (m *CommonMethod) TableName(ID int64) string {
	shard := 10
	return fmt.Sprintf("@@table%d", ID%shard)
}
```

**Comment by qqxhb** [comment]
@jjkoh95 去掉scheam也可以这样自定义，比如
```go
func (m *CommonMethod) TableName() string {
	tbs:=strings.Split("@@table",".")
	return tbs[len(tbs)-1]
}
// gen
gen.WithMethod(method.CommonMethod{}.TableName)
```

**Comment by jinzhu** [comment]
This should be fixed already, please upgrade gorm.io/gorm to latest version.
