### ISSUE TITLE
How to use decimal replace with float 64?

### ISSUE THREAD

**Issue by MikyChow** [go-gorm/gen#699]
In our project, We defined decimal(38) in our database, When we use gorm gen,It generate float64 as mapping. Is there any way to use decimal mapping?
Use it like  https://pkg.go.dev/github.com/shopspring/decimal

**Comment by qqxhb** [comment]
@MikyChow [FieldType](https://gorm.io/gen/database_to_structs.html#Field-Options) or [WithDataTypeMap](https://gorm.io/gen/database_to_structs.html#Data-Mapping)

**Comment by qqxhb** [comment]
@MikyChow 
specify import package path  by `WithImportPkgPath`
 e.g.
```go
cfg := gen.Config{xxx}
cfg.WithImportPkgPath("github.com/shopspring/decimal")
```

**Comment by MikyChow** [comment]
Thanks. Finally it worked
