### ISSUE TITLE
database to struct生成的结构体中的gorm tag能不能加一下comment

### ISSUE THREAD

**Issue by zhangdaogui** [go-gorm/gen#713]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

默认生成的结构体，注释在字段的后面，以//字段名，这样的话，我们使用autoMigrate生成的数据表，就不会有comment,反向再生成的时候，就会丢失comment

建议在tbl_column文件的buildGormTag方法中，加一个
````go
if c, ok := c.Comment(); ok {
    if c != "" {
	buf.WriteString(fmt.Sprintf(";comment:%s", c))
    }
}
````

这样就可以解决注释丢失的问题

**Comment by qqxhb** [comment]
@zhangdaogui 反向生成只建议在 自测场景使用，比如起一个docker反向生成表结构做测试
不建议反向生成用于真实环境

**Comment by zhangdaogui** [comment]
> 



> @zhangdaogui 反向生成只建议在 自测场景使用，比如起一个docker反向生成表结构做测试 不建议反向生成用于真实环境

那比如团队开发时，我自己建了新表，生成了新的结构体，其他成员migrate的时候，生成的表就没有注释了

**Comment by zhangdaogui** [comment]
而且在gorm tag里面加了comment之后，字段后面的//注释也就可以去掉了

**Comment by ZoftTy** [comment]
> 而且在gorm tag里面加了comment之后，字段后面的//注释也就可以去掉了

// 后面的提示可以被IDE识别

**Comment by qqxhb** [comment]
这两天加下

**Comment by qqxhb** [comment]
#784

**Comment by ZoftTy** [comment]
去掉后面注释后，vscode 获取不到当前字段的备注了

<img width="975" alt="image" src="https://user-images.githubusercontent.com/48001509/233247302-6359c3b2-fae8-416f-b839-8530e52b71c7.png">

这是之前带注释的版本

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/48001509/233247468-1ef0e2de-477b-44ea-88f9-b1ea6354231b.png">

**Comment by qqxhb** [comment]
@ZoftTy 后面会加上
