### ISSUE TITLE
我可以使用model通过运行中输入的字符串表名称值吗?

### ISSUE THREAD

**Issue by hzjux001** [go-gorm/gen#715]
query.SetDefault(db)
	Q := query.Q

	u := Q.CustomformMain9
	u.First()

	rto := reflect.TypeOf(*Q)
	rtv := reflect.ValueOf(*Q)
	for i := 0; i < rto.NumField(); i++ {
		if rto.Field(i).Name == "CustomformMain9" {
			v := rtv.Field(i)
			fmt.Println("v", v)
			//v.First()  //这里不能运行，我希望能通过输入的字符串的表名或者model名称找到对应的model,然后执行对应的数据库操作方法就象上面的u.First()一样,这样就可以实现动态的数据库操作了
		}

	}

**Comment by qqxhb** [comment]
@hzjux001 不可以，因为每个表的dao都不一样，并没有统一的接口
虽然都是`First()`，但是返回值是不同的
