### ISSUE TITLE
v0.3.18版本的clone修改引起的Statement污染问题

### ISSUE THREAD

**Issue by yuxinyin** [go-gorm/gen#721]
ReplaceConnPool 使clone的gorm.DB的clone为0，在Transaction中，tx.xxx.Where()内的db.getInstance 不会复制新的对象，在不使用WithContext的情况下，同一个table的不同查询会污染gorm.DB的statement，引起查询语句错误，我在开启了gen.WithoutContext的项目中，生成的query变的不安全

[代码回复](https://github.com/go-gorm/gen/commit/23008b285564a396ba5a9ae9d47c37a154319622#r92269503)

@qqxhb

**Comment by qqxhb** [comment]
@yuxinyin 这个问题我们看下
`WithoutContext`模式只是不强制使用`WithContext`，但这个方法还是保留的，你可以先都调用`WithoutContext`解决这个问题
