### ISSUE TITLE
不支持生成soft_delete.DeletedAt吗？

### ISSUE THREAD

**Issue by baiyuxiong** [go-gorm/gen#730]

**Comment by qqxhb** [comment]
@baiyuxiong 
自定义类型，手动指定就行，类似：
		`gen.FieldType("deleted_at", "soft_delete.DeletedAt")`
也可以手动指定下需要导入的包，比如：
`g.WithImportPkgPath("gorm.io/plugin/soft_delete")
`

**Comment by baiyuxiong** [comment]
已解决，谢谢。
g.GenerateAllTable(gen.FieldType("deleted_at", "soft_delete.DeletedAt"))
