### ISSUE TITLE
How to ORDER BY FIELD() by gen?

### ISSUE THREAD

**Issue by Nomango** [go-gorm/gen#739]
## Your Question

请问 gen 生成的代码是否可以实现 `ORDER BY FIELD('id', 3,2,1)` 这样的语句？

## Expected answer

`ORDER BY FIELD('id', 3,2,1)` 对应的 gen 代码

**Comment by qqxhb** [comment]
@Nomango 这种目前只能用diy的方式去写
[dynamic_sql](https://gorm.io/gen/dynamic_sql.html)

**Comment by qqxhb** [comment]
@Nomango 嗯嗯，自定义确实只能是最后一个，但是它前面可以和gen的方法一起用，类似这个
[Code-Snippets](https://gorm.io/gen/dynamic_sql.html#Code-Snippets)

**Comment by Nomango** [comment]
我在 gen 上面又封装了一层，需要用 ORDER BY FIELD() 的同时返回 DAO，不过暂时用下面这种方法解决了

```go
do.ReplaceDB(do.UnderlyingDB().Clauses(clause.OrderBy{
	Expression: clause.Expr{SQL: "FIELD(`id`, ?)", Vars: []any{ids}, WithoutParentheses: true},
}))
```
