### ISSUE TITLE
Allow default on primary key

### ISSUE THREAD

**Issue by jjkoh95** [go-gorm/gen#753]
## Your Question
Why do we disable default in primarykey? 
I'm using PG `gen_random_uuid` (sample attached at the bottom) as default but it doesn't output in struct and causes error 
To enable this I will have to manually add `gen.FieldGORMTag` for each of my tables. 

## The document you expected this should be explained
- https://github.com/go-gorm/gen/blob/cabead194e6762c56c953d883c6745ad98835657/internal/model/tbl_column.go#L118

## Expected answer
Perhaps it's limitation for other SQL dialects?
Can we consider removing the condition?

--- 
## Reproduce:
Notice that `uuid_col` default gets generated correctly but `id` is ignored instead.

### SQL scripts:
```sql
CREATE TABLE "test"."event_store" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid (),
  "mutation_event" text NOT NULL,
  "event_ts" timestamptz NOT NULL,
  "payload" jsonb NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "test"."event_store_with_uuid_col" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid (),
  "mutation_event" text NOT NULL,
  "event_ts" timestamptz NOT NULL,
  "payload" jsonb NOT NULL,
  "uuid_col" uuid NOT NULL DEFAULT gen_random_uuid (),
  PRIMARY KEY ("id")
);
```

### Generate structs
```go
// EventStore
type EventStore struct {
	ID            string            `gorm:"column:id;primaryKey" json:"id"`
	MutationEvent string            `gorm:"column:mutation_event;not null" json:"mutationEvent"`
	EventTs       time.Time         `gorm:"column:event_ts;not null" json:"eventTs"`
	Payload       datatypes.JSONMap `gorm:"column:payload;not null" json:"payload"`
}

// event_store_with_uuid_col
type EventStoreWithUUIDCol struct {
	ID            string            `gorm:"column:id;primaryKey" json:"id"`
	MutationEvent string            `gorm:"column:mutation_event;not null" json:"mutationEvent"`
	EventTs       time.Time         `gorm:"column:event_ts;not null" json:"eventTs"`
	Payload       datatypes.JSONMap `gorm:"column:payload;not null" json:"payload"`
	UUIDCol       string            `gorm:"column:uuid_col;not null;default:gen_random_uuid()" json:"uuidCol"`
}
```

**Comment by qqxhb** [comment]
@jjkoh95 
you can set global configuration for all tables like this:
`conf.WithOpts(gen.FieldGORMTag("id","xxx"))`

**Comment by jjkoh95** [comment]
Thanks @qqxhb 

But some of my tables don't require default, I have added manually using `gen.FieldGORMTag` for the ones that I need

I think this feature will provides better user experiences though I cannot be sure what other SQL DB treats default based on my limited testings (PG13+, MySQL8+ work fine)

It is not a deal breaker, just my two cent

**Comment by qqxhb** [comment]
#784
