### ISSUE TITLE
Fields cannot be custom converted when use PostgreSql

### ISSUE THREAD

**Issue by hhmy27** [go-gorm/gen#804]
## Fields cannot be custom converted
Hi, when I use the gen tool to generate code from postgresql, I found that the custom conversion type cannot take effect. Below is my table structure and generated model:

```sql
CREATE TABLE call_data
(
    A     INTEGER primary key,
    B     INTEGER,
    C     INTEGER
)
```

```go
type CallDatum struct {
	A          int32
	B         *int32
	C         *int32
}
```

Here's the conversion I expect:
```go
	var dataMap = map[string]func(detailType string) (dataType string){
		"tinyint":   func(detailType string) (dataType string) { return "int64" },
		"smallint":  func(detailType string) (dataType string) { return "int64" },
		"mediumint": func(detailType string) (dataType string) { return "int64" },
		"bigint":    func(detailType string) (dataType string) { return "int64" },
		"int":       func(detailType string) (dataType string) { return "int64" },
		"INTEGER":   func(detailType string) (dataType string) { return "int64" },
		"integer":   func(detailType string) (dataType string) { return "int64" },
	}
	g.WithDataTypeMap(dataMap)
```
I expected the Integer types to all be converted to int64, but that's not happening

## The document you expected this should be explained
I have consulted the documentation and materials, but int32 fields are still generated in the end.

## Expected answer
Any method capable of converting INTERGER type to int64

**Comment by qqxhb** [comment]
@hhmy27 You can take a look at the type tag on the generated model.
e.g. `column:age;type:int8`

**Comment by hhmy27** [comment]
> @hhmy27 You can take a look at the type tag on the generated model. e.g. `column:age;type:int8`

Thanks to your reply.
Here is a filed generated by gen:
```
id          int32   `gorm:"column:id;type:integer;primaryKey" json:"id"
```
the type tag is `type:integer;`.
I wrote the conversion rule as written above: `"integer": func(detailType string) (dataType string) { return "int64" },`, but it doesn't work,  and finally generates int32 field.

**Comment by qqxhb** [comment]
@hhmy27 try `numeric` .
[datatype-numeric](https://www.postgresql.org/docs/current/datatype-numeric.html)

**Comment by hhmy27** [comment]
> @hhmy27 try `numeric` . [datatype-numeric](https://www.postgresql.org/docs/current/datatype-numeric.html)

it doesn't work..

**Comment by qqxhb** [comment]
@hhmy27 [playground](https://github.com/go-gorm/playground/tree/feature/gen)

**Comment by qqxhb** [comment]
@hhmy27 

```go
dataMap := map[string]func(columnType gorm.ColumnType) (dataType string){
		"int2": func(columnType gorm.ColumnType) (dataType string) { //smallint
			return "int64"
		},
		"int4": func(columnType gorm.ColumnType) (dataType string) { //integer
			return "int64"
		},
		"int8": func(columnType gorm.ColumnType) (dataType string) { //bigint
			return "int64"
		},
	}
```
Configuration like this will work.
For More details, please refer to the postgreSQL datatype document I posted above.
