### ISSUE TITLE
动态查询遇到的问题，field.String

### ISSUE THREAD

**Issue by jhhuang2000** [go-gorm/gen#813]
##  如果我这样写：
c := dal.Category
p := c..GetFieldByName("categoryName")

p.xx  ，这里没有Eq，Like等参数，是bug吗？

**Comment by qqxhb** [comment]
@jhhuang2000 不是bug，返回的是接口，直接强转成实现就行，比如你提到的field.String

**Comment by jhhuang2000** [comment]
谢谢了，问题解决。
感觉返回 field.Field 会更好。

**Comment by qqxhb** [comment]
> 谢谢了，问题解决。 感觉返回 field.Field 会更好。

感谢建议，我们看下
