### ISSUE TITLE
Feature Request: Enhanced DataTypeMap

### ISSUE THREAD

**Issue by taobig** [go-gorm/gen#819]
按照文档： https://gorm.io/gen/database_to_structs.html#Data-Mapping ，在映射时我们只能获取字段的类型名称( *int/tinyint/varchar(100)/...* )，但不能知道字段是否可空、是否unsigned。希望扩展以支持在自定义mapping时可以感知这些信息。

**Comment by qqxhb** [comment]
@taobig 空和unsigned 有个全局配置，能满足吗？[Global-Generating-Options](https://gorm.io/gen/database_to_structs.html#Global-Generating-Options)
`FieldNullable`和`FieldSignable`，可null的会自动转指针，是unsigned会自动转成 类似uint

**Comment by taobig** [comment]
在我们的使用场景里，希望在处理字段映射时，将字段可空与否映射成不同的类型：
mysql datetime =>  time.Time
mysql datetime nullable => sql.NullTime

目前DataTypeMap似乎不能满足需求。

**Comment by qqxhb** [comment]
这个确实不支持，我们考虑下怎么支持。直接用`time.Time`和`*time.Time`，有问题吗？

**Comment by qqxhb** [comment]
@taobig #820 未发版，先拉master

**Comment by taobig** [comment]
Well done！
但是发现一个新问题，
```
"datetime": func(columnType gorm.ColumnType) (dataType string) {
			isNull, ok := columnType.Nullable()
			if !ok {
				t.Fatal("columnType.Nullable() error")
			}
			if isNull {
				return "sql.NullTime"
			} else {
				return "time.Time"
			}
		},
```
之前设置了全局的FieldNullable: true，那么现在指定mysql datetime nullable 为sql.NullTime时，实际会生成为*sql.NullTime。
所以当指定了具体某个mysql类型的typeMapping时，是否应该忽略全局设置的FieldNullable参数？

**Comment by qqxhb** [comment]
@taobig 这样改动会不兼容历史，影响业务逻辑，比如之前他生成的是带指针的，升级之后就丢了。

**Comment by qqxhb** [comment]
嗯嗯，签名是改了，不过影响的是生成时的逻辑，生成后的代码和之前的是一致的，不会影响业务逻辑。
后面的思路可以考虑下，也欢迎提PR呀
