### ISSUE TITLE
嵌套预加载无法工作

### ISSUE THREAD

**Issue by kaylee595** [go-gorm/gen#821]
```dal.DBResources = dal.ConnectDB(conf.DSN)
db := query.Use(dal.DBResources)
u := db.User
record, err := u.Preload(u.Company.Users).First()
```
u.Company可以正常预加载, 但是我无法编写Company.Users, IDE会告诉我语法错误, Company下面没有Users.

**Comment by qqxhb** [comment]
@kaylee595 不支持嵌套哈。 user-> load company 是先查user，然后用userid 召回company；最终返回的是 user，只是属性company也有值。

我理解你的这个场景，应该用company -> load user ，`db.Company.Preload(db.Company.User).Fisrt()`

**Comment by Carseason** [comment]
u.Preload(field.NewRelation("Company.Users", "")).First()
