### ISSUE TITLE
表中的某个字段是一个json字符串，我想生成的model中这个字段是一个自定义结构体，查询时报错

### ISSUE THREAD

**Issue by l54808821** [go-gorm/gen#866]
生成的代码
```
	g.UseDB(db)
	g.ApplyInterface(func(ExtendedMethod) {},
		g.GenerateModel("t_team", gen.FieldType("members", "[]int32")))
	g.Execute()
```
测试代码
```
	dal.SetDefault(db)

	teamQuery := dal.Q.TTeam
	first, _ := teamQuery.Where(teamQuery.ID.Eq(1)).First()
	println(first.Name)
```

报错
```
[error] unsupported data type: &[]
panic: Cannot parse model: &{ID:0 Name: AppID:0 Description: Logo: Category:0 Owner:0 Members:[] IsDeleted:0 CreatedTime:0001-01-01 00:00:00 +0000 UTC UpdatedTime:0001-01-01 00:00:00 +0000 UTC}
unsupported data type: &[]
```

请问，我是在操作中有什么问题么

**Comment by qqxhb** [comment]
@l54808821 自定义类型需要实现 Scan/Value方法
[Scanner-x2F-Valuer](https://gorm.io/docs/data_types.html#Scanner-x2F-Valuer)
或者加上序列化tag [Serializer](https://gorm.io/docs/serializer.html#content-inner)

**Comment by l54808821** [comment]
感谢您的回复，我在生成的members字段添加了serializer:json 已经解决了
但是我的model也是通过生成的，有什么方法追加一个gorm的 serializer:json   tag

**Comment by l54808821** [comment]
这样做好像ok了，非常感谢

**Comment by l54808821** [comment]
g.ApplyInterface(func(ExtendedMethod) {},
		g.GenerateModel("t_team",
			gen.FieldType("members", "[]int32"),
			gen.FieldGORMTag("members", func(tag field.GormTag) field.GormTag {
				tag.Set("serializer", "json")
				return tag
			}),
		))

**Comment by l54808821** [comment]
WithNewTagNameStrategy 这个 gorm.io/gen v0.3.22 是不是已经废弃了，有啥替代方法呢

**Comment by qqxhb** [comment]
@l54808821 FieldNewTagWithNS这个是不是就可以了？

**Comment by l54808821** [comment]
@qqxhb v0.3.22 已经没有这个方法了
