### ISSUE TITLE
Questions about the common use of GenerateModel and GenerateAllTable

### ISSUE THREAD

**Issue by cha0ran** [go-gorm/gen#871]
I have multiple tables and I want to customize the fields for certain tables during generation. There may be duplicate or identical field names among them, and I want to define them based on the table names. However, when using both ApplyBasic(g.GenerateAllTable()...) and ApplyBasic(g.GenerateModel(..)), I found that the definitions for individual tables are not taking effect. Am I using the methods incorrectly? I don't want to define each table separately using GenerateModel.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gen/pull/869/files

**Comment by cha0ran** [comment]
Didn't get it, and I don't think it solved my problem. I still can't modify the fields for different tables

**Comment by qqxhb** [comment]
@cha0ran Give an example.

**Comment by qqxhb** [comment]
@cha0ran Change the calling order of these two methods.
```go
g := gen.NewGenerator(gen.Config{})
one := g.GenerateModel(
	"one",
	gen.FieldRename("time", "time_at"),
)


g.ApplyBasic(g.GenerateAllTable()...)

g.ApplyBasic(one)

g.Execute()
```

**Comment by cha0ran** [comment]
@qqxhb 
Okay, perhaps my example wasn't accurate enough. Generally, it works like that, but the situation can be different when there's an error with the field. As I mentioned in another issue, when the field name cannot be processed correctly, I need to rename that field, and it will no longer be valid.

The table field name is "1688_shop_name".

**Comment by cha0ran** [comment]
Wow, when I used it like that, something unexpected happened. It's "NT" in the query, but "NL" in the model.

```golang

g.ApplyBasic(g.GenerateAllTable(
	gen.FieldRename("1688_shop_name", "NT_1688_shop_name"), // Removing these two lines will result in an error.
	gen.FieldRename("1688_order_number", "NT_1688_order_number"), // Same as above.
)...)

g.ApplyBasic(g.GenerateModel("purchases",
	gen.FieldRename("1688_shop_name", "NL_1688_shop_name"),
	gen.FieldRename("1688_order_number", "NL_1688_order_number"),
))

g.Execute()
```

**Comment by qqxhb** [comment]
@cha0ran I don't quite understand. It's all about changing names, so why doesn't it take effect anymore?
However, starting field names with numbers is not standardized, and programming languages generally do not recognize them.

**Comment by cha0ran** [comment]
@qqxhb Yes, it is true that field names starting with numbers are not conventional in Go language. However, in MySQL, it is allowed, and the field already exists in the database. I cannot modify the numeric field in the database, so I need to change the field name during the generation process. If I don't modify it in the `GenerateAllTable` function, it will still throw an error and cause the generation to fail.

**Comment by cha0ran** [comment]
```golang
tables := g.GenerateAllTable()

for i, table := range tables {
	QueryMeta := reflect.ValueOf(table)
	typeOfQueryMeta := QueryMeta.Elem()
	tableName := typeOfQueryMeta.FieldByName("TableName")

	if tableName.String() == "purchases" {
		tables[i] = g.GenerateModel("purchases",
			gen.FieldRename("1688_shop_name", "NL_1688_shop_name"),
			gen.FieldRename("1688_order_number", "NL_1688_order_number"),
		)
	}
}

g.ApplyBasic(tables...)

g.Execute()
```

As a beginner in Golang, I'm not sure if it's the correct approach, but at least it solves the issue.

**Comment by qqxhb** [comment]
@cha0ran The renaming at the beginning of a number does not need to be distinguished by a table, right? We need to change everything.

**Comment by qqxhb** [comment]
@cha0ran try again.
e.g.
```go
g.ApplyBasic(g.GenerateModel("purchases",
	gen.FieldRename("1688_shop_name", "NL_1688_shop_name"),
	gen.FieldRename("1688_order_number", "NL_1688_order_number"),
))

g.WithTableNameStrategy(func(tableName string) (targetTableName string) {
		if tableName == "purchases" { //ignore table
			return ""
		}
		return tableName
	})

g.ApplyBasic(g.GenerateAllTable()...)

g.Execute()
```

**Comment by cha0ran** [comment]
@qqxhb That’s great! It turns out it can be done this way. It seems much more elegant than my approach.

**Comment by jpenna** [comment]
@qqxhb I think this should be in the documentation as the way we can ignore tables.

In my case, the table is called `_prisma_migrations` and the file had the `_`  prepended and `gen.go` couldn't access it. It would be better to just ignore this table, and this is how it can be done.

**Comment by qqxhb** [comment]
@jpenna Documentation has been updated. https://gorm.io/gen/database_to_structs.html#Ignore-Table
