### ISSUE TITLE
代码生成不到我想要的位置

### ISSUE THREAD

**Issue by yangyile1990** [go-gorm/gen#874]
我把路径打印了出来，结果生成的位置跟我想要的位置不同。除非我的路径是以model结尾的，位置才能相同：
         fmt.Println(path)
         //show /Users/admin/main_gorm_gen/model
	g := gen.NewGenerator(gen.Config{
		OutPath: path,
	})
	g.UseDB(db)
	g.GenerateAllTable()
	g.Execute()

**Comment by jinzhu** [comment]
暂时不支持放到同一目录下

**Comment by gh73962** [comment]
不太理解，后面会有规划吗

> 暂时不支持放到同一目录下

**Comment by qqxhb** [comment]
@gh73962 看你的代码只生成了model，所以是想单独指定model的路径吗？ 
``` go 
gen.Config{
ModelPkgPath: path,
}
```

**Comment by gh73962** [comment]
> @gh73962 看你的代码只生成了model，所以是想单独指定model的路径吗？
> 
> ```go
> gen.Config{
> ModelPkgPath: path,
> }
> ```

这个代码是@yangyile1990 提供的
游戏业务的model非常多，不能统一的划分在一个model目录下管理

**Comment by gh73962** [comment]
我们先fork自己改下用，因为不用query，涉及的query部分不太了解，就不提PR了

**Comment by qqxhb** [comment]
@gh73962 所以你们的问题是一样的吗？
model路径可以通过 `ModelPkgPath` 指定

**Comment by qqxhb** [comment]
@gh73962 Ok
