### ISSUE TITLE
gen最新的v0.3.22没有WithJSONTagNameStrategy方法了，很需要

### ISSUE THREAD

**Issue by l54808821** [go-gorm/gen#881]
gen最新的v0.3.22没有WithJSONTagNameStrategy方法了，很需要这个

因为gen生成的命名中有的Id为ID，我需要自定义一个json tag用大驼峰去命名

**Comment by qqxhb** [comment]
@l54808821 确定是这个吗？ 看代码还有呀[v0.3.22/config.go](https://github.com/go-gorm/gen/blob/v0.3.22/config.go#LL102C20-L102C43)

**Comment by l54808821** [comment]
@qqxhb 抱歉，搞错了，是这个WithNewTagNameStrategy

**Comment by qqxhb** [comment]
@l54808821 这个确实是去掉了，可以在gen config配置
e.g.
```go
config.WithOpts(gen.FieldNewTagWithNS("json", func(columnName string) string {
            return strings.ToLower(columnName)
	}))
```

**Comment by l54808821** [comment]
优秀呀，非常帅，也希望稳定能及时更新一波

**Comment by qqxhb** [comment]
好的好的
