### ISSUE TITLE
有没有配置修改生成的实体类的名称

### ISSUE THREAD

**Issue by kuangshp** [go-gorm/gen#909]
我希望根据数据库表批量生成go的实体类可以自定义结构体名称
比如我数据库叫`user`我希望结构体是`UserEntity` ，`role`表生成的结构体是`RoleEntity`这样的，不知道有什么配置可以操作

**Comment by qqxhb** [comment]
@kuangshp `g.WithModelNameStrategy`

https://gorm.io/gen/database_to_structs.html#Global-Generating-Options
