### ISSUE TITLE
can't import rawsql_driver

### ISSUE THREAD

**Issue by to2false** [go-gorm/gen#920]
## Your Question

` go get gorm.io/gen/rawsql_driver@v0.3.23`

here is return:
```
go: module gorm.io/gen@v0.3.23 found, but does not contain package gorm.io/gen/rawsql_driver
```

## Expected answer

import rawsql_driver successfully

**Comment by qqxhb** [comment]
@to2false https://gorm.io/gen/database_to_structs.html#Generate-From-Sql
