### ISSUE TITLE
Why is gen.Condition not compatible with clause.Expression

### ISSUE THREAD

**Issue by go-ltbf** [go-gorm/gen#93]
## Your Question
How to use `gorm.io/datatypes` JSON type and JSONQueryExpression?

## Expected answer
How to achieve the previous effect？

**Comment by riverchu** [comment]
The release version `v0.0.17` now support JSONQueryExpression. And usage can be found [here](https://github.com/go-gorm/gen/tree/v0.0.17#json-query)

**Comment by go-ltbf** [comment]
Why can't I use custom datatype(implement clause.Expression interface)?
