### ISSUE TITLE
how I can convert bit(1) to bool ?

### ISSUE THREAD

**Issue by nobject** [go-gorm/gen#930]
## Your Question
I have a field `deleted`, the field defined `bit(1)` type。 I want to gen `bool` type.
I use dataMap like this:

```golang
var dataMap = map[string]func(gorm.ColumnType) (dataType string){
		// bool mapping
		"bit": func(columnType gorm.ColumnType) (dataType string) {
			ct, _ := columnType.ColumnType()
			if strings.HasPrefix(ct, "bit(1)") {
				return "bool"
			}
			return "byte"
		},
	}
```
the model gen:
```golang
Deleted                     bool      `gorm:"column:deleted;not null;default:b'0;comment:: 0:1" json:"deleted"` // : 0:1
```
but the field has default value, it where report error below:
```
failed to parse b'0 as default value for bool, got error: strconv.ParseBool: parsing "b'0": invalid syntax
```

## Expected answer
I want to know how to avoid the error and are there have the better advise to handle bit(1) type ?

**Comment by qqxhb** [comment]
@nobject 
try remove default tag
```go
g.WithOpts(gen.FieldGORMTagReg("deleted", func(tag field.GormTag) field.GormTag {
		tag.Remove("default")
		return tag
	}))
```

**Comment by qqxhb** [comment]
tips:[Soft-Delete](https://gorm.io/docs/delete.html#Soft-Delete)

**Comment by nobject** [comment]
> @nobject try remove default tag
> 
> ```go
> g.WithOpts(gen.FieldGORMTagReg("deleted", func(tag field.GormTag) field.GormTag {
> 		tag.Remove("default")
> 		return tag
> 	}))
> ```

thanks,  it works.  but if i has lots of fields is bit(1) type(example: is_online, is_lock and so on),  i should write the method every times.

**Comment by qqxhb** [comment]
@nobject 

```go
g.WithOpts(gen.FieldGORMTagReg("^is_.*", func(tag field.GormTag) field.GormTag {
		tag.Remove("default")
		return tag
	}))
```
