### ISSUE TITLE
为什么 gen.Cond 要约束为datatypes的指定三种数据结构，如果需要扩展使用怎么办呢？

### ISSUE THREAD

**Issue by rogeecn** [go-gorm/gen#931]
## Your Question

`gen.Cond` 方法约束死了类型为 `*datatypes.JSONQueryExpression, *datatypes.JSONOverlapsExpression, *datatypes.JSONArrayExpression` 这三种才可以转化。
```
func exprToCondition(exprs ...clause.Expression) []Condition {
	conds := make([]Condition, 0, len(exprs))
	for _, e := range exprs {
		switch e := e.(type) {
		case *datatypes.JSONQueryExpression, *datatypes.JSONOverlapsExpression, *datatypes.JSONArrayExpression:
			conds = append(conds, &condContainer{value: e})
		default:
			conds = append(conds, &condContainer{err: fmt.Errorf("unsupported Expression %T to converted to Condition", e)})
		}
	}
	return conds
}
```

## The document you expected this should be explained

我目前的情况是需要扩展 `datatypes.JSONQueryExpression` 添加一个 `Like` 查询方法。目前直接使用库无法完成。我目前操作是使用 `go vendor ` 把库拉回项目中，然后修改 vendo 内 `gen/condition.go`代码， 把 `switch` 断言忽略掉，直接暴力 `conds = append(conds, &condContainer{value: e})`。其中 `e` 为我自己定义的 实现`Build(builder clause.Builder)` 接口的对象。

## Expected answer

可有更优雅的实现方案呢？

**Comment by qqxhb** [comment]
@rogeecn 主要是基于安全考虑，所以做了一些限制；后面会支持用户自定义

**Comment by jiazheng2** [comment]
现在还是不支持用户自定义
