### ISSUE TITLE
I found that using Where and FindByPage at the same time will panic

### ISSUE THREAD

**Issue by go-ltbf** [go-gorm/gen#94]
## Your Question

```go
// gorm version: v1.21.15
// gen version: v0.0.16
user := query.NewUser(db)
_, _, _ = user.Model(&models.User{}).FindByPage(0, 5) // is ok
_, _, _ = user.FindByPage(0, 5) // is ok
_, _, _ = user.Model(&models.User{}).Where(user.ID.In(1, 2)).FindByPage(0, 5) // is ok
_, _, _ = user.Where(user.ID.In(1, 2)).FindByPage(0, 5) // panic
```

## The document you expected this should be explained
I found that using Where and FindByPage at the same time will panic.

## Expected answer
I hope to fix it ASAP.

**Comment by riverchu** [comment]
It's a fixed bug, you should update version by `go get gorm.io/gen`

**Comment by riverchu** [comment]
I cannot reproduce the panic you mentioned, maybe you can provide complete test code

**Comment by riverchu** [comment]
`v0.0.17` fix some bugs, you should upgrade and try again

**Comment by go-ltbf** [comment]
Thanks, `v0.0.17` is ok.
