### ISSUE TITLE
Template-based DIY method, with access to table name and column names etc (QueryStructMeta)

### ISSUE THREAD

**Issue by jjkoh95** [go-gorm/gen#963]
## Describe the feature
- https://gorm.io/gen/sql_annotation.html#Template-Placeholder
- https://gorm.io/gen/database_to_structs.html#Methods-Template

Expose an alternative template-based method to construct DIY method, with access to fields (QueryStructMeta) -- currently no easy way to access columns/fields.

## Motivation
It offers better flexibility and familiarity to users.

## Related Issues
N/A

---

## Example interface:

```go
type Audit interface {
	// func (m *{{ @@tableName }}) AfterSave(tx *gorm.DB) (err error) {
	//   tx.Create(&AuditTable{
	//     {{ range $index, $fieldName := @@fieldNames }} {{ $fieldName }}: m.{{ $fieldName }}
	//     {{ end }}
	//   })
	// }
	AfterSave(tx *gorm.DB) error
}
```

**Comment by jinzhu** [comment]
```
type Audit struct {
}

func (m *Audit) AfterSave(tx *gorm.DB) error {
    bytes, err :=   json.Marshal(m)
    auditTable := AuditTable{}
    json.Unmarshal(&auditTable, bytes)
    tx.Create(&auditTable)
}
```

Maybe generate the AfterSave method like this?

**Comment by jjkoh95** [comment]
Thanks @jinzhu 
I believe exposing a template-based method is easier for some other usecases.
Alternatively, I would love to have access to some internal structs eg `QueryStructMeta`, `model.Field` (the types are in `internal`) so I can have simpler ways to modify them.

---
As a side note, currently I use reflect below to access to those fields and pass it to my custom go-template:
```go
func FieldBy(
	model interface{},
	name string,
) interface{} {
	e := reflect.ValueOf(model).Elem()
	for i := 0; i < e.NumField(); i++ {
		if name == e.Type().Field(i).Name {
			return e.Field(i).Interface()
		}
	}
	return nil
}

func InterfaceSlice(slice interface{}) []interface{} {
	s := reflect.ValueOf(slice)
	if s.Kind() != reflect.Slice {
		panic("InterfaceSlice() given a non-slice type")
	}
	// Keep the distinction between nil and empty slice input
	if s.IsNil() {
		return nil
	}
	ret := make([]interface{}, s.Len())
	for i := 0; i < s.Len(); i++ {
		ret[i] = s.Index(i).Interface()
	}
	return ret
}
```
