### ISSUE TITLE
在 model.Field 类型中加入 gorm.ColumnType

### ISSUE THREAD

**Issue by shuqingzai** [go-gorm/gen#964]
## Describe the feature

在 `dataMap()` 签名中包含 `gorm.ColumnType` 参考： https://github.com/go-gorm/gen/blob/d18f8d3048108cce5e780d0f23809b90533b618f/config.go#L97 可以得到字段的很多源信息，进行更自由的自定义操作，可是在 `field_options` 相关的方法签名中却没法得到这些信息（签名都是：`model.Field`）， 使用 `FieldModify` 修改字段信息时，很受限
参考： https://github.com/go-gorm/gen/blob/d18f8d3048108cce5e780d0f23809b90533b618f/field_options.go#L23 
比如：我需要向字段追加一个验证标签("v:id")，用于验证字段内容是否符合某种规则，目前只能根据字段名称或字段类型定义我的验证规则，我没法知道这个字段是否为自增，是否为唯一索引等更多信息，自定义字段内容的功能受限

虽然可以从 `model.Field.GORMTag` 中解析，但这样我不确定是否可以准确

希望可以把 `gorm.ColumnType`  追加到 `model.Field` 结构体中

**Comment by shuqingzai** [comment]
`model.Field.GORMTag` 中获取的字段信息也是受限的，如下数据库中的 `completedTime` 是允许为 `null` 的
 
![image](https://github.com/go-gorm/gen/assets/44406033/2bd778bf-8105-4bdf-a89a-ef868258acc3)

**Comment by qqxhb** [comment]
@shuqingzai 可以根据gormtag去判断下，只有不允许位null的才会出现在tag里，唯一键也是一眼的，只有是唯一键的时候，才有这个tag

**Comment by shuqingzai** [comment]
> @shuqingzai 可以根据gormtag去判断下，只有不允许位null的才会出现在tag里，唯一键也是一眼的，只有是唯一键的时候，才有这个tag

那我有办法知道当前操作是哪个数据表吗？因为一次生成多个model时，批量执行，在使用 `FieldModify` 操作字段时，有办法知道当前的表吗？？

**Comment by qqxhb** [comment]
@shuqingzai 不能判断。
如果你是想改个别表字段，那就直接在`GenerateModel`后面加option
如果你是想改所有表的某些字段，那你就直接用全局的配置`g.WithOpts`
如果你是想改一部分表，建议你可以，线apply其他表，后调用`g.WithOpts`，然后在apply要改的那部分表
