### ISSUE TITLE
根据数据表生成 model ，支持把表注释加上

### ISSUE THREAD

**Issue by shuqingzai** [go-gorm/gen#966]
## Describe the feature

现在根据数据表自动生成模型文件时，只会把 `mapped from table <tableName>` 添加到模型上，作为模型注释，这意义不大，能否把 表注释也加上？？

目前生成的模型

![image](https://github.com/go-gorm/gen/assets/44406033/1a5aba70-a4c0-421b-806d-3631df291281)

数据表定义的注释

![image](https://github.com/go-gorm/gen/assets/44406033/29175796-f8c4-4e2f-8e59-f76816ce873c)

希望可以类似下面的效果

```go
// PeriodicTask 定时任务表
// 
// mapped from table <periodic_task>
type PeriodicTask struct {
	ID uint64 `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id,string" dc:"id"`
}
```

IDE 查看效果

![image](https://github.com/go-gorm/gen/assets/44406033/f07c8ce1-3d11-4c88-a84f-53fe7f0ad83e)

因为项目越来越大的时候，数据表太多了，有时可能没法很好的记得每张表的含义

**Comment by qqxhb** [comment]
#975
