### ISSUE TITLE
gen的FirstOrCreate方法的入参与grom的文档不一致，无法按照例子使用

### ISSUE THREAD

**Issue by langwan** [go-gorm/gen#967]
gorm的FirstOrCreate方法需要传入一个model作为参数来插入新的数据，gen的FirstOrCreate方法没有任何入参，所以无法参考gorm的文档使用，看了文档没有看明白使用方法，能给一个例子么？

**Comment by qqxhb** [comment]
@langwan 用Attr传model就行了，这个和gorm是一致的
https://gorm.io/gen/query.html#FirstOrCreate
