### ISSUE TITLE
the name of my package conflicts with the name of struct generated gorm-gen

### ISSUE THREAD

**Issue by tzq0301** [go-gorm/gen#971]
## Description

<img width="968" alt="image" src="https://github.com/go-gorm/gen/assets/58631544/452e56f6-eab5-4733-8167-14ed45bf63b1">

**Comment by qqxhb** [comment]
@tzq0301 FieldRename
https://gorm.io/gen/database_to_structs.html#Field-Options

**Comment by tzq0301** [comment]
能说详细点吗，不是很懂应该怎么用

**Comment by qqxhb** [comment]
> 能说详细点吗，不是很懂应该怎么用

看下文档的可选项，要么改下包的名字，要么改下struct的名字就行

**Comment by HYisen** [comment]
In my view, I was facing the same situation while @qqxhb does not on the same page.

## Problem

Generation of widget.Widget would fail.

```go
package widget

type Widget struct {
	ID   int
	Name string
}
```

```go
package main

func main() {
	g := gen.NewGenerator(gen.Config{
		OutPath:      "./clients/query",
		ModelPkgPath: "",
		Mode:         gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface,
	})
	g.ApplyBasic(widget.Widget{})
	g.Execute()
}
```

open the generated file query/widgets.gen.go,
IDE hints error Unresolved type 'Widget'

## Cause

gen creates struct in the name widget in query/widgets.gen.go

```go
type widget struct {
	widgetDo

	ALL  field.Asterisk
	ID   field.Int
	Name field.String

	fieldMap map[string]field.Expr
}
```

but that name is also used in the generated file, such as
`First() (*widget.Widget, error)`


the code `widget.Widget` shall be linked to struct Widget in package widget,
but the compliler read it as linked to struct widget in the generated file.

## Solution

### A

Move struct Widget out of package widget, maybe model.Widget, just like what it is in gen's demo.

### B

As I found in the source code, but not in gen document.

make struct Widget implements `interface{ GenInternalDoName() string }`

```go
package widget

type Widget struct {
	ID   int
	Name string
}

func (w Widget) GenInternalDoName() string {
	return "foobar"
}
```

Watch out the value rather pointer receiver.

Regenerate, and everything goes on well, inside file widgets.gen.go,
the struct foobar take the place of previous struct widget.

I believe the internal name here less matters, as it's internal.
