### ISSUE TITLE
当从 SQL 文件中获取表结构的时候，当某个字段是 BIGINT UNSIGNED（非 unsigned）时，不会解析成 uint64

### ISSUE THREAD

**Issue by tzq0301** [go-gorm/gen#973]
## GORM Playground Link

参考 https://github.com/tzq0301/demo-gorm-gen 的代码，cmd/gorm-gen/main.go 生成代码

## Description

将 https://github.com/tzq0301/demo-gorm-gen 中 go.mod 的 replace 行去掉，运行 go run cmd/gorm-gen/main.go

**Comment by qqxhb** [comment]
https://github.com/go-gorm/rawsql/pull/3
直接改sql文件那边的逻辑了
