### ISSUE TITLE
生成model的时候，可以指定继承某个结构体吗

### ISSUE THREAD

**Issue by XiaoSGentle** [go-gorm/gen#990]
## Your Question

![image](https://github.com/go-gorm/gen/assets/107936135/c74230a3-db99-4465-83f0-dd08bea64a6c)

类似这样的

请问是否有这样的配置？

还有可以指定某个表不生成吗?

非常感谢能够做出回答~

**Comment by kuangshp** [comment]
其实没必要的，我之前也是搞继承，现在直接放弃了，直接全部生成，毕竟这个东西不能选择某一张表来生成，都是批量操作

**Comment by qqxhb** [comment]
base目前是不支持的；
选择生成的表是可以的，看下文档 https://gorm.io/gen/database_to_structs.html#Quick-Start

指定某个表不生成的话没有直的方法，但是可以实现的`WithTableNameStrategy`，这个option对需要排除的表，返回空字符就行

**Comment by Alice52** [comment]
@XiaoSGentle 后面有找到实现方式吗？
