### ISSUE TITLE
How to use the function "WithDbNameOpts" ?

### ISSUE THREAD

**Issue by pengyuxiang1** [go-gorm/gen#996]
The model code function 'TableName()' that I want to generate returns a string of table name and database name.  like this:
```golang
// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}

const TableNameAddress = "myDbName.user"
```

Can I do this with the function 'WithDbNameOpts()'?

If that doesn't work, what should I do？

**Comment by qqxhb** [comment]
@pengyuxiang1 https://gorm.io/gen/database_to_structs.html#DIY-TableName
